<div class="mb-3"><a href="<?php echo html_escape($back_url); ?>" class="btn btn-outline-secondary btn-sm mb-2">&larr; Kembali</a><h4 class="mb-1">Pengaturan Daily Matrix Spreadsheet</h4><div class="text-muted">Pilih workbook dan tab secara dinamis. Tautan serta pemetaan disimpan privat di server, bukan di source code.</div></div>
<div class="row g-3" data-inventory-matrix-settings data-discover-url="<?php echo html_escape($discover_url); ?>" data-save-url="<?php echo html_escape($save_url); ?>" data-csrf="<?php echo html_escape($csrf); ?>">
  <div class="col-xl-7"><div class="card"><div class="card-header"><strong>Workbook dan pemetaan tab</strong></div><div class="card-body">
    <div class="mb-3"><label class="form-label" for="imsUrl">Tautan Google Spreadsheet</label><input class="form-control" id="imsUrl" type="url" placeholder="https://docs.google.com/spreadsheets/d/.../edit" value="<?php echo !empty($settings['spreadsheet_id']) ? html_escape('https://docs.google.com/spreadsheets/d/' . $settings['spreadsheet_id'] . '/edit') : ''; ?>"><div class="form-text">Akun service Google harus mendapat akses Editor ke workbook ini.</div></div>
    <div class="d-flex flex-wrap gap-2 mb-3"><button class="btn btn-outline-primary" type="button" data-ims-discover>Muat tab spreadsheet</button><button class="btn btn-primary" type="button" data-ims-save>Simpan pengaturan</button><span class="small align-self-center" data-ims-status></span></div>
    <div class="mb-3"><label class="form-label" for="imsWarehouse">Gudang pusat (STOREROOM)</label><select class="form-select" id="imsWarehouse" data-ims-sheet data-setting-name="warehouse_sheet_id" data-saved="<?php echo html_escape((string)($settings['warehouse_sheet_id'] ?? '')); ?>"><option value="">Muat tab spreadsheet dahulu</option></select></div>
    <hr><h6>Tab per divisi</h6>
    <?php foreach ((array)$divisions as $division): $id = (int)($division['id'] ?? 0); $label = trim((string)($division['code'] ?? '') . ' - ' . (string)($division['name'] ?? '')); ?>
    <div class="row align-items-center g-2 mb-2"><label class="col-md-4 col-form-label" for="imsDivision<?php echo $id; ?>"><?php echo html_escape($label !== ' - ' ? $label : ('Divisi ' . $id)); ?></label><div class="col-md-8"><select class="form-select" id="imsDivision<?php echo $id; ?>" data-ims-sheet data-setting-name="division_sheet_<?php echo $id; ?>" data-saved="<?php echo html_escape((string)($settings['division_sheets'][(string)$id] ?? '')); ?>"><option value="">Muat tab spreadsheet dahulu</option></select></div></div>
    <?php endforeach; ?>
    <div class="alert alert-info mt-3 mb-0">Tab utama mengikuti bulan yang terakhir diperbarui. Sistem membuat tab arsip <code>NamaTab_YYYY-MM</code> untuk menyimpan snapshot setiap bulan. Divisi tanpa stok boleh tidak dipetakan; jika ternyata memiliki stok, pembaruan akan ditolak sampai tab dipilih. Bahan baku dan BASE/PREPARE per divisi digabung dan dibedakan melalui Domain/Jenis. Tanggal yang sudah lewat diberi warna lembut berbeda dan garis batas tegas; hari ini serta tanggal mendatang tetap polos.</div>
  </div></div></div>
  <div class="col-xl-5"><div class="card h-100"><div class="card-header"><strong>Panduan dan perlindungan data</strong></div><div class="card-body">
    <ol class="ps-3"><li>Tempel tautan workbook, lalu klik <strong>Muat tab spreadsheet</strong>.</li><li>Pilih tab tujuan gudang dan tiap divisi. Nama tab tidak ditanam di kode dan semua pemetaan harus unik.</li><li>Bagikan workbook dengan service account aplikasi sebagai <strong>Editor</strong>; alamatnya dapat dilihat di pengaturan Google Sheets Produk.</li><li>Pada halaman daily matrix, pilih bulan lalu klik <strong>Perbarui Spreadsheet</strong>. Tidak ada pembaruan otomatis.</li></ol>
    <div class="alert alert-warning mb-0">Tab yang pertama kali dipakai harus kosong. Tab berisi data manual tanpa penanda ekspor akan ditolak. Hanya tab terpilih dan tab arsip terkait yang diubah; database tidak ditulis dan tidak ada migrasi SQL.</div>
  </div></div></div>
</div>
