<?php

declare(strict_types=1);

$checks=0;$failures=[];
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok){$failures[]=$message;fwrite(STDERR,'FAIL: '.$message.PHP_EOL);return;}echo 'PASS: '.$message.PHP_EOL;};
function a58t_rm(string $root,string $path):void{if(strpos($path,$root)!==0)throw new RuntimeException('unsafe cleanup');if(is_link($path)||is_file($path)){@unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$entry)if($entry!=='.'&&$entry!=='..')a58t_rm($root,$path.'/'.$entry);@rmdir($path);}
function a58t_run(array $command,string $cwd,array $env):array{$p=proc_open($command,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$cwd,$env);if(!is_resource($p))return['code'=>255,'out'=>'','err'=>''];$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return['code'=>proc_close($p),'out'=>(string)$out,'err'=>(string)$err];}
function a58t_code(array $result):string{$json=json_decode(trim($result['err']),true);return is_array($json)?(string)($json['code']??''):'';}

$root=dirname(__DIR__,2);$probe=$root.'/tools/db/auth_login_failure_named_fk_contract_probe.php';
define('A58_NAMED_FK_LIBRARY_ONLY',true);require $probe;
$sql=a58_named_fk_sql();
$check(a55_safe_select($sql)&&substr_count($sql,';')===0,'named FK statement is a strict safe SELECT with no embedded terminator');
$check(strpos($sql,'information_schema.KEY_COLUMN_USAGE')!==false&&strpos($sql,'information_schema.REFERENTIAL_CONSTRAINTS')!==false&&strpos($sql,'sys_schema_migration')===false,'probe is metadata-only with no ledger path');
$check(substr_count($sql,"CONSTRAINT_NAME='fk_auth_login_failure_user'")===10,'every metadata aggregate is restricted to the named constraint');
$check(strpos($sql,'BINARY REFERENCED_TABLE_SCHEMA<>BINARY DATABASE()')!==false&&strpos($sql,"REFERENCED_TABLE_NAME='auth_user'")!==false&&strpos($sql,"REFERENCED_COLUMN_NAME='id'")!==false,'cross-schema and exact target contract are independently checked');
$check(strpos($sql,"COLUMN_NAME='user_id'")!==false&&strpos($sql,"DELETE_RULE='SET NULL'")!==false&&strpos($sql,"UPDATE_RULE IN ('RESTRICT','NO ACTION')")!==false,'local column and referential actions are independently checked');

$tmp=sys_get_temp_dir().'/finance-a58-'.bin2hex(random_bytes(6));mkdir($tmp.'/bin',0700,true);register_shutdown_function(static function()use($tmp):void{if(is_dir($tmp))a58t_rm($tmp,$tmp);});
$option=$tmp.'/client.cnf';file_put_contents($option,"[client]\nuser=fixture\n");chmod($option,0600);$databaseName='a58_contract_db';$databaseNameFile=$tmp.'/database-name';file_put_contents($databaseNameFile,$databaseName."\n");chmod($databaseNameFile,0600);$capture=$tmp.'/capture.sql';$pidFile=$tmp.'/pid';$argvFile=$tmp.'/argv.json';
$fake=<<<'PHP'
#!/usr/bin/php
<?php
$mode=getenv('A58_MODE')?:'exact';$expectedDatabase=getenv('A58_EXPECTED_DATABASE');file_put_contents(getenv('A58_ARGV'),json_encode($argv,JSON_UNESCAPED_SLASHES));if(!is_string($expectedDatabase)||end($argv)!==$expectedDatabase){fwrite(STDERR,"RAW SECRET selected database missing\n");exit(12);}file_put_contents(getenv('A58_PID'),(string)getmypid());
while(($line=fgets(STDIN))!==false){file_put_contents(getenv('A58_CAPTURE'),$line,FILE_APPEND);if($mode==='timeout'){if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,SIG_IGN);}while(true)usleep(100000);}if($mode==='malformed'){fwrite(STDOUT,"RAW SECRET malformed\n");fflush(STDOUT);exit(8);}if($mode==='client_failure'){fwrite(STDERR,"RAW SECRET /secure/client.cnf\n");exit(9);}if(strpos($line,'__A58_NAMED_FK__')!==false){$v=[1,1,1,0,1,1,1,1,1,1];switch($mode){case'metadata_absent':$v=[0,0,0,0,0,0,0,0,0,0];break;case'permission_limited':$v=[1,1,1,0,1,1,0,0,0,0];break;case'hidden_rules_local':$v=[1,1,0,0,1,1,0,0,0,0];break;case'hidden_rules_cross':$v=[1,1,1,1,1,1,0,0,0,0];break;case'hidden_rules_table':$v=[1,1,1,0,0,1,0,0,0,0];break;case'hidden_rules_column':$v=[1,1,1,0,1,0,0,0,0,0];break;case'hidden_rules_multi':$v=[2,2,2,0,2,2,0,0,0,0];break;case'metadata_incomplete':$v[1]=0;break;case'local':$v[2]=0;break;case'cross':$v[3]=1;break;case'table':$v[4]=0;break;case'column':$v[5]=0;break;case'delete':$v[8]=0;break;case'update':$v[9]=0;break;case'multi':$v=[2,2,2,0,2,2,1,1,1,1];break;case'precedence_local':$v=[2,2,1,1,1,1,1,1,0,0];break;case'precedence_cross':$v[3]=1;$v[4]=0;$v[5]=0;$v[8]=0;break;case'precedence_table':$v[4]=0;$v[5]=0;$v[8]=0;$v[9]=0;break;case'precedence_column':$v[5]=0;$v[8]=0;$v[9]=0;break;case'precedence_delete':$v[8]=0;$v[9]=0;break;}fwrite(STDOUT,"__A58_NAMED_FK__\t".implode("\t",$v)."\n");fflush(STDOUT);}}
PHP;
file_put_contents($tmp.'/bin/mariadb',$fake);chmod($tmp.'/bin/mariadb',0700);
$env=['PATH'=>$tmp.'/bin','A58_CAPTURE'=>$capture,'A58_PID'=>$pidFile,'A58_ARGV'=>$argvFile,'A58_EXPECTED_DATABASE'=>$databaseName];$args=['probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile,'--permission-profile-acknowledgement=metadata-read'];
$validate=a58t_run([PHP_BINARY,$probe,'validate'],$root,$env);$validateJson=json_decode(trim($validate['out']),true);$check($validate['code']===0&&($validateJson['read_only']??false)===true&&($validateJson['permission_profile_acknowledgement_required']??'')==='metadata-read'&&!file_exists($capture),'validate is DB-free and declares the operator acknowledgement requirement');
$states=['exact'=>[],'permission_limited'=>['permission_visibility_limited'],'hidden_rules_local'=>['named_fk_local_column_mismatch'],'hidden_rules_cross'=>['named_fk_cross_schema'],'hidden_rules_table'=>['named_fk_target_table_mismatch'],'hidden_rules_column'=>['named_fk_target_column_mismatch'],'hidden_rules_multi'=>['named_fk_multicolumn_or_ambiguous'],'local'=>['named_fk_local_column_mismatch'],'cross'=>['named_fk_cross_schema'],'table'=>['named_fk_target_table_mismatch'],'column'=>['named_fk_target_column_mismatch'],'delete'=>['named_fk_delete_rule_mismatch'],'update'=>['named_fk_update_rule_mismatch'],'multi'=>['named_fk_multicolumn_or_ambiguous'],'metadata_absent'=>['named_fk_metadata_incomplete'],'metadata_incomplete'=>['named_fk_metadata_incomplete'],'precedence_local'=>['named_fk_local_column_mismatch'],'precedence_cross'=>['named_fk_cross_schema'],'precedence_table'=>['named_fk_target_table_mismatch'],'precedence_column'=>['named_fk_target_column_mismatch'],'precedence_delete'=>['named_fk_delete_rule_mismatch']];
foreach($states as$mode=>$expected){@unlink($capture);$result=a58t_run([PHP_BINARY,$probe,...$args],$root,$env+['A58_MODE'=>$mode]);$json=json_decode(trim($result['out']),true);$check($result['code']===0&&($json['reasons']??null)===$expected,$mode.' emits the exact fixed code under deterministic precedence');$sent=(string)@file_get_contents($capture);$lines=array_values(array_filter(preg_split('/\R/',$sent)?:[],static fn(string $line):bool=>trim($line)!==''));$terminated=count($lines)===1&&preg_match('/^SELECT\b.*;$/i',$lines[0])===1&&substr_count($lines[0],';')===1;$check($terminated&&a55_safe_select((string)preg_replace('/;\s*$/','',$lines[0]))&&strpos($sent,'sys_schema_migration')===false,'probe emits exactly one terminated safe metadata SELECT');$check(strpos($result['out'],'auth_login_failure')===false&&strpos($result['out'],'auth_user')===false&&strpos($result['out'],$option)===false,'successful output contains no object, credential path, or row detail');}
$clientArgv=json_decode((string)@file_get_contents($argvFile),true);$check(is_array($clientArgv)&&array_slice($clientArgv,-2)===['--unbuffered',$databaseName],'named FK client selects the database as the final argv argument');
foreach(['malformed'=>'malformed_output','client_failure'=>'client_failure']as$mode=>$code){$result=a58t_run([PHP_BINARY,$probe,...$args],$root,$env+['A58_MODE'=>$mode]);$check($result['code']!==0&&a58t_code($result)===$code&&strpos($result['err'],'RAW SECRET')===false&&strpos($result['err'],$option)===false,$mode.' fails closed with redacted diagnostics');}
@unlink($capture);@unlink($pidFile);$timeout=a58t_run([PHP_BINARY,$probe,...$args],$root,$env+['A58_MODE'=>'timeout','A5_MIGRATION_TIMEOUT_SECONDS'=>'1']);$pid=(int)@file_get_contents($pidFile);$alive=$pid>0&&function_exists('posix_kill')?@posix_kill($pid,0):false;$check($timeout['code']!==0&&a58t_code($timeout)==='client_timeout'&&!$alive&&strpos((string)@file_get_contents($capture),'sys_schema_migration')===false,'timeout terminates child with no ledger path');
$credential=a58t_run([PHP_BINARY,'-d','variables_order=GPCS',$probe,...$args],$root,$env+['DB_PASSWORD'=>'SECRET']);$check($credential['code']!==0&&a58t_code($credential)==='credential_env'&&strpos($credential['err'],'SECRET')===false,'credential environment is rejected without disclosure');
@unlink($capture);$profile=a58t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile],$root,$env);$check($profile['code']!==0&&a58t_code($profile)==='permission_profile_acknowledgement_invalid'&&!file_exists($capture),'missing permission-profile acknowledgement fails before client start');
$missingDatabase=a58t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--permission-profile-acknowledgement=metadata-read'],$root,$env);$check($missingDatabase['code']!==0&&a58t_code($missingDatabase)==='usage','missing database-name file argument fails closed');
$extra=a58t_run([PHP_BINARY,$probe,...$args,'--unexpected'],$root,$env);$check($extra['code']!==0&&a58t_code($extra)==='usage','extra named FK argument fails closed');
$cli=a58t_run([PHP_BINARY,$probe,...$args,'--password=SECRET'],$root,$env);$check($cli['code']!==0&&a58t_code($cli)==='credential_cli'&&strpos($cli['err'],'SECRET')===false,'credential CLI argument is rejected without disclosure');
a58t_rm($tmp,$tmp);$check(!file_exists($tmp),'named FK fixtures are cleaned');
if($failures!==[]){fwrite(STDERR,count($failures).' A5.8 named FK contract check(s) failed.'.PHP_EOL);exit(1);}echo 'All '.$checks.' A5.8 named FK contract checks passed.'.PHP_EOL;
