<?php

declare(strict_types=1);

$checks=0;$failures=[];
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok){$failures[]=$message;fwrite(STDERR,'FAIL: '.$message.PHP_EOL);return;}echo 'PASS: '.$message.PHP_EOL;};
function a56t_rm(string $root,string $path):void{if(strpos($path,$root)!==0)throw new RuntimeException('unsafe cleanup');if(is_link($path)||is_file($path)){@unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$entry)if($entry!=='.'&&$entry!=='..')a56t_rm($root,$path.'/'.$entry);@rmdir($path);}
function a56t_run(array $command,string $cwd,array $env):array{$p=proc_open($command,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$cwd,$env);if(!is_resource($p))return['code'=>255,'out'=>'','err'=>''];$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return['code'=>proc_close($p),'out'=>(string)$out,'err'=>(string)$err];}
function a56t_code(array $result):string{$json=json_decode(trim($result['err']),true);return is_array($json)?(string)($json['code']??''):'';}

$root=dirname(__DIR__,2);$probe=$root.'/tools/db/auth_login_failure_fk_probe.php';
define('A56_FK_PROBE_LIBRARY_ONLY',true);require $probe;
$structureSql=a56_structure_sql();$orphanSql=a56_orphan_sql();
$check(a55_safe_select($structureSql)&&a55_safe_select($orphanSql),'both forensic statements pass strict SELECT-only validation');
$check(strpos($structureSql,"ENGINE='InnoDB'")!==false&&strpos($structureSql,"f.DATA_TYPE='bigint'")!==false&&strpos($structureSql,"LOWER(u.COLUMN_TYPE)=LOWER(f.COLUMN_TYPE)")!==false&&strpos($structureSql,"SEQ_IN_INDEX=1")!==false,'structure SELECT checks tables, engines, exact compatible columns, and suitable indexes');
$check(strpos($structureSql,'fk_auth_login_failure_user')!==false&&strpos($structureSql,'k.REFERENCED_TABLE_SCHEMA=DATABASE()')!==false&&strpos($structureSql,"DELETE_RULE='SET NULL'")!==false&&strpos($structureSql,'REFERENCED_TABLE_NAME IS NOT NULL')!==false,'structure SELECT bounds named FK to current schema and distinguishes competing foreign keys');
$check(strpos($orphanSql,'COUNT(*)')!==false&&strpos($orphanSql,'f.user_id IS NOT NULL')!==false&&strpos($orphanSql,'u.id IS NULL')!==false&&strpos($orphanSql,'SELECT f.')===false,'orphan evidence is aggregate-only and exposes no row values');

$tmp=sys_get_temp_dir().'/finance-a56-'.bin2hex(random_bytes(6));mkdir($tmp.'/bin',0700,true);register_shutdown_function(static function()use($tmp):void{if(is_dir($tmp))a56t_rm($tmp,$tmp);});
$option=$tmp.'/client.cnf';file_put_contents($option,"[client]\nuser=fixture\n");chmod($option,0600);$databaseName='a56_contract_db';$databaseNameFile=$tmp.'/database-name';file_put_contents($databaseNameFile,$databaseName."\n");chmod($databaseNameFile,0600);$capture=$tmp.'/capture.sql';$pidFile=$tmp.'/pid';$countFile=$tmp.'/count';$argvFile=$tmp.'/argv.json';
$fake=<<<'PHP'
#!/usr/bin/php
<?php
$mode=getenv('A56_MODE')?:'clean';$capture=getenv('A56_CAPTURE');$expectedDatabase=getenv('A56_EXPECTED_DATABASE');file_put_contents(getenv('A56_ARGV'),json_encode($argv,JSON_UNESCAPED_SLASHES));if(!is_string($expectedDatabase)||end($argv)!==$expectedDatabase){fwrite(STDERR,"RAW SECRET selected database missing\n");exit(12);}file_put_contents(getenv('A56_PID'),(string)getmypid());file_put_contents(getenv('A56_COUNT'),(string)(((int)@file_get_contents(getenv('A56_COUNT')))+1));
while(($line=fgets(STDIN))!==false){file_put_contents($capture,$line,FILE_APPEND);if($mode==='timeout'){if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,SIG_IGN);}while(true)usleep(100000);}if($mode==='malformed'){fwrite(STDOUT,"RAW SECRET malformed\n");fflush(STDOUT);exit(8);}if($mode==='client_failure'){fwrite(STDERR,"RAW SECRET /secure/client.cnf\n");exit(9);}if(strpos($line,'__A56_STRUCTURE__')!==false){$marker=['clean'=>"1\t0\t0\t0\t0\t0",'orphan'=>"1\t0\t0\t0\t0\t0",'already'=>"1\t1\t1\t1\t1\t0",'permission_limited'=>"1\t0\t1\t1\t0\t0",'missing_table'=>"0\t0\t0\t0\t0\t0",'wrong_engine'=>"0\t0\t0\t0\t0\t0",'wrong_type'=>"0\t0\t0\t0\t0\t0",'missing_index'=>"0\t0\t0\t0\t0\t0",'competing_fk'=>"1\t0\t0\t0\t0\t1",'cross_schema_fk'=>"1\t0\t1\t0\t0\t0",'hidden_rules_wrong_structure'=>"0\t0\t1\t1\t0\t0",'hidden_rules_competing'=>"1\t0\t1\t1\t0\t1"][$mode]??"0\t0\t0\t0\t0\t0";fwrite(STDOUT,"__A56_STRUCTURE__\t{$marker}\n");fflush(STDOUT);}elseif(strpos($line,'__A56_ORPHANS__')!==false){fwrite(STDOUT,"__A56_ORPHANS__\t".($mode==='orphan'?'3':'0')."\n");fflush(STDOUT);}}
PHP;
file_put_contents($tmp.'/bin/mariadb',$fake);chmod($tmp.'/bin/mariadb',0700);
$env=['PATH'=>$tmp.'/bin','A56_CAPTURE'=>$capture,'A56_PID'=>$pidFile,'A56_COUNT'=>$countFile,'A56_ARGV'=>$argvFile,'A56_EXPECTED_DATABASE'=>$databaseName];$args=['probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile,'--permission-profile-acknowledgement=metadata-read'];
$validate=a56t_run([PHP_BINARY,$probe,'validate'],$root,$env);$check($validate['code']===0&&strpos($validate['out'],'"read_only":true')!==false&&strpos($validate['out'],'"permission_profile_acknowledgement_required":"metadata-read"')!==false,'validate mode is DB-free and declares the operator acknowledgement requirement');

$states=['clean'=>'missing_fk_clean','orphan'=>'missing_fk_orphan','already'=>'already_present','permission_limited'=>'permission_visibility_limited','missing_table'=>'structural_incompatible','wrong_engine'=>'structural_incompatible','wrong_type'=>'structural_incompatible','missing_index'=>'structural_incompatible','competing_fk'=>'structural_incompatible','cross_schema_fk'=>'structural_incompatible','hidden_rules_wrong_structure'=>'structural_incompatible','hidden_rules_competing'=>'structural_incompatible'];
foreach($states as$mode=>$expected){@unlink($capture);@unlink($countFile);$result=a56t_run([PHP_BINARY,$probe,...$args],$root,$env+['A56_MODE'=>$mode]);$json=json_decode(trim($result['out']),true);$countExpected=$mode==='clean'?0:($mode==='orphan'?3:null);$countOk=$countExpected===null?!array_key_exists('orphan_count',$json):(($json['orphan_count']??-1)===$countExpected);$check($result['code']===0&&($json['state']??'')===$expected&&$countOk,$mode.' maps to the exact redacted forensic state');$sent=(string)@file_get_contents($capture);$lines=array_values(array_filter(preg_split('/\R/',$sent)?:[],static function(string $line):bool{return trim($line)!=='';}));$check(trim((string)@file_get_contents($countFile))==='1'&&$lines!==[]&&count(array_filter($lines,static function(string $line):bool{return preg_match('/^SELECT\b.*;$/i',$line)===1&&substr_count($line,';')===1;}))===count($lines),'state uses one client and terminated SELECT-only statements');$safeLines=array_filter($lines,static function(string $line):bool{return a55_safe_select((string)preg_replace('/;\s*$/','',$line));});$check(strpos($sent,'sys_schema_migration')===false&&count($safeLines)===count($lines),'state has no ledger or mutation path');}
$clientArgv=json_decode((string)@file_get_contents($argvFile),true);$check(is_array($clientArgv)&&array_slice($clientArgv,-2)===['--unbuffered',$databaseName],'FK forensic client selects the database as the final argv argument');

foreach(['malformed'=>'malformed_output','client_failure'=>'client_failure']as$mode=>$code){@unlink($capture);$result=a56t_run([PHP_BINARY,$probe,...$args],$root,$env+['A56_MODE'=>$mode]);$check($result['code']!==0&&a56t_code($result)===$code&&strpos($result['err'],'RAW SECRET')===false&&strpos($result['err'],$option)===false,$mode.' fails closed with redacted diagnostics');}
@unlink($capture);@unlink($pidFile);$timeout=a56t_run([PHP_BINARY,$probe,...$args],$root,$env+['A56_MODE'=>'timeout','A5_MIGRATION_TIMEOUT_SECONDS'=>'1']);$pid=(int)@file_get_contents($pidFile);$alive=$pid>0&&function_exists('posix_kill')?@posix_kill($pid,0):false;$check($timeout['code']!==0&&a56t_code($timeout)==='client_timeout'&&!$alive&&strpos((string)@file_get_contents($capture),'sys_schema_migration')===false,'timeout kills child without ledger mutation');
$credential=a56t_run([PHP_BINARY,'-d','variables_order=GPCS',$probe,...$args],$root,$env+['DB_PASSWORD'=>'SECRET']);$check($credential['code']!==0&&a56t_code($credential)==='credential_env'&&strpos($credential['err'],'SECRET')===false,'credential environment fails closed without disclosure');
@unlink($capture);$profile=a56t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile],$root,$env);$check($profile['code']!==0&&a56t_code($profile)==='permission_profile_acknowledgement_invalid'&&!file_exists($capture),'missing permission-profile acknowledgement fails before client start');
$missingDatabase=a56t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--permission-profile-acknowledgement=metadata-read'],$root,$env);$check($missingDatabase['code']!==0&&a56t_code($missingDatabase)==='usage','missing database-name file argument fails closed');
$extra=a56t_run([PHP_BINARY,$probe,...$args,'--unexpected'],$root,$env);$check($extra['code']!==0&&a56t_code($extra)==='usage','extra FK forensic argument fails closed');
$cli=a56t_run([PHP_BINARY,$probe,...$args,'--password=SECRET'],$root,$env);$check($cli['code']!==0&&a56t_code($cli)==='credential_cli'&&strpos($cli['err'],'SECRET')===false,'credential CLI argument fails closed without disclosure');
a56t_rm($tmp,$tmp);$check(!file_exists($tmp),'forensic fixtures are cleaned');
if($failures!==[]){fwrite(STDERR,count($failures).' A5.6 FK forensic check(s) failed.'.PHP_EOL);exit(1);}echo 'All '.$checks.' A5.6 auth login failure FK forensic checks passed.'.PHP_EOL;
