<?php

declare(strict_types=1);

$checks=0;$failures=[];
$check=static function(bool $ok,string $message)use(&$checks,&$failures):void{$checks++;if(!$ok){$failures[]=$message;fwrite(STDERR,'FAIL: '.$message.PHP_EOL);return;}echo 'PASS: '.$message.PHP_EOL;};
function a57t_rm(string $root,string $path):void{if(strpos($path,$root)!==0)throw new RuntimeException('unsafe cleanup');if(is_link($path)||is_file($path)){@unlink($path);return;}if(!is_dir($path))return;foreach(scandir($path)?:[]as$entry)if($entry!=='.'&&$entry!=='..')a57t_rm($root,$path.'/'.$entry);@rmdir($path);}
function a57t_run(array $command,string $cwd,array $env):array{$p=proc_open($command,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$cwd,$env);if(!is_resource($p))return['code'=>255,'out'=>'','err'=>''];$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);return['code'=>proc_close($p),'out'=>(string)$out,'err'=>(string)$err];}
function a57t_code(array $result):string{$json=json_decode(trim($result['err']),true);return is_array($json)?(string)($json['code']??''):'';}

$root=dirname(__DIR__,2);$probe=$root.'/tools/db/auth_login_failure_fk_detail_probe.php';
define('A57_FK_DETAIL_LIBRARY_ONLY',true);require $probe;
$sql=a57_detail_sql();
$check(a55_safe_select($sql)&&substr_count($sql,';')===0,'detail statement passes strict SELECT-only validation and has no embedded terminator');
$check(substr_count($sql,'information_schema.')>=9&&strpos($sql,'sys_schema_migration')===false&&!preg_match('/\b(?:INSERT\s+INTO|UPDATE\s+auth_|DELETE\s+FROM|ALTER\s+TABLE|CREATE\s+TABLE|DROP\s+TABLE|SET\s+@|GET_LOCK\s*\()/i',$sql),'probe reads only information_schema and has no ledger or mutation path');
$check(strpos($sql,"ENGINE='InnoDB'")!==false&&strpos($sql,"f.DATA_TYPE='bigint'")!==false&&strpos($sql,"f.COLUMN_TYPE LIKE '%unsigned'")!==false&&strpos($sql,"f.IS_NULLABLE='YES'")!==false&&strpos($sql,"u.IS_NULLABLE='NO'")!==false,'engine and user_id type, sign, and nullability evidence is exact');
$check(strpos($sql,'GROUP BY INDEX_NAME HAVING COUNT(*)=1')!==false&&strpos($sql,'SEQ_IN_INDEX=1')!==false,'target uniqueness and source leading index evidence are checked');
$check(strpos($sql,"CONSTRAINT_NAME='fk_auth_login_failure_user'")!==false&&strpos($sql,'k.REFERENCED_TABLE_SCHEMA=DATABASE()')!==false&&strpos($sql,"DELETE_RULE='SET NULL'")!==false&&strpos($sql,"UPDATE_RULE IN ('RESTRICT','NO ACTION')")!==false,'named FK contract is scoped to the current schema and exact actions');
$check(strpos($sql,"COLUMN_NAME='user_id' AND REFERENCED_TABLE_NAME IS NOT NULL")!==false,'competing user_id foreign keys are counted');

$tmp=sys_get_temp_dir().'/finance-a57-'.bin2hex(random_bytes(6));mkdir($tmp.'/bin',0700,true);register_shutdown_function(static function()use($tmp):void{if(is_dir($tmp))a57t_rm($tmp,$tmp);});
$option=$tmp.'/client.cnf';file_put_contents($option,"[client]\nuser=fixture\n");chmod($option,0600);$databaseName='a57_contract_db';$databaseNameFile=$tmp.'/database-name';file_put_contents($databaseNameFile,$databaseName."\n");chmod($databaseNameFile,0600);$capture=$tmp.'/capture.sql';$pidFile=$tmp.'/pid';$argvFile=$tmp.'/argv.json';
$fake=<<<'PHP'
#!/usr/bin/php
<?php
$mode=getenv('A57_MODE')?:'compatible';$expectedDatabase=getenv('A57_EXPECTED_DATABASE');file_put_contents(getenv('A57_ARGV'),json_encode($argv,JSON_UNESCAPED_SLASHES));if(!is_string($expectedDatabase)||end($argv)!==$expectedDatabase){fwrite(STDERR,"RAW SECRET selected database missing\n");exit(12);}file_put_contents(getenv('A57_PID'),(string)getmypid());
while(($line=fgets(STDIN))!==false){file_put_contents(getenv('A57_CAPTURE'),$line,FILE_APPEND);if($mode==='timeout'){if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,SIG_IGN);}while(true)usleep(100000);}if($mode==='malformed'){fwrite(STDOUT,"RAW SECRET malformed\n");fflush(STDOUT);exit(8);}if($mode==='client_failure'){fwrite(STDERR,"RAW SECRET /secure/client.cnf\n");exit(9);}if(strpos($line,'__A57_DETAIL__')!==false){$v=[1,1,1,1,1,1,1,1,1,0,0,0,0,0];switch($mode){case'metadata_incomplete':$v[0]=0;break;case'source_not_innodb':$v[1]=0;break;case'target_not_innodb':$v[3]=0;break;case'user_id_type_mismatch':$v[6]=0;break;case'target_id_not_unique':$v[7]=0;break;case'source_index_missing':$v[8]=0;break;case'named_fk_wrong_contract':$v[10]=1;$v[11]=0;$v[12]=1;break;case'permission_limited':$v[10]=1;$v[11]=1;break;case'competing_fk':$v[13]=1;break;case'already_present':$v[9]=1;$v[10]=1;$v[11]=1;$v[12]=1;break;case'hidden_rules_wrong_kcu':$v[10]=1;$v[11]=0;break;case'hidden_rules_missing_index':$v[8]=0;$v[10]=1;$v[11]=1;break;case'hidden_rules_competing':$v[10]=1;$v[11]=1;$v[13]=1;break;case'precedence_metadata':$v=[0,0,0,0,0,0,0,0,0,2,2,0,0,2];break;case'precedence_engine':$v[1]=0;$v[3]=0;$v[6]=0;break;}fwrite(STDOUT,"__A57_DETAIL__\t".implode("\t",$v)."\n");fflush(STDOUT);}}
PHP;
file_put_contents($tmp.'/bin/mariadb',$fake);chmod($tmp.'/bin/mariadb',0700);
$env=['PATH'=>$tmp.'/bin','A57_CAPTURE'=>$capture,'A57_PID'=>$pidFile,'A57_ARGV'=>$argvFile,'A57_EXPECTED_DATABASE'=>$databaseName];$args=['probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile,'--permission-profile-acknowledgement=metadata-read'];
$validate=a57t_run([PHP_BINARY,$probe,'validate'],$root,$env);$validateJson=json_decode(trim($validate['out']),true);$check($validate['code']===0&&($validateJson['read_only']??false)===true&&($validateJson['permission_profile_acknowledgement_required']??'')==='metadata-read'&&!file_exists($capture),'validate is DB-free and declares the operator acknowledgement requirement');

$states=['compatible'=>[],'already_present'=>[],'permission_limited'=>['permission_visibility_limited'],'metadata_incomplete'=>['metadata_incomplete'],'source_not_innodb'=>['source_not_innodb'],'target_not_innodb'=>['target_not_innodb'],'user_id_type_mismatch'=>['user_id_type_mismatch'],'target_id_not_unique'=>['target_id_not_unique'],'source_index_missing'=>['source_index_missing'],'named_fk_wrong_contract'=>['named_fk_wrong_contract'],'competing_fk'=>['competing_fk'],'hidden_rules_wrong_kcu'=>['named_fk_wrong_contract'],'hidden_rules_missing_index'=>['source_index_missing'],'hidden_rules_competing'=>['competing_fk'],'precedence_metadata'=>['metadata_incomplete'],'precedence_engine'=>['source_not_innodb']];
foreach($states as$mode=>$expected){@unlink($capture);$result=a57t_run([PHP_BINARY,$probe,...$args],$root,$env+['A57_MODE'=>$mode]);$json=json_decode(trim($result['out']),true);$check($result['code']===0&&($json['reasons']??null)===$expected,$mode.' emits only the expected fixed reason code by precedence');$sent=(string)@file_get_contents($capture);$lines=array_values(array_filter(preg_split('/\R/',$sent)?:[],static fn(string $line):bool=>trim($line)!==''));$terminated=count($lines)===1&&preg_match('/^SELECT\b.*;$/i',$lines[0])===1&&substr_count($lines[0],';')===1;$safe=$terminated&&a55_safe_select((string)preg_replace('/;\s*$/','',$lines[0]));$check($safe&&strpos($sent,'sys_schema_migration')===false,'fixture receives exactly one terminated safe metadata SELECT and no ledger statement');$check(strpos($result['out'],'auth_login_failure')===false&&strpos($result['out'],'auth_user')===false&&strpos($result['out'],$option)===false,'successful output is deterministic and redacted');}
$clientArgv=json_decode((string)@file_get_contents($argvFile),true);$check(is_array($clientArgv)&&array_slice($clientArgv,-2)===['--unbuffered',$databaseName],'FK detail client selects the database as the final argv argument');

foreach(['malformed'=>'malformed_output','client_failure'=>'client_failure']as$mode=>$code){@unlink($capture);$result=a57t_run([PHP_BINARY,$probe,...$args],$root,$env+['A57_MODE'=>$mode]);$check($result['code']!==0&&a57t_code($result)===$code&&strpos($result['err'],'RAW SECRET')===false&&strpos($result['err'],$option)===false,$mode.' fails closed with redacted diagnostics');}
@unlink($capture);@unlink($pidFile);$timeout=a57t_run([PHP_BINARY,$probe,...$args],$root,$env+['A57_MODE'=>'timeout','A5_MIGRATION_TIMEOUT_SECONDS'=>'1']);$pid=(int)@file_get_contents($pidFile);$alive=$pid>0&&function_exists('posix_kill')?@posix_kill($pid,0):false;$check($timeout['code']!==0&&a57t_code($timeout)==='client_timeout'&&!$alive&&strpos((string)@file_get_contents($capture),'sys_schema_migration')===false,'timeout kills the fake client without a ledger path');
$credential=a57t_run([PHP_BINARY,'-d','variables_order=GPCS',$probe,...$args],$root,$env+['DB_PASSWORD'=>'SECRET']);$check($credential['code']!==0&&a57t_code($credential)==='credential_env'&&strpos($credential['err'],'SECRET')===false,'credential environment is rejected without disclosure');
@unlink($capture);$profile=a57t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--database-name-file='.$databaseNameFile],$root,$env);$check($profile['code']!==0&&a57t_code($profile)==='permission_profile_acknowledgement_invalid'&&!file_exists($capture),'missing permission-profile acknowledgement fails before client start');
$missingDatabase=a57t_run([PHP_BINARY,$probe,'probe','--defaults-extra-file='.$option,'--permission-profile-acknowledgement=metadata-read'],$root,$env);$check($missingDatabase['code']!==0&&a57t_code($missingDatabase)==='usage','missing database-name file argument fails closed');
$extra=a57t_run([PHP_BINARY,$probe,...$args,'--unexpected'],$root,$env);$check($extra['code']!==0&&a57t_code($extra)==='usage','extra FK detail argument fails closed');
$cli=a57t_run([PHP_BINARY,$probe,...$args,'--password=SECRET'],$root,$env);$check($cli['code']!==0&&a57t_code($cli)==='credential_cli'&&strpos($cli['err'],'SECRET')===false,'credential CLI argument is rejected without disclosure');
a57t_rm($tmp,$tmp);$check(!file_exists($tmp),'detail probe fixtures are cleaned');
if($failures!==[]){fwrite(STDERR,count($failures).' A5.7 FK detail check(s) failed.'.PHP_EOL);exit(1);}echo 'All '.$checks.' A5.7 auth login failure FK detail checks passed.'.PHP_EOL;
