<?php
declare(strict_types=1);
$checks=0;$fails=[];$check=static function(bool $ok,string $m)use(&$checks,&$fails):void{$checks++;if(!$ok){$fails[]=$m;fwrite(STDERR,"FAIL: $m\n");}else echo"PASS: $m\n";};
function a510trm(string $r,string $p):void{if(strpos($p,$r)!==0)throw new RuntimeException('cleanup');if(is_link($p)||is_file($p)){@unlink($p);return;}if(!is_dir($p))return;foreach(scandir($p)?:[]as$e)if($e!=='.'&&$e!=='..')a510trm($r,$p.'/'.$e);@rmdir($p);}
function a510trun(array $c,string $w,array $e=[]):array{$p=proc_open($c,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$x,$w,$e?:null);$o=stream_get_contents($x[1]);$q=stream_get_contents($x[2]);fclose($x[1]);fclose($x[2]);return['code'=>proc_close($p),'out'=>(string)$o,'err'=>(string)$q];}
function a510tcode(array $r):string{$j=json_decode(trim($r['err']),true);return is_array($j)?(string)($j['code']??''):'';}
function a510tcopy(string $a,string $b):void{mkdir($b,0700);foreach(scandir($a)?:[]as$e)if($e!=='.'&&$e!=='..')copy("$a/$e","$b/$e");}
$root=dirname(__DIR__,2);$builder="$root/tools/db/backup_bundle_manifest.php";$preflight="$root/tools/db/restore_preflight.php";$tmp=sys_get_temp_dir().'/a510-'.bin2hex(random_bytes(5));mkdir($tmp,0700);register_shutdown_function(static fn()=>is_dir($tmp)?a510trm($tmp,$tmp):null);
$src="$tmp/fixture.sql.gz";file_put_contents($src,gzencode("-- fixture\nSELECT 1;\n",9));chmod($src,0600);
$build=static fn(string $out):array=>a510trun([PHP_BINARY,$builder,'build','--source-archive='.$src,'--output-bundle='.$out,'--source-epoch=1700000000','--schema-digest=null','--ledger-digest='.str_repeat('a',64)],$root,['PATH'=>'/untrusted']);
$one="$tmp/one";$two="$tmp/two";$r1=$build($one);$r2=$build($two);$check($r1['code']===0&&$r2['code']===0,'atomic CLI build succeeds without inherited PATH');
$m1=file_get_contents("$one/backup_bundle_manifest.json");$m2=file_get_contents("$two/backup_bundle_manifest.json");$check($m1===$m2&&file_get_contents("$one/fixture.sql.gz")===file_get_contents("$two/fixture.sql.gz"),'built bundles are deterministic');
$check((fileperms($one)&0777)===0700&&(fileperms("$one/fixture.sql.gz")&0777)===0600&&(fileperms("$one/backup_bundle_manifest.json")&0777)===0600,'bundle and artifact permissions are private');
$m=json_decode((string)$m1,true);$check(($m['source']['created_utc']??'')==='2023-11-14T22:13:20Z'&&array_key_exists('schema_digest',$m)&&$m['schema_digest']===null&&($m['artifact']['sha256']??'')===hash_file('sha256',$src),'manifest preserves deterministic metadata and exact source digest');
$plan=a510trun([PHP_BINARY,$preflight,'plan','--bundle-dir='.$one],$root,['PATH'=>'/untrusted']);$pj=json_decode(trim($plan['out']),true);$check($plan['code']===0&&in_array('reverify_bundle_immediately_before_consume',$pj['plan']??[],true)&&($pj['database_action']??'')==='none','preflight plans immediate consumer reverify and no DB action');
$before=hash_file('sha256',"$one/backup_bundle_manifest.json");$exists=$build($one);$check($exists['code']!==0&&a510tcode($exists)==='output_exists'&&hash_file('sha256',"$one/backup_bundle_manifest.json")===$before,'existing output is never replaced');
$openParent="$tmp/open-parent";mkdir($openParent,0700);chmod($openParent,0770);$open=a510trun([PHP_BINARY,$builder,'build','--source-archive='.$src,'--output-bundle='.$openParent.'/bundle','--source-epoch=1700000000'],$root);$check($open['code']!==0&&a510tcode($open)==='unsafe_output_parent'&&!file_exists($openParent.'/bundle'),'group-writable output parent is rejected before staging');chmod($openParent,0700);
$race="$tmp/race";$raceCommand=[PHP_BINARY,$builder,'build','--source-archive='.$src,'--output-bundle='.$race,'--source-epoch=1700000000'];$procs=[];foreach([1,2]as$_){$p=proc_open($raceCommand,[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,['PATH'=>'/untrusted']);$procs[]=[$p,$pipes];}$raceResults=[];foreach($procs as[$p,$pipes]){$out=stream_get_contents($pipes[1]);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$raceResults[]=['code'=>proc_close($p),'out'=>$out,'err'=>$err];}$success=count(array_filter($raceResults,static fn(array $r):bool=>$r['code']===0));$existsCodes=count(array_filter($raceResults,static fn(array $r):bool=>a510tcode($r)==='output_exists'));$check($success===1&&$existsCodes===1&&is_file($race.'/backup_bundle_manifest.json'),'parent flock serializes cooperating builders and never replaces race winner');
$bad="$tmp/bad.sql.gz";file_put_contents($bad,'bad');$badOut="$tmp/bad-out";$r=a510trun([PHP_BINARY,$builder,'build','--source-archive='.$bad,'--output-bundle='.$badOut,'--source-epoch=1700000000'],$root);$check($r['code']!==0&&a510tcode($r)==='gzip_invalid'&&!file_exists($badOut)&&(glob($tmp.'/.bad-out.stage-*')?:[])===[],'failed build removes stage and publishes no partial bundle');
$link="$tmp/link.sql.gz";symlink($src,$link);$r=a510trun([PHP_BINARY,$builder,'build','--source-archive='.$link,'--output-bundle='.$tmp.'/linked','--source-epoch=1'],$root);$check($r['code']!==0&&a510tcode($r)==='unsafe_source_archive','source symlink is rejected');
$case="$tmp/tamper";a510tcopy($one,$case);file_put_contents("$case/fixture.sql.gz",'x',FILE_APPEND);$r=a510trun([PHP_BINARY,$preflight,'verify','--bundle-dir='.$case],$root);$check($r['code']!==0&&a510tcode($r)==='artifact_mismatch','tamper fails closed');
$case="$tmp/traversal";a510tcopy($one,$case);$badManifest=$m;$badManifest['artifact']['path']='../x.sql.gz';file_put_contents("$case/backup_bundle_manifest.json",json_encode($badManifest,JSON_UNESCAPED_SLASHES).PHP_EOL);$r=a510trun([PHP_BINARY,$preflight,'verify','--bundle-dir='.$case],$root);$check($r['code']!==0&&a510tcode($r)==='unsafe_artifact','traversal fails closed');
$fake="$tmp/fake";mkdir($fake,0700);$mark="$tmp/path-used";file_put_contents("$fake/gzip","#!/usr/bin/php\n<?php file_put_contents('".addslashes($mark)."','x');\n");chmod("$fake/gzip",0700);$r=a510trun([PHP_BINARY,$preflight,'verify','--bundle-dir='.$one],$root,['PATH'=>$fake]);$check($r['code']===0&&!file_exists($mark),'normal CLI ignores PATH gzip substitution');
define('A510_RESTORE_PREFLIGHT_LIBRARY_ONLY',true);require $preflight;$sym="$fake/sym";symlink("$fake/gzip",$sym);$rejected=false;try{a510_test_set_gzip_binary($sym);}catch(A510BundleFailure $e){$rejected=$e->failureCode==='gzip_untrusted';}$check($rejected,'test hook rejects unsafe binary');
$hookOut="$tmp/hook-output";a510_test_set_build_failure('stage_mode');$hookCode='';try{a510_atomic_build(['source_archive'=>$src,'output_bundle'=>$hookOut,'source_epoch'=>'1700000000','schema_digest'=>null,'ledger_digest'=>null]);}catch(A510BundleFailure $e){$hookCode=$e->failureCode;}a510_test_set_build_failure(null);$check($hookCode==='stage_mode_failed'&&!file_exists($hookOut)&&(glob($tmp.'/.hook-output.stage-*')?:[])===[],'stage mode failure inside try/finally leaves no stage or output');
$syncFail="$fake/sync-fail";file_put_contents($syncFail,"#!/usr/bin/php\n<?php fwrite(STDERR,'SYNC SECRET');exit(9);\n");chmod($syncFail,0700);$syncFailOut="$tmp/sync-fail-output";a510_test_set_sync_binary($syncFail);a510_test_set_build_failure('cleanup_observe_failure');$syncError=null;try{a510_atomic_build(['source_archive'=>$src,'output_bundle'=>$syncFailOut,'source_epoch'=>'1700000000','schema_digest'=>null,'ledger_digest'=>null]);}catch(A510BundleFailure $e){$syncError=$e;}a510_test_set_build_failure(null);a510_test_set_sync_binary(null);$check($syncError instanceof A510BundleFailure&&$syncError->failureCode==='publish_sync_failed'&&strpos($syncError->getMessage(),'target_failed,lock_ok')!==false&&strpos($syncError->getMessage(),'SECRET')===false&&!file_exists($syncFailOut)&&(glob($tmp.'/.sync-fail-output.stage-*')?:[])===[],'sync failure removes final/stage and retains primary code with deterministic cleanup outcome');
$syncPid="$tmp/sync.pid";$syncHang="$fake/sync-hang";file_put_contents($syncHang,"#!/usr/bin/php\n<?php file_put_contents('".addslashes($syncPid)."',(string)getmypid());if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,SIG_IGN);}while(true)usleep(100000);\n");chmod($syncHang,0700);$syncTimeoutOut="$tmp/sync-timeout-output";putenv('A5_BACKUP_PREFLIGHT_TIMEOUT_SECONDS=1');a510_test_set_sync_binary($syncHang);$syncTimeoutCode='';try{a510_atomic_build(['source_archive'=>$src,'output_bundle'=>$syncTimeoutOut,'source_epoch'=>'1700000000','schema_digest'=>null,'ledger_digest'=>null]);}catch(A510BundleFailure $e){$syncTimeoutCode=$e->failureCode;}a510_test_set_sync_binary(null);putenv('A5_BACKUP_PREFLIGHT_TIMEOUT_SECONDS');$syncPidValue=(int)@file_get_contents($syncPid);$syncAlive=$syncPidValue>0&&function_exists('posix_kill')?@posix_kill($syncPidValue,0):false;$check($syncTimeoutCode==='publish_sync_timeout'&&!$syncAlive&&!file_exists($syncTimeoutOut)&&(glob($tmp.'/.sync-timeout-output.stage-*')?:[])===[],'sync timeout kills child and removes published final/stage while retaining timeout cause');
$pidFile="$tmp/pid";$hang="$fake/hang";file_put_contents($hang,"#!/usr/bin/php\n<?php file_put_contents('".addslashes($pidFile)."',(string)getmypid());if(function_exists('pcntl_async_signals')){pcntl_async_signals(true);pcntl_signal(SIGTERM,SIG_IGN);}while(true)usleep(100000);\n");chmod($hang,0700);putenv('A5_BACKUP_PREFLIGHT_TIMEOUT_SECONDS=1');a510_test_set_gzip_binary($hang);$code='';try{a510_load_bundle($one);}catch(A510BundleFailure $e){$code=$e->failureCode;}a510_test_set_gzip_binary(null);putenv('A5_BACKUP_PREFLIGHT_TIMEOUT_SECONDS');$pid=(int)@file_get_contents($pidFile);$alive=$pid>0&&function_exists('posix_kill')?@posix_kill($pid,0):false;$check($code==='gzip_timeout'&&!$alive,'test-only timeout kills verifier child');
$fail="$fake/fail";file_put_contents($fail,"#!/usr/bin/php\n<?php fwrite(STDOUT,'DUMP SECRET');fwrite(STDERR,'PATH SECRET');exit(9);\n");chmod($fail,0700);a510_test_set_gzip_binary($fail);$error=null;try{a510_load_bundle($one);}catch(A510BundleFailure $e){$error=$e;}a510_test_set_gzip_binary(null);$check($error instanceof A510BundleFailure&&$error->failureCode==='gzip_invalid'&&strpos($error->getMessage(),'SECRET')===false,'test-only failure is redacted');
$bs=file_get_contents($builder);$ps=file_get_contents($preflight);$check(strpos((string)$bs,'fstat(')!==false&&strpos((string)$bs,'lstat(')!==false&&strpos((string)$bs,"hash_init('sha256')")!==false&&strpos((string)$bs,'rename($stage,$final)')!==false,'source identity, copied digest, and atomic rename are explicit');$check(substr_count((string)$bs,'!chmod(')>=4&&substr_count((string)$bs,'!fflush(')>=2&&substr_count((string)$bs,'!fsync(')>=2&&strpos((string)$bs,"function_exists('fsync')")!==false,'chmod, flush, fsync, and fsync availability are checked fail-closed');$check(strpos((string)$bs,'$cleanupTarget=$final')!==false&&strpos((string)$bs,'$primaryFailure->failureCode')!==false,'published final remains the cleanup target and primary failure code is preserved');$check(strpos((string)$ps,"\$path='/usr/bin/gzip'")!==false&&strpos((string)$ps,"getenv('PATH')")===false&&strpos((string)$ps,"\$path='/usr/bin/sync'")!==false,'gzip and publish sync use fixed absolute host-approved binaries');
a510trm($tmp,$tmp);$check(!file_exists($tmp),'fixtures cleaned');if($fails){fwrite(STDERR,count($fails)." A5.10 remedial failures.\n");exit(1);}echo"All $checks A5.10 atomic bundle checks passed.\n";
