<?php
declare(strict_types=1);
// Real HTTPS/download contract against an explicit disposable Control database only.
require dirname(__DIR__).'/install/ControlDelivery.php';
umask(0077);$s=$argv[1]??'';$manifestPath=$argv[2]??'';$resultPath=$argv[3]??'';
if(PHP_SAPI!=='cli'||posix_geteuid()!==0||preg_match('~\A/var/lib/finance-control-[0-9]{8}[.][A-Za-z0-9]{6}\z~D',$s)!==1||realpath($s)!==$s)throw new RuntimeException('EXPLICIT_CONTROL_FIXTURE_REQUIRED');
$f=PrivateDeployment::read($s.'/fixture.json');if(preg_match('/\Afinance_ctl_test_[a-f0-9]{12}\z/D',$f['database'])!==1||$f['user']!==$f['database']||$f['base_url']!=='https://127.0.0.1:18444/')throw new RuntimeException('DISPOSABLE_DATABASE_ONLY');
$db=new PDO('mysql:host=127.0.0.1;dbname='.$f['database'].';charset=utf8mb4',$f['user'],$f['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION]);
$job=$s.'/delivery-'.bin2hex(random_bytes(6));mkdir($job,0700);$gid=posix_getpwnam('finance_c3_trial')['gid'];
$m=json_decode((string)file_get_contents($manifestPath),true,64,JSON_THROW_ON_ERROR);$releasePublic=PrivateDeployment::uuid();
$db->prepare("INSERT INTO releases(public_id,product_id,version,build_number,channel,source_commit,source_manifest_sha256,release_manifest_sha256,application_artifact_sha256,signing_key_id,signature_verified_at,status,release_notes,created_by) VALUES (?,?,?,?,'ALPHA',?,?,?,?,?,NOW(),'PUBLISHED','Disposable signed Finance package test',?)")->execute([$releasePublic,$f['product_id'],$m['version'],'practice-'.bin2hex(random_bytes(4)),$m['source_commit'],$m['source_manifest_sha256'],hash_file('sha256',$manifestPath),$m['sha256'],$m['key_id']??json_decode((string)file_get_contents(substr($manifestPath,0,-13).'.release.sig.json'),true)['key_id'],$f['owner_id']]);$release=(int)$db->lastInsertId();
$storage=$s.'/artifacts';if(!is_dir($storage)){mkdir($storage,0770);chgrp($storage,$gid);chmod($storage,0770);}mkdir($storage.'/'.$releasePublic,0750);chgrp($storage.'/'.$releasePublic,$gid);chmod($storage.'/'.$releasePublic,0750);
$q=$db->prepare('INSERT INTO release_artifacts(public_id,release_id,artifact_type,original_filename,storage_key,media_type,size_bytes,sha256,uploaded_by) VALUES (?,?,?,?,?,?,?,?,?)');
foreach(['MANIFEST'=>$manifestPath,'OTHER'=>substr($manifestPath,0,-13).'.release.sig.json','APPLICATION_PACKAGE'=>dirname($manifestPath).'/'.$m['artifact']]as$type=>$path){$id=PrivateDeployment::uuid();$relative=$releasePublic.'/'.$id.($type==='APPLICATION_PACKAGE'?'.tar':'.json');copy($path,$storage.'/'.$relative);chgrp($storage.'/'.$relative,$gid);chmod($storage.'/'.$relative,0640);$q->execute([$id,$release,$type,basename($path),$relative,'application/octet-stream',filesize($path),hash_file('sha256',$path),$f['owner_id']]);}
$deploymentPublic=PrivateDeployment::uuid();$db->prepare("INSERT INTO deployments(public_id,instance_id,release_id,status,requested_by,approved_by,started_at,action,plan_sha256,preflight_json) VALUES (?,?,?,'RUNNING',?,?,NOW(),'DEPLOY',?,'{}')")->execute([$deploymentPublic,$f['recovery']['record_id'],$release,$f['reviewer_id'],$f['owner_id'],hash('sha256',$releasePublic)]);$deployment=(int)$db->lastInsertId();
$token='ndi_'.rtrim(strtr(base64_encode(random_bytes(36)),'+/','-_'),'=');$db->prepare('INSERT INTO deployment_install_tokens(public_id,deployment_id,token_hash,expires_at,created_by) VALUES (?,?,?,DATE_ADD(NOW(),INTERVAL 1 HOUR),?)')->execute([PrivateDeployment::uuid(),$deployment,hash('sha256',$token),$f['owner_id']]);
$secret=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$nonce=random_bytes(SODIUM_CRYPTO_SECRETBOX_NONCEBYTES);$keyId=PrivateDeployment::uuid();
$db->prepare("INSERT INTO instance_keys(instance_id,key_id,secret_ciphertext,secret_nonce,secret_fingerprint,status,created_by) VALUES (?,?,?,?,?,'ACTIVE',?)")->execute([$f['recovery']['record_id'],$keyId,base64_encode(sodium_crypto_secretbox($secret,$nonce,hash('sha256',$f['application_key'],true))),base64_encode($nonce),substr(hash('sha256',$secret),0,16),$f['owner_id']]);
$config=['control_origin'=>rtrim($f['base_url'],'/'),'install_token'=>$token,'instance_id'=>$f['recovery']['instance_id'],'primary_domain'=>$f['recovery']['instance_id'].'.example.invalid','ca_file'=>$s.'/tls.crt'];
$identity=['instance_id'=>$config['instance_id'],'environment'=>'DEMO','key_id'=>$keyId,'secret'=>$secret];
PrivateDeployment::write($job.'/job.json',$config+['state_dir'=>$job]);PrivateDeployment::write($job.'/identity.json',$identity);PrivateDeployment::write($s.'/last-delivery.json',['job'=>$job,'deployment_id'=>$deployment]);
$checks=[];$check=static function(bool$ok,string$label)use(&$checks):void{if(!$ok)throw new RuntimeException('FAIL '.$label);$checks[]=$label;echo 'PASS '.$label."\n";};
$client=new ControlDelivery($job,$config);$fetched=$client->fetch('/var/lib/namua-control/release-signing/trusted/NAMUA_FINANCE.json');
$check($fetched['status']==='VERIFIED'&&$fetched['installed']===false,'HTTPS claims plan and streams all three signed artifacts without installing');
$check($db->query('SELECT COUNT(*) FROM deployment_artifact_downloads WHERE install_token_id IN (SELECT id FROM deployment_install_tokens WHERE deployment_id='.$deployment.')')->fetchColumn()==3,'exactly one download per artifact');
$check($client->fetch('/var/lib/namua-control/release-signing/trusted/NAMUA_FINANCE.json')['status']==='VERIFIED','verified retry is local and does not reuse consumed tokens');
$result=PrivateDeployment::read($resultPath);$bad=$result;$bad['web_verified']=false;$denied=false;try{$client->receipt($identity,$bad);}catch(RuntimeException$e){$denied=$e->getMessage()==='RECEIPT_EVIDENCE_REQUIRED';}
$check($denied&&$db->query('SELECT status FROM deployments WHERE id='.$deployment)->fetchColumn()==='RUNNING','database-only evidence cannot report a completed installation');
// Intermediate receipt exercises Finance dated migration IDs but must not complete the deployment.
$payload=['receipt_id'=>PrivateDeployment::uuid(),'instance_id'=>$identity['instance_id'],'occurred_at'=>gmdate(DATE_ATOM),'receipt_type'=>'MIGRATION_UP','status'=>'SUCCEEDED','environment'=>'DEMO','app_version'=>$m['version'],'from_schema'=>$result['from_schema'],'to_schema'=>$result['to_schema'],'migration_versions'=>$result['migration_versions'],'release_manifest_sha256'=>hash_file('sha256',$manifestPath),'artifact_sha256'=>$m['sha256'],'backup_sha256'=>$result['backup_sha256']];
$post=static function(array$p,string$n,?string$wrongSecret=null)use($config,$identity):array{$raw=json_encode($p,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$ts=gmdate(DATE_ATOM);$idem='practice-receipt-'.$p['receipt_id'];$sig=hash_hmac('sha256',implode("\n",['POST','/api/v1/deployment-receipts',$identity['instance_id'],$identity['key_id'],$ts,$n,$idem,hash('sha256',$raw)]),$wrongSecret??$identity['secret']);$h=curl_init($config['control_origin'].'/api/v1/deployment-receipts');curl_setopt_array($h,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$raw,CURLOPT_RETURNTRANSFER=>true,CURLOPT_TIMEOUT=>20,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_SSL_VERIFYPEER=>true,CURLOPT_SSL_VERIFYHOST=>2,CURLOPT_CAINFO=>$config['ca_file'],CURLOPT_HTTPHEADER=>['Content-Type: application/json','X-Namua-Instance-ID: '.$identity['instance_id'],'X-Namua-Key-ID: '.$identity['key_id'],'X-Namua-Timestamp: '.$ts,'X-Namua-Nonce: '.$n,'Idempotency-Key: '.$idem,'X-Namua-Signature: '.$sig]]);$out=curl_exec($h);$status=(int)curl_getinfo($h,CURLINFO_RESPONSE_CODE);curl_close($h);return ['http'=>$status,'json'=>json_decode((string)$out,true)];};
$n=bin2hex(random_bytes(24));$progress=$post($payload,$n);$check($progress['http']===202&&$db->query('SELECT status FROM deployments WHERE id='.$deployment)->fetchColumn()==='RUNNING','dated Finance migrations accepted without prematurely completing deployment');
$replay=$payload;$replay['receipt_id']=PrivateDeployment::uuid();$check($post($replay,$n)['http']===409,'receipt nonce replay rejected');
$check($post($replay,bin2hex(random_bytes(24)),str_repeat('x',43))['http']===401,'wrong instance secret rejected');
$receipt=$client->receipt($identity,$result);$check($receipt['status']==='ACKNOWLEDGED'&&$db->query('SELECT status FROM deployments WHERE id='.$deployment)->fetchColumn()==='SUCCEEDED','web-verified activation receipt completes matching deployment');
$check(($client->receipt($identity,$result)['duplicate']??false)===true,'lost acknowledgement can retry idempotently');
PrivateDeployment::write($job.'/acceptance.json',['status'=>'PASS','checks'=>count($checks),'passed'=>$checks,'artifact_sha256'=>$m['sha256'],'at'=>date(DATE_ATOM)]);
echo 'All '.count($checks).' Control delivery HTTPS checks passed. Evidence: '.$job.'/acceptance.json'."\n";
