<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
function finance_control_operations_fixture($db,$context,$check,string $root): void
{
    require APPPATH.'models/Finance_control_operation_model.php';
    $context->Finance_control_operation_model=new Finance_control_operation_model();$op=$context->Finance_control_operation_model;
    $db->query('SET GLOBAL innodb_flush_log_at_trx_commit=2'); // Only this disposable socket-only fixture server.
    $sql=preg_replace('/^--.*$/m','',file_get_contents($root.'/sql/2026-09-14b_finance_control_operations.sql'));
    for($round=1;$round<=2;$round++)foreach(explode(';',$sql) as $statement)if(trim($statement)!=='')$check($db->query($statement)!==false,'operations migration repeat-safe '.$round.': '.substr(trim($statement),0,50));
    $db->data_cache=[];
    $put=static function($table,$data)use($db):int{if(!$db->insert($table,$data))throw new RuntimeException('Fixture insert '.$table.' '.json_encode($db->error()));return (int)$db->insert_id();};
    $ok=static function(array $result,string $label)use($check):array{$check(!empty($result['ok']),$label.': '.($result['message']??''));if(empty($result['ok']))throw new RuntimeException($label.' '.json_encode($result));return $result;};
    $deny=static function(array $result,string $label)use($check):void{$check(empty($result['ok']),$label.': '.($result['message']??''));};
    $today=date('Y-m-d');$tomorrow=date('Y-m-d',strtotime('+1 day'));
    foreach([1,2] as $uid)if(!$db->get_where('auth_user',['id'=>$uid])->row_array())$put('auth_user',['id'=>$uid,'username'=>'fixture-'.$uid,'password_hash'=>'disabled']);
    $put('fin_company_account',['id'=>1,'account_code'=>'TEST','account_name'=>'Fixture IDR bank','current_balance'=>1000,'opening_balance'=>0]);
    $put('fin_company_account',['id'=>2,'account_code'=>'TEST2','account_name'=>'Other fixture bank','current_balance'=>1000,'opening_balance'=>0]);
    $put('pos_payment_method',['id'=>1,'method_code'=>'ONLINE','method_name'=>'Platform fixture','method_type'=>'EWALLET','company_account_id'=>1]);
    $put('pos_payment',['id'=>1,'payment_no'=>'P-1','order_id'=>1,'payment_type'=>'FINAL','payment_status'=>'PAID','paid_at'=>$today.' 10:00:00']);
    $put('pos_payment_line',['id'=>1,'payment_id'=>1,'line_no'=>1,'payment_method_id'=>1,'amount'=>1000,'status'=>'PAID']);
    $posMutationId=$put('fin_account_mutation_log',['mutation_no'=>'POS-1','mutation_date'=>$today,'account_id'=>1,'mutation_type'=>'IN','amount'=>1000,'ref_module'=>'POS','ref_table'=>'pos_payment','ref_id'=>1]);
    $insight=$context->Finance_insight_model;$purchase=$context->Purchase_model;
    $balance=static fn()=>(float)$db->get_where('fin_company_account',['id'=>1])->row('current_balance');
    $trace=Finance_settlement_control::trace($db,$today,1);
    $casePayload=['revenue_date'=>$today,'payment_method_id'=>1,'provider_reference'=>'OPS-'.$today,'due_date'=>$today,'received_amount'=>'100','settlement_complete'=>false,'source_fingerprint'=>$trace['source_fingerprint'],'revision'=>0,'notes'=>'Fixture historic confirmed total'];
    $deny($insight->save_settlement($casePayload,1),'new settlement must use detailed receipts');
    $caseId=$ok($insight->save_settlement(array_replace($casePayload,['received_amount'=>0]),1),'new case starts at zero')['id'];
    $db->where('id',$caseId)->update('fin_settlement_control',['received_amount'=>100,'receipt_mode'=>0,'receipt_opening_amount'=>null]); // Synthetic predecessor metadata only.
    $case=static fn()=>$db->get_where('fin_settlement_control',['id'=>$caseId])->row_array();
    $receipt=['settlement_id'=>$caseId,'revision'=>1,'request_key'=>str_repeat('a',32),'received_date'=>$today,'reference_no'=>'BANK-1','amount'=>'400.25','notes'=>'Transfer one'];
    $rid=$ok($op->save_receipt($receipt,1),'first detailed receipt')['id'];
    $check((float)$case()['received_amount']===500.25 && (float)$case()['receipt_opening_amount']===100.0 && $balance()===1000.0,'legacy opening retained, receipt does not post bank');
    $ok($op->save_receipt($receipt,1),'receipt retry');
    $deny($op->save_receipt(array_replace($receipt,['amount'=>'400.26']),1),'retry changed amount rejected');
    $deny($op->save_receipt(array_replace($receipt,['request_key'=>str_repeat('b',32)]),1),'stale case revision rejected');
    $deny($op->save_receipt(array_replace($receipt,['revision'=>$case()['revision'],'request_key'=>str_repeat('b',32)]),1),'same transfer reference rejected');
    $deny($op->save_receipt(array_replace($receipt,['revision'=>$case()['revision'],'request_key'=>str_repeat('b',32),'reference_no'=>'BANK-2','received_date'=>$tomorrow]),1),'future receipt rejected');
    $ok($op->save_receipt(array_replace($receipt,['revision'=>$case()['revision'],'request_key'=>str_repeat('c',32),'reference_no'=>'BANK-2','amount'=>'299.75']),1),'second receipt sums automatically');
    $check((float)$case()['received_amount']===800.0,'two transfers plus legacy total exact cents');
    $deny($insight->save_settlement(array_replace($casePayload,['revision'=>$case()['revision'],'received_amount'=>'999']),1),'manual aggregate overwrite blocked once detailed');
    $ok($op->void_receipt(['id'=>$rid,'revision'=>$case()['revision'],'reason'=>'wrong proof'],1),'receipt VOID metadata only');
    $ok($op->void_receipt(['id'=>$rid,'revision'=>0,'reason'=>'retry'],1),'receipt VOID retry');
    $check((float)$case()['received_amount']===399.75 && $balance()===1000.0,'receipt VOID adjusts aggregate only');
    $ok($op->save_receipt(array_replace($receipt,['revision'=>$case()['revision'],'request_key'=>str_repeat('d',32)]),1),'corrected transfer reuses voided reference');
    $charge=['settlement_id'=>$caseId,'id'=>0,'revision'=>0,'request_key'=>str_repeat('e',32),'charge_date'=>$today,'document_no'=>'INV-ONE','line_reference'=>'FEE-1','category'=>'PLATFORM_FEE','direction'=>'OUT','amount'=>'100','notes'=>'First fee'];
    $chargeId=$ok($op->save_charge($charge,1),'first charge identity')['id'];
    $ok($op->save_charge($charge,1),'charge definition retry');
    $deny($op->save_charge(array_replace($charge,['request_key'=>str_repeat('f',32)]),1),'same document line duplicate rejected');
    $deny($op->save_charge(array_replace($charge,['request_key'=>str_repeat('f',32),'category'=>'OTHER_INCOME']),1),'category direction mismatch');
    $secondId=$ok($op->save_charge(array_replace($charge,['request_key'=>str_repeat('f',32),'line_reference'=>'FEE-2','amount'=>'50']),1),'same category distinct line accepted')['id'];
    $fee=['account_id'=>1,'mutation_type'=>'OUT','amount'=>100,'mutation_date'=>$today,'report_category'=>'PLATFORM_FEE','client_request_key'=>str_repeat('1',32),'reference_no'=>'INV-ONE','settlement_confirmed'=>true,'settlement_control_id'=>$caseId,'settlement_charge_id'=>$chargeId,'notes'=>'Post fee'];
    $deny($purchase->apply_manual_account_mutation(array_replace($fee,['settlement_charge_id'=>0]),1),'new linked posting requires identity');
    $deny($purchase->apply_manual_account_mutation(array_replace($fee,['amount'=>101]),1),'charge amount bound');
    $deny($purchase->apply_manual_account_mutation(array_replace($fee,['account_id'=>2]),1),'charge account bound');
    $ok($purchase->apply_manual_account_mutation($fee,1),'post fee with identity');
    $ok($purchase->apply_manual_account_mutation($fee,1),'posting retry remains idempotent');
    $deny($purchase->apply_manual_account_mutation(array_replace($fee,['client_request_key'=>str_repeat('2',32)]),1),'same line posted twice blocked');
    $ok($purchase->apply_manual_account_mutation(array_replace($fee,['client_request_key'=>str_repeat('2',32),'settlement_charge_id'=>$secondId,'amount'=>50]),1),'second same-category line really posts');
    $check($balance()===850.0,'two fees count exactly once');
    $deny($op->save_charge(array_replace($charge,['id'=>$chargeId,'revision'=>1,'amount'=>101]),1),'posted charge immutable');
    $policy=Finance_settlement_control::policy($db);$check(!(int)$policy['approval_enabled'],'approvals default disabled');
    $ok($op->save_policy(['revision'=>$policy['revision'],'approval_enabled'=>1,'approval_threshold'=>50,'evidence_required'=>0,'payroll_day'=>25,'notes'=>'Fixture approval enabled'],1),'configure optional approval');
    $third=$ok($op->save_charge(array_replace($charge,['request_key'=>str_repeat('3',32),'line_reference'=>'FEE-3','amount'=>75]),1),'approval target')['id'];
    $thirdFee=array_replace($fee,['client_request_key'=>str_repeat('4',32),'settlement_charge_id'=>$third,'amount'=>75]);
    $deny($purchase->apply_manual_account_mutation($thirdFee,1),'threshold approval required before debit');
    $request=['action_code'=>'POST_CHARGE','target_id'=>$third,'reason'=>'Check bank fee'];
    $ok($op->request_approval($request,1),'request review');$aid=(int)$db->order_by('id','DESC')->get('fin_control_approval',1)->row('id');
    $deny($op->review_approval(['id'=>$aid,'decision'=>'APPROVED','reason'=>'self'],1),'self approval denied');
    $ok($op->review_approval(['id'=>$aid,'decision'=>'APPROVED','reason'=>'checked by second user'],2),'second user approval');
    $ok($op->save_charge(array_replace($charge,['id'=>$third,'revision'=>1,'line_reference'=>'FEE-3','amount'=>80]),1),'edit unposted approved amount');
    $deny($purchase->apply_manual_account_mutation(array_replace($thirdFee,['amount'=>80]),1),'changed amount invalidates approval');
    $ok($op->request_approval($request,1),'request fresh amount');$aid=(int)$db->order_by('id','DESC')->get('fin_control_approval',1)->row('id');
    $ok($op->review_approval(['id'=>$aid,'decision'=>'APPROVED','reason'=>'80 verified'],2),'approve fresh amount');
    $ok($purchase->apply_manual_account_mutation(array_replace($thirdFee,['amount'=>80]),1),'approved post');
    $check($db->get_where('fin_control_approval',['id'=>$aid])->row('status')==='CONSUMED' && $balance()===770.0,'approval consumed atomically with posting');
    $mutation=$db->get_where('fin_account_mutation_log',['settlement_charge_id'=>$third])->row_array();
    $void=['mutation_id'=>$mutation['id'],'reason'=>'Wrong separate fee'];
    $deny($insight->void_adjustment($void,1),'VOID also requires threshold approval');
    $ok($op->request_approval(['action_code'=>'VOID_ADJUSTMENT','target_id'=>$mutation['id'],'reason'=>'Wrong fee'],1),'request VOID');$aid=(int)$db->order_by('id','DESC')->get('fin_control_approval',1)->row('id');
    $ok($op->review_approval(['id'=>$aid,'decision'=>'APPROVED','reason'=>'refund adjustment verified'],2),'approve VOID');
    $planPayload=['request_key'=>str_repeat('5',32),'title'=>'Platform service','direction'=>'OUT','amount'=>'120','due_date'=>$today,'certainty'=>'COMMITTED','status'=>'OPEN','revision'=>0,'notes'=>'Fixture plan'];
    $planId=$ok($insight->save_plan($planPayload,1),'cash plan')['id'];
    $link=['plan_id'=>$planId,'revision'=>1,'mutation_id'=>$mutation['id'],'notes'=>'Already posted fee'];
    $ok($op->link_plan($link,1),'link actual without posting');$ok($op->link_plan($link,1),'link retry');
    $plan=$insight->forecast(7)['plans'][0];$check($plan['actual']===80.0 && $plan['remaining']===40.0 && $balance()===770.0,'plan forecast only remaining, no double cash');
    $deny($op->link_plan(array_replace($link,['mutation_id'=>$posMutationId,'revision'=>2]),1),'POS cannot be counted as manual realization');
    $ok($insight->void_adjustment($void,1),'approved VOID after linking');
    $plan=$insight->forecast(7)['plans'][0];$check($plan['actual']===0.0 && $plan['remaining']===120.0 && $balance()===850.0,'VOID reopens planned remaining automatically');
    $check(Finance_insight_model::payroll_forecast_date('2026-01-31',31)==='2026-02-28','short month payroll clamp');
    $check(Finance_insight_model::payroll_forecast_date('2026-09-14',25)==='2026-09-25','configured payroll day after period end');
    $check(Finance_insight_model::payroll_forecast_date('2026-09-30',25)==='2026-10-25','next month payroll schedule');
    $check(count($op->approvals()['rows'])>=3,'review list loads usernames and actual facts');
    $firstMutation=$db->get_where('fin_account_mutation_log',['settlement_charge_id'=>$chargeId])->row_array();
    $plan2=$ok($insight->save_plan(array_replace($planPayload,['request_key'=>str_repeat('6',32),'title'=>'Second plan']),1),'second plan')['id'];
    $ok($op->link_plan(['plan_id'=>$planId,'revision'=>2,'mutation_id'=>$firstMutation['id'],'notes'=>'Actual fee'],1),'link active fee');
    $deny($op->link_plan(['plan_id'=>$plan2,'revision'=>1,'mutation_id'=>$firstMutation['id'],'notes'=>'Duplicate allocation'],1),'one mutation cannot realize two plans');
    $deny($insight->save_plan(array_replace($planPayload,['id'=>$planId,'revision'=>3,'direction'=>'IN']),1),'linked plan direction immutable');
    $deny($insight->save_plan(array_replace($planPayload,['id'=>$planId,'revision'=>3,'status'=>'DONE']),1),'cannot hide remaining by marking linked plan done');
    $linkRow=$db->get_where('fin_cash_plan_realization',['active_mutation_id'=>$firstMutation['id']])->row_array();
    $ok($op->unlink_plan(['id'=>$linkRow['id'],'revision'=>3,'reason'=>'Wrong plan'],1),'unlink leaves original mutation intact');
    $check($balance()===850.0,'all plan linking/unlinking left bank unchanged');
    $policy=Finance_settlement_control::policy($db);
    $ok($op->save_policy(['revision'=>$policy['revision'],'approval_enabled'=>0,'approval_threshold'=>50,'evidence_required'=>0,'payroll_day'=>25,'notes'=>'Test legacy identities'],1),'disable policy explicitly');
    $legacyId=$put('fin_account_mutation_log',['mutation_no'=>'LEGACY-FEE','mutation_date'=>$today,'account_id'=>1,'mutation_type'=>'OUT','amount'=>10,'ref_module'=>'FINANCE','report_category'=>'PLATFORM_FEE','settlement_control_id'=>$caseId]);
    $fourth=$ok($op->save_charge(array_replace($charge,['request_key'=>str_repeat('7',32),'line_reference'=>'FEE-4','amount'=>10]),1),'new fee with unstructured legacy present')['id'];
    $fee4=array_replace($fee,['client_request_key'=>str_repeat('8',32),'settlement_charge_id'=>$fourth,'amount'=>10]);
    $deny($purchase->apply_manual_account_mutation($fee4,1),'unidentified historical same-category fee blocks potential double expense');
    $ok($op->save_charge(array_replace($charge,['request_key'=>str_repeat('9',32),'line_reference'=>'LEGACY','amount'=>10,'existing_mutation_id'=>$legacyId]),1),'explicit legacy identification without double posting');
    $ok($purchase->apply_manual_account_mutation($fee4,1),'separate fee allowed after legacy identified');
    $balanceBefore=$balance();$receiptBefore=$case()['received_amount'];
    $db->query("CREATE TRIGGER fixture_operations_audit_fail BEFORE INSERT ON aud_transaction_log FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='synthetic audit failure'");
    $deny($op->save_receipt(array_replace($receipt,['revision'=>$case()['revision'],'request_key'=>str_repeat('b',32),'reference_no'=>'ROLLBACK']),1),'audit failure rolls back receipt and total');
    $check($case()['received_amount']===$receiptBefore && $balance()===$balanceBefore,'receipt audit failure is atomic');
    $db->query('DROP TRIGGER fixture_operations_audit_fail');
    $ok($insight->save_settlement(array_replace($casePayload,['revision'=>$case()['revision'],'received_amount'=>$case()['received_amount'],'settlement_complete'=>true]),1),'complete settlement before recon');
    $revenue=$context->Finance_revenue_reconciliation_model;
    $adjusted=$insight->settlement($today,1)['expected_net'];$actual=(float)$case()['received_amount'];$remainingFee=round($adjusted-$actual,2);
    $reconCharge=$ok($op->save_charge(array_replace($charge,['request_key'=>bin2hex(random_bytes(16)),'line_reference'=>'RECON-1','amount'=>$remainingFee]),1),'remaining reconciliation cost')['id'];
    $draft=$ok($revenue->save_line(['reconciliation_date'=>$today,'revenue_date'=>$today,'payment_method_id'=>1,'account_id'=>1,'actual_amount'=>$actual,'resolution_type'=>'OUT','report_category'=>'PLATFORM_FEE','settlement_control_id'=>$caseId,'settlement_charge_id'=>$reconCharge],1),'revenue draft with charge identity');
    $ok($revenue->post_line($draft['line_id'],1),'revenue writer posts only separate identified remaining fee');
    $check($db->get_where('fin_account_mutation_log',['settlement_charge_id'=>$reconCharge])->num_rows()===1,'revenue writer persists identity');
    $cashCharge=$ok($op->save_charge(array_replace($charge,['request_key'=>bin2hex(random_bytes(16)),'line_reference'=>'CASH-1','amount'=>5]),1),'cash reconciliation identity')['id'];
    $cash=$context->Finance_cash_reconciliation_model;
    $draft=$ok($cash->save_line(['reconciliation_date'=>$today,'account_id'=>1,'actual_balance'=>(string)($balance()-5),'resolution_type'=>'OUT','report_category'=>'PLATFORM_FEE','settlement_control_id'=>$caseId,'settlement_charge_id'=>$cashCharge],1),'cash recon draft identity');
    $ok($cash->post_line($draft['line']['id'],1),'cash writer posts distinct identified fee');
    $check($db->get_where('fin_account_mutation_log',['settlement_charge_id'=>$cashCharge])->num_rows()===1,'cash writer persists identity');
    $policy=Finance_settlement_control::policy($db);
    $ok($op->save_policy(['revision'=>$policy['revision'],'approval_enabled'=>1,'approval_threshold'=>50,'evidence_required'=>1,'payroll_day'=>25,'notes'=>'Test proof requirement'],1),'optional evidence policy enabled in fixture only');
    $largeId=$ok($op->save_charge(array_replace($charge,['request_key'=>bin2hex(random_bytes(16)),'line_reference'=>'LARGE-FEE','amount'=>10000]),1),'unfunded fee approval target')['id'];
    $largeFee=array_replace($fee,['client_request_key'=>bin2hex(random_bytes(16)),'settlement_charge_id'=>$largeId,'amount'=>10000]);
    $deny($purchase->apply_manual_account_mutation($largeFee,1),'proof policy blocks posting without evidence');
    $policy=Finance_settlement_control::policy($db);
    $ok($op->save_policy(['revision'=>$policy['revision'],'approval_enabled'=>1,'approval_threshold'=>50,'evidence_required'=>0,'payroll_day'=>25,'notes'=>'Test rollback with approval only'],1),'approval-only policy');
    $ok($op->request_approval(['action_code'=>'POST_CHARGE','target_id'=>$largeId,'reason'=>'large fixture fee'],1),'request large fee');$largeAid=(int)$db->order_by('id','DESC')->get('fin_control_approval',1)->row('id');
    $ok($op->review_approval(['id'=>$largeAid,'decision'=>'APPROVED','reason'=>'approved exact amount'],2),'approve large fee');
    $balanceBefore=$balance();$deny($purchase->apply_manual_account_mutation($largeFee,1),'insufficient balance rejects approved posting');
    $check($balance()===$balanceBefore && $db->get_where('fin_control_approval',['id'=>$largeAid])->row('status')==='APPROVED','failed posting restores approval and balance atomically');
    $policy=Finance_settlement_control::policy($db);
    $ok($op->save_policy(['revision'=>$policy['revision'],'approval_enabled'=>1,'approval_threshold'=>100,'evidence_required'=>0,'payroll_day'=>25,'notes'=>'Policy changed after approval'],1),'change policy invalidates old approval');
    $rows=$op->approvals()['rows'];$stale=array_values(array_filter($rows,static fn($row)=>(int)$row['id']===$largeAid))[0];$check($stale['stale'],'UI marks stale approved facts');
    $deny($purchase->apply_manual_account_mutation($largeFee,1),'old approval cannot survive policy change');
    $deny($op->request_approval(['action_code'=>'POST_CHARGE','target_id'=>$chargeId,'reason'=>'repost'],1),'cannot request approval of already posted charge');
    require_once __DIR__.'/finance_control_operations_http_cases.php';
    finance_control_operations_http_cases($db,$check,$root,$caseId);
    if(in_array('--export-ui',$GLOBALS['argv'],true)){
        $dir=sys_get_temp_dir().'/finance-control-ops-ui-'.bin2hex(random_bytes(6));if(!mkdir($dir,0700))throw new RuntimeException('UI directory failed');
        foreach(['settlement','cash-plan','approvals','settings'] as $tab)foreach([true,false] as $edit){
            $result=match($tab){'settlement'=>$insight->settlement($today,1),'cash-plan'=>$insight->forecast(7),'approvals'=>$op->approvals(),'settings'=>Finance_settlement_control::policy($db)};
            $data=['tab'=>$tab,'result'=>$result,'can_edit'=>$edit,'csrf'=>str_repeat('a',64),'error'=>'','date'=>$today,'method_id'=>1,'methods'=>$insight->methods(),'month'=>date('Y-m'),'days'=>7,'operations_ready'=>true,'operation_details'=>$op->details($caseId),'can_approve'=>$edit,'can_settings'=>$edit,'can_void_modules'=>array_fill_keys(['FINANCE','FINANCE_RECON','REVENUE_RECON'],$edit)];
            ob_start();(function($data){extract($data);include APPPATH.'views/finance/control.php';})->call($context,$data);$html=ob_get_clean();file_put_contents($dir.'/'.$tab.($edit?'':'-readonly').'.html',$html);
        }
        ob_start();(function($data){extract($data);include APPPATH.'views/finance/_settlement_select.php';})->call($context,['settlement_selected'=>$caseId,'settlement_charge_selected'=>$chargeId,'settlement_options'=>[]]);file_put_contents($dir.'/picker.html',ob_get_clean());
        echo 'UI_FIXTURE='.$dir.PHP_EOL;
    }
    for($i=1;$i<=205;$i++)$put('fin_settlement_control',['revenue_date'=>date('Y-m-d',strtotime($today.' -'.$i.' days')),'payment_method_id'=>1,'account_id'=>1,'provider_reference'=>'OLD-'.$i,'due_date'=>$today,'expected_amount'=>0,'source_fingerprint'=>str_repeat('0',64),'notes'=>'Synthetic search only']);
    $found=$op->search(['q'=>'OLD-205']);$check($found['total']===1 && $found['rows'][0]['provider_reference']==='OLD-205','search reaches beyond old 200-record cutoff');
    $found=$op->search(['page'=>9]);$check($found['total']===206 && $found['page']===9 && count($found['rows'])===6,'all-history pagination stable');
    $check($op->search(['q'=>"' OR 1=1 --"])['total']===0,'search bound parameters');
    $check($op->search(['q'=>'%'])['total']===0 && $op->search(['q'=>'_'])['total']===0,'search treats wildcard characters literally');
    echo "Finance control operations fixtures complete.\n";
}
