<?php
declare(strict_types=1);
if(PHP_SAPI!=='cli'){http_response_code(404);exit;}
$root=dirname(__DIR__,2);$n=0;
$check=static function($yes,$label)use(&$n){if(!$yes)throw new RuntimeException('FAIL '.$label);$n++;echo 'PASS '.$label.PHP_EOL;};
$read=static fn($f)=>file_get_contents($root.'/'.$f);
$controller=$read('application/controllers/Finance_insights.php');
$guard=$read('application/libraries/Finance_settlement_control.php');
$model=$read('application/models/Finance_insight_model.php');
$pos=$read('application/models/Pos_report_model.php');
$view=$read('application/views/finance/control.php');
$check(str_contains($controller,"require_permission(self::PAGE,'view')") && str_contains($controller,"require_permission(self::PAGE,'edit')"),'separate view/edit RBAC');
$check(str_contains($controller,'hash_equals($expected,$provided)') && str_contains($controller,"method(true)!=='POST'") && str_contains($controller,'X-Finance-Control-CSRF'),'POST scoped session CSRF');
$check(str_contains($model,'source_fingerprint') && str_contains($guard,'source_fingerprint'),'source changes invalidate settlement');
$check(str_contains($guard,'FOR UPDATE') && str_contains($guard,'self::effective()'),'shared claim locks effective non-VOID category');
foreach(['Purchase_model','Finance_cash_reconciliation_model','Finance_revenue_reconciliation_model'] as $name)$check(str_contains($read('application/models/'.$name.'.php'),'Finance_settlement_control::assert_post'),'writer participates '.$name);
$check(str_contains($guard,"['REVENUE_RECON','FINANCE_RECON']") && str_contains($guard,"case['settlement_complete']"),'partial payouts cannot become linked reconciliation expense');
$check(str_contains($model,"'request_key'") && str_contains($model,"'revision'") && str_contains($model,"'aud_transaction_log'"),'cash plan retry/revision/audit');
$metadata=explode('public function adjustment_permission',explode('public function save_settlement',$model,2)[1],2)[0];
$check(!preg_match('/(?:insert|update|delete)\([^\n]*(?:pos_order|pos_payment|fin_company_account)/',$metadata),'confirmation and plan metadata never mutate POS or account balances');
$check(str_contains($controller,"require_permission($".'page,\'edit\')') && str_contains($model,"'SETTLEMENT_ADJUSTMENT_VOID'") && str_contains($model,"'reversal_of_mutation_id'=>$".'id'),'linked void requires original permission, reversal link and audit');
$check(str_contains($model,'$opening=round($book-$pending,2)'),'forecast subtracts booked pending cash first');
$check(str_contains($pos,'financial_profit_loss_basis') && str_contains($pos,"r.refunded_at>=?") && str_contains($pos,'a.recognition_date>=?'),'P&L source dates include period refund/deficit');
$check(str_contains($view,'data-save="settlement"') && str_contains($view,'data-save="cash-plan"') && str_contains($view,'JSON_HEX_TAG'),'named UI workflows and safe JSON');
$check(str_contains($view,"if($".'can_edit)') && str_contains($view,'message.textContent=text'),'read-only UI and safe error rendering');
$catalog=json_decode($read('tools/db/migration_catalog.json'),true);$m=array_column($catalog['migrations'],null,'id')['2026-09-14a-finance-control-workspace'];
$check(hash_file('sha256',$root.'/'.$m['path'])===$m['sha256'] && $m['dependencies']===['2026-09-13a-finance-mutation-reporting-category'],'migration exact checksum and dependency');
$profile=json_decode($read('tools/release/customer_clean_profile.json'),true);$check($profile['profile_version']===11 && ($profile['sql_sha256'][$m['path']]??'')===$m['sha256'],'versioned clean profile retains registered SQL');
foreach(['application/controllers/Finance_insights.php','application/models/Finance_insight_model.php','application/libraries/Finance_settlement_control.php','application/views/finance/control.php','application/views/finance/_settlement_select.php'] as $file)$check(in_array($file,$profile['code_files'],true),'clean runtime includes '.$file);
$check(!str_contains($read($m['path']),'DELETE FROM') && !str_contains($read($m['path']),'UPDATE fin_company_account'),'migration does not repair balances');
require $root.'/tools/release/CustomerReleaseProfile.php';
require $root.'/tools/install/ControlDelivery.php';
$policy=CustomerReleaseProfile::fromRoot($root);$check($policy->version()===11,'actual profile parser exposes version 11');
$bad=$profile;$bad['profile_version']=999;try{new CustomerReleaseProfile(json_encode($bad));$rejected=false;}catch(RuntimeException $e){$rejected=true;}$check($rejected,'unknown profile version rejected');
$binding=['distribution_profile'=>'CUSTOMER_CLEAN','distribution_profile_version'=>3,'seed_profile'=>'REFERENCE_ONLY'];
$verified=$binding+['customer_clean_eligible'=>true,'customer_content_audit'=>['profile_sha256'=>$policy->digest()]];
$plan=['release'=>$binding+['customer_content_profile_sha256'=>$policy->digest()]];
ControlDelivery::validateCustomerBinding($plan,$verified);$check(true,'delivery accepts exactly matching verified v3 binding');
$plan['release']['distribution_profile_version']=1;try{ControlDelivery::validateCustomerBinding($plan,$verified);$rejected=false;}catch(RuntimeException $e){$rejected=true;}$check($rejected,'delivery rejects plan v1 for verified v3 artifact');
echo 'Finance control contract: '.$n.' PASS. No database accessed.'.PHP_EOL;
