#!/usr/bin/env bash
# Start the persistent SSH forward on the replica host (Server 2).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../backup/.env"

if [[ ! -r "$ENV_FILE" ]]; then
  echo "[ERROR] Config tidak ditemukan: ${ENV_FILE}" >&2
  exit 1
fi
# Generated by System Tools; values are shell-quoted by the application.
# shellcheck source=/dev/null
source "$ENV_FILE"

SSH_HOST="${SSH_HOST:-}"
SSH_PORT="${SSH_PORT:-22}"
SSH_USER="${SSH_USER:-root}"
LOCAL_PORT="${TUNNEL_LOCAL_PORT:-3307}"
REMOTE_PORT="${TUNNEL_REMOTE_PORT:-3306}"

for name in SSH_PORT LOCAL_PORT REMOTE_PORT; do
  value="${!name}"
  if [[ ! "$value" =~ ^[0-9]+$ ]] || (( value < 1 || value > 65535 )); then
    echo "[ERROR] ${name} harus berupa port 1-65535." >&2
    exit 1
  fi
done

if [[ -z "$SSH_HOST" || -z "$SSH_USER" ]]; then
  echo "[ERROR] Isi SSH_HOST dan SSH_USER di pengaturan DB Tools." >&2
  exit 1
fi

if ! command -v ssh >/dev/null 2>&1; then
  echo "[ERROR] OpenSSH client tidak ditemukan." >&2
  exit 1
fi

if command -v ss >/dev/null 2>&1 && ss -ltn "sport = :${LOCAL_PORT}" 2>/dev/null | tail -n +2 | grep -q .; then
  echo "[ERROR] Port lokal ${LOCAL_PORT} sudah dipakai. Verifikasi listener tersebut adalah tunnel yang benar." >&2
  exit 2
fi

SSH_OPTS=(
  -N
  -o BatchMode=yes
  -o ExitOnForwardFailure=yes
  -o StrictHostKeyChecking=yes
  -o ServerAliveInterval=30
  -o ServerAliveCountMax=3
  -p "$SSH_PORT"
  -L "127.0.0.1:${LOCAL_PORT}:127.0.0.1:${REMOTE_PORT}"
)

echo "Membuka tunnel di Server 2: 127.0.0.1:${LOCAL_PORT} -> ${SSH_USER}@${SSH_HOST}:127.0.0.1:${REMOTE_PORT}"
echo "Pastikan SSH key tersedia dan host key Server 1 sudah diverifikasi di known_hosts."

if command -v autossh >/dev/null 2>&1; then
  AUTOSSH_GATETIME=0 autossh -M 0 -f "${SSH_OPTS[@]}" "${SSH_USER}@${SSH_HOST}"
  echo "Tunnel dimulai dengan autossh (reconnect otomatis)."
else
  ssh -f "${SSH_OPTS[@]}" "${SSH_USER}@${SSH_HOST}"
  echo "Tunnel dimulai dengan ssh. Peringatan: install autossh atau gunakan systemd untuk reconnect otomatis."
fi
