<?php
$employee = $employee ?? null;
$employeeOptions = $employee_options ?? [];
$selectedEmployeeId = (int)($selected_employee_id ?? 0);
$filters = $filters ?? [];
$rows = $rows ?? [];
$pg = $pg ?? ['page' => 1, 'total_pages' => 1, 'per_page' => 25, 'total' => 0];
$statusOptions = $status_options ?? ['DRAFT', 'APPROVED', 'REJECTED', 'SETTLED', 'VOID'];
?>
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2">
  <div><h4 class="mb-0"><?php echo html_escape($title ?? 'Kasbon Saya'); ?></h4><small class="text-muted">Status kasbon, outstanding, dan cicilan per periode.</small></div>
  <?php if (!empty($employeeOptions)): ?><form method="get" action="<?php echo site_url('my/cash-advance'); ?>" class="d-flex gap-2"><select name="employee_id" class="form-select form-select-sm" style="min-width:260px"><option value="">Pilih Pegawai (Preview Superadmin)</option><?php foreach($employeeOptions as $o): ?><option value="<?php echo (int)$o['value']; ?>" <?php echo ((int)$o['value'] === $selectedEmployeeId) ? 'selected' : ''; ?>><?php echo html_escape((string)$o['label']); ?></option><?php endforeach; ?></select><button type="submit" class="btn btn-sm btn-primary">Buka</button></form><?php endif; ?>
</div>
<?php if (!$employee): ?><div class="alert alert-warning">Data pegawai tidak ditemukan pada akun ini.</div><?php else: ?>
<div class="card mb-3"><div class="card-body"><form method="get" action="<?php echo site_url('my/cash-advance'); ?>" class="row g-2 align-items-end"><?php if ($selectedEmployeeId): ?><input type="hidden" name="employee_id" value="<?php echo $selectedEmployeeId; ?>"><?php endif; ?><div class="col-md-2"><label class="form-label mb-1">Status</label><select name="status" class="form-select"><option value="">Semua</option><?php foreach($statusOptions as $s): ?><option value="<?php echo html_escape($s); ?>" <?php echo (($filters['status'] ?? '') === $s) ? 'selected' : ''; ?>><?php echo html_escape($s); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label mb-1">Dari</label><input type="date" name="date_start" class="form-control" value="<?php echo html_escape((string)($filters['date_start'] ?? '')); ?>"></div><div class="col-md-2"><label class="form-label mb-1">Sampai</label><input type="date" name="date_end" class="form-control" value="<?php echo html_escape((string)($filters['date_end'] ?? '')); ?>"></div><div class="col-md-1"><label class="form-label mb-1">Per</label><select name="per_page" class="form-select"><?php foreach([10,25,50,100] as $p): ?><option value="<?php echo $p; ?>" <?php echo ((int)$pg['per_page'] === $p) ? 'selected' : ''; ?>><?php echo $p; ?></option><?php endforeach; ?></select></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-primary" type="submit">Filter</button><a href="<?php echo site_url('my/cash-advance' . ($selectedEmployeeId ? ('?employee_id=' . $selectedEmployeeId) : '')); ?>" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th>No Kasbon</th><th>Tgl</th><th>Status</th><th class="text-end">Nominal</th><th class="text-end">Outstanding</th><th class="text-end">Skema</th><th class="text-end">Rencana Cicilan</th></tr></thead><tbody><?php if(empty($rows)): ?><tr><td colspan="7" class="text-center text-muted py-4">Belum ada data kasbon.</td></tr><?php else: foreach($rows as $r): ?><tr><td><?php echo html_escape((string)($r['advance_no'] ?? '-')); ?></td><td><?php echo html_escape((string)($r['request_date'] ?? '-')); ?></td><td><span class="badge bg-<?php $st=strtoupper((string)($r['status'] ?? 'DRAFT')); echo $st==='APPROVED'?'success':($st==='SETTLED'?'primary':($st==='REJECTED'?'danger':'secondary')); ?>"><?php echo html_escape((string)($r['status'] ?? 'DRAFT')); ?></span></td><td class="text-end"><?php echo number_format((float)($r['amount'] ?? 0), 2, ',', '.'); ?></td><td class="text-end fw-semibold"><?php echo number_format((float)($r['outstanding_amount'] ?? 0), 2, ',', '.'); ?></td><td class="text-end"><?php echo ((int)($r['tenor_month'] ?? 0) > 0) ? ('Tenor ' . (int)($r['tenor_month'] ?? 0) . ' bln') : 'Fleksibel'; ?></td><td class="text-end"><?php echo number_format((float)($r['monthly_deduction_plan'] ?? 0), 2, ',', '.'); ?></td></tr>
<tr><td colspan="7" class="pt-0"><div class="small text-muted">Cicilan: <?php $inst = (array)($r['installments'] ?? []); if (empty($inst)) { echo '-'; } else { $chunks=[]; foreach ($inst as $it) { $chunks[] = html_escape((string)$it['due_period']) . ' (' . number_format((float)$it['paid_amount'], 2, ',', '.') . '/' . number_format((float)$it['plan_amount'], 2, ',', '.') . ')'; } echo implode(' | ', $chunks); } ?></div></td></tr>
<?php endforeach; endif; ?></tbody></table></div></div>
<?php endif; ?>
