<?php
$employee = $employee ?? null;
$employeeOptions = $employee_options ?? [];
$selectedEmployeeId = (int)($selected_employee_id ?? 0);
$filters = $filters ?? [];
$rows = $rows ?? [];
$pg = $pg ?? ['page' => 1, 'total_pages' => 1, 'per_page' => 25, 'total' => 0];
$statusOptions = $status_options ?? ['PENDING', 'APPROVED', 'REJECTED'];
$kindOptions = $kind_options ?? ['ADDITION', 'DEDUCTION'];
?>
<div class="d-flex justify-content-between align-items-center mb-3 flex-wrap gap-2">
  <div><h4 class="mb-0"><?php echo html_escape($title ?? 'Tambahan/Pengurangan Saya'); ?></h4><small class="text-muted">Riwayat adjustment manual yang mempengaruhi gaji harian.</small></div>
  <?php if (!empty($employeeOptions)): ?><form method="get" action="<?php echo site_url('my/manual-adjustments'); ?>" class="d-flex gap-2"><select name="employee_id" class="form-select form-select-sm" style="min-width:260px"><option value="">Pilih Pegawai (Preview Superadmin)</option><?php foreach($employeeOptions as $o): ?><option value="<?php echo (int)$o['value']; ?>" <?php echo ((int)$o['value'] === $selectedEmployeeId) ? 'selected' : ''; ?>><?php echo html_escape((string)$o['label']); ?></option><?php endforeach; ?></select><button type="submit" class="btn btn-sm btn-primary">Buka</button></form><?php endif; ?>
</div>
<?php if (!$employee): ?><div class="alert alert-warning">Data pegawai tidak ditemukan pada akun ini.</div><?php else: ?>
<div class="card mb-3"><div class="card-body"><form method="get" action="<?php echo site_url('my/manual-adjustments'); ?>" class="row g-2 align-items-end"><?php if ($selectedEmployeeId): ?><input type="hidden" name="employee_id" value="<?php echo $selectedEmployeeId; ?>"><?php endif; ?><div class="col-md-2"><label class="form-label mb-1">Status</label><select name="status" class="form-select"><option value="">Semua</option><?php foreach($statusOptions as $s): ?><option value="<?php echo html_escape($s); ?>" <?php echo (($filters['status'] ?? '') === $s) ? 'selected' : ''; ?>><?php echo html_escape($s); ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label mb-1">Jenis</label><select name="adjustment_kind" class="form-select"><option value="">Semua</option><?php foreach($kindOptions as $k): ?><option value="<?php echo html_escape($k); ?>" <?php echo (($filters['adjustment_kind'] ?? '') === $k) ? 'selected' : ''; ?>><?php echo $k === 'ADDITION' ? 'Tambahan' : 'Pengurangan'; ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label mb-1">Dari</label><input type="date" name="date_start" class="form-control" value="<?php echo html_escape((string)($filters['date_start'] ?? '')); ?>"></div><div class="col-md-2"><label class="form-label mb-1">Sampai</label><input type="date" name="date_end" class="form-control" value="<?php echo html_escape((string)($filters['date_end'] ?? '')); ?>"></div><div class="col-md-1"><label class="form-label mb-1">Per</label><select name="per_page" class="form-select"><?php foreach([10,25,50,100] as $p): ?><option value="<?php echo $p; ?>" <?php echo ((int)$pg['per_page'] === $p) ? 'selected' : ''; ?>><?php echo $p; ?></option><?php endforeach; ?></select></div><div class="col-md-3 d-flex gap-2"><button class="btn btn-primary" type="submit">Filter</button><a href="<?php echo site_url('my/manual-adjustments' . ($selectedEmployeeId ? ('?employee_id=' . $selectedEmployeeId) : '')); ?>" class="btn btn-outline-secondary">Reset</a></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th>Tanggal</th><th>Komponen</th><th>Jenis</th><th class="text-end">Nominal</th><th>Status</th><th>Catatan</th></tr></thead><tbody><?php if (empty($rows)): ?><tr><td colspan="6" class="text-center text-muted py-4">Belum ada data penyesuaian.</td></tr><?php else: foreach($rows as $r): $status=strtoupper((string)($r['status'] ?? 'PENDING')); ?><tr><td><?php echo html_escape((string)($r['adjustment_date'] ?? '-')); ?></td><td><?php echo html_escape((string)($r['adjustment_name'] ?? '-')); ?></td><td><span class="<?php echo strtoupper((string)($r['adjustment_kind'] ?? 'ADDITION')) === 'DEDUCTION' ? 'text-danger' : 'text-success'; ?> fw-semibold"><?php echo strtoupper((string)($r['adjustment_kind'] ?? 'ADDITION')) === 'DEDUCTION' ? 'Pengurangan' : 'Tambahan'; ?></span></td><td class="text-end fw-semibold"><?php echo number_format((float)($r['amount'] ?? 0), 2, ',', '.'); ?></td><td><span class="badge bg-<?php echo $status === 'APPROVED' ? 'success' : ($status === 'REJECTED' ? 'danger' : 'warning'); ?>"><?php echo html_escape($status); ?></span></td><td><?php echo html_escape((string)($r['notes'] ?? '-')); ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
<?php endif; ?>
