<?php
$setup=$result;$writable=!empty($can_setup)&&!empty($setup['schema_ready']);
?>
<div class="alert alert-info"><strong>Pengaturan ini hanya mengatur saran, bukan menjalankan transaksi.</strong> Jurnal yang sudah diposting tidak dihitung ulang. Kode dan kelompok akun existing tidak dapat diubah; nama akun dapat diperjelas dan perubahan dicatat di log.</div>
<?php if(empty($setup['schema_ready'])): ?><div class="alert alert-warning">Penyimpanan pengaturan belum aktif. Admin perlu menjalankan SQL 2026-09-15b. Panduan, saran bawaan dan jurnal manual tetap dapat digunakan.</div><?php endif; ?>
<?php if(empty($can_setup)): ?><p class="gl-muted">Mode baca saja. Minta pengelola memberi izin edit pada Pengaturan Akun Jurnal untuk mengubah pengaturan.</p><?php endif; ?>
<div class="gl-card"><h5>Jenis transaksi → akun yang disarankan</h5><p class="gl-muted">Pilih akun sesuai arti transaksi, bukan agar laporan tampak seimbang. “Bawaan” belum berarti sudah dikonfirmasi pengelola. Menonaktifkan saran tidak menonaktifkan jurnal manual.</p>
  <label class="d-block mb-3">Cari jenis transaksi<input class="form-control" type="search" data-gl-search="mapping" placeholder="Contoh: listrik, modal, utang, DP"></label>
  <div style="max-height:65vh;overflow:auto">
  <?php foreach($setup['mappings'] as $m): ?><details class="gl-card" data-gl-filter="mapping"><summary><?= $e($m['label']) ?> · <?= $e($m['direction']) ?> <span class="badge <?= $m['configured']?'bg-success':'bg-secondary' ?>"><?= $m['configured']?'Tersimpan':'Bawaan — belum dikonfirmasi' ?></span><?= !$m['is_enabled']?' · Saran nonaktif':'' ?></summary>
    <p class="gl-muted mt-2"><?= $e($m['help']) ?></p><?php if(!$m['valid']): ?><p class="text-danger">Akun saran tidak aktif/tidak sesuai. Pilih akun yang benar sebelum menggunakannya.</p><?php endif; ?>
    <form class="gl-setup-form gl-flex" data-kind="mapping">
      <input type="hidden" name="scenario_code" value="<?= $e($m['scenario_code']) ?>"><input type="hidden" name="expected_hash" value="<?= $e($m['hash']) ?>">
      <label>Akun <?= $e($typeLabels[$m['account_type']]) ?><select class="form-select" name="account_code" required <?= !$writable?'disabled':'' ?>><?php foreach($setup['accounts'] as $a): if(empty($a['is_active'])||!empty($a['is_cash'])||$a['account_type']!==$m['account_type']||in_array((string)$a['code'],['1100','1190'],true))continue; ?><option value="<?= $e($a['code']) ?>" <?= (string)$a['code']===$m['account_code']?'selected':'' ?>><?= $e($a['code'].' · '.$a['name']) ?></option><?php endforeach; ?></select></label>
      <label>Kelompok arus kas<select class="form-select" name="cashflow_class" <?= !$writable?'disabled':'' ?>><?php foreach(['OPERATING'=>'Operasi — kegiatan usaha','INVESTING'=>'Investasi — aset jangka panjang','FINANCING'=>'Pendanaan — modal/pokok pinjaman'] as $key=>$label): ?><option value="<?= $e($key) ?>" <?= $m['cashflow_class']===$key?'selected':'' ?>><?= $e($label) ?></option><?php endforeach; ?></select></label>
      <label>Saran<select class="form-select" name="is_enabled" <?= !$writable?'disabled':'' ?>><option value="1" <?= $m['is_enabled']?'selected':'' ?>>Aktif</option><option value="0" <?= !$m['is_enabled']?'selected':'' ?>>Nonaktif</option></select></label>
      <?php if($writable): ?><button type="submit" class="btn btn-primary">Simpan pemetaan</button><?php endif; ?>
    </form>
  </details><?php endforeach; ?></div>
</div>
<details class="gl-card"><summary>Daftar akun akuntansi (COA) — <?= count($setup['accounts']) ?> akun</summary><p class="gl-muted mt-2">Akun bukan rekening bank baru. Contoh: 5210 Beban Listrik adalah kelompok pencatatan, bukan tempat menyimpan uang. Awalan: 1 Aset, 2 Utang, 3 Ekuitas, 4 Pendapatan, 5 Beban. Akun kas 1100 dan perantara 1190 dilindungi.</p>
  <label class="d-block mb-3">Cari akun<input class="form-control" type="search" data-gl-search="account" placeholder="Kode atau nama akun"></label>
  <div style="max-height:65vh;overflow:auto"><?php foreach($setup['accounts'] as $a): $protected=!empty($a['is_cash'])||in_array((string)$a['code'],['1100','1190'],true); ?><details class="gl-card" data-gl-filter="account"><summary><?= $e($a['code'].' · '.$a['name']) ?> · <?= $e($typeLabels[$a['account_type']]??$a['account_type']) ?><?= empty($a['is_active'])?' · Nonaktif':'' ?></summary>
    <?php if($protected): ?><p class="gl-muted mt-2">Akun sistem dilindungi. Tidak dapat diganti/dinonaktifkan dari halaman ini.</p><?php else: ?><form class="gl-setup-form gl-flex mt-2" data-kind="account"><input name="code" type="hidden" value="<?= $e($a['code']) ?>"><input name="expected_hash" type="hidden" value="<?= $e($a['hash']) ?>"><label>Nama akun<input class="form-control" name="name" maxlength="150" value="<?= $e($a['name']) ?>" required <?= !$writable?'disabled':'' ?>></label><label>Status<select name="is_active" class="form-select" <?= !$writable?'disabled':'' ?>><option value="1" <?= $a['is_active']?'selected':'' ?>>Aktif</option><option value="0" <?= !$a['is_active']?'selected':'' ?>>Nonaktif</option></select></label><?php if($writable): ?><button class="btn btn-outline-primary">Simpan akun</button><?php endif; ?></form><?php endif; ?>
  </details><?php endforeach; ?></div>
  <?php if($writable): ?><h6 class="mt-3">Tambah akun nonkas</h6><form class="gl-setup-form gl-flex" data-kind="account"><input type="hidden" name="expected_hash" value="<?= $e(Finance_journal_assistant::account_hash(null)) ?>"><input type="hidden" name="is_active" value="1"><label>Kode baru<input class="form-control" name="code" pattern="[1-5][0-9]{3,9}" maxlength="10" placeholder="5210" required></label><label>Nama<input class="form-control" name="name" maxlength="150" placeholder="Beban Listrik" required></label><button class="btn btn-primary">Tambah akun</button></form><?php endif; ?>
  <p class="gl-muted mt-2">Akun yang sudah dipakai jurnal atau pemetaan aktif tidak dapat dinonaktifkan agar pembalikan tetap tersedia. Tidak tersedia hapus akun.</p>
</details>
