<?php
$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');
$money=static fn($c)=>number_format(((int)$c)/100,2,',','.');
$decimal=static fn($v)=>Finance_journal_policy::cents($v);
$month=(string)($month??date('Y-m'));
$url=static fn(array $p=[])=>site_url('finance-reports/accounting').'?'.http_build_query(array_merge(['month'=>$month],$p));
$tabs=['cash'=>'Arus Kas Aktual','queue'=>'Belum Dijurnal','journals'=>'Jurnal','ledger'=>'Buku Besar','trial'=>'Neraca Saldo','profit'=>'Laba-Rugi','balance'=>'Neraca','equity'=>'Perubahan Ekuitas','guide'=>'Panduan'];
if (!empty($can_view_setup))$tabs['settings']='Pengaturan Akun';
$flowLabels=['OPERATING'=>'Operasi','INVESTING'=>'Investasi','FINANCING'=>'Pendanaan','TRANSFER'=>'Transfer internal','UNCLASSIFIED'=>'Belum ditinjau / belum dijurnal'];
$typeLabels=['ASSET'=>'Aset','LIABILITY'=>'Liabilitas','EQUITY'=>'Ekuitas','INCOME'=>'Pendapatan','EXPENSE'=>'Beban'];
?>
<?php $this->load->view('finance/_tabs',get_defined_vars()); ?>
<style>
.gl-workspace{min-width:0}.gl-nav{display:flex;gap:.4rem;overflow:auto;padding:.5rem 0;margin-bottom:1rem}.gl-nav a{white-space:nowrap}.gl-card{border:1px solid #e5e7eb;border-radius:14px;padding:1rem;background:#fff;margin-bottom:1rem}.gl-stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(155px,1fr));gap:.8rem}.gl-stat{padding:1rem;border-radius:12px;background:#eef5ff;color:#15345d}.gl-stat:nth-child(2){background:#e8f7ef;color:#165d36}.gl-stat:nth-child(3){background:#fff0eb;color:#853a21}.gl-stat:nth-child(4){background:#f0edff;color:#453482}.gl-stat strong{display:block;font-size:1.25rem;overflow-wrap:anywhere}.gl-scroll{overflow:auto;max-width:100%}.gl-scroll table{min-width:680px;margin-bottom:0}.gl-lines select{min-width:210px}.gl-lines input{min-width:120px}.gl-flex{display:flex;gap:.75rem;flex-wrap:wrap;align-items:end}.gl-muted{color:#64748b;font-size:.9rem}.gl-workspace td,.gl-workspace th{vertical-align:middle}.gl-workspace .alert{overflow-wrap:anywhere}.gl-workspace .gl-note{max-width:850px}.gl-pager{display:flex;align-items:center;gap:1rem;margin:1rem 0}.gl-workspace input,.gl-workspace select{max-width:100%}
</style>
<style>.gl-workspace .gl-flex>label{min-width:0;max-width:100%}.gl-setup-form>label{flex:1 1 220px}.gl-workspace summary{overflow-wrap:anywhere;cursor:pointer}.gl-setup-form [data-gl-feedback]{flex-basis:100%;overflow-wrap:anywhere}</style>
<div class="gl-workspace" data-gl-url="<?= $e(site_url('finance-reports/accounting/post')) ?>" data-gl-home="<?= $e(site_url('finance-reports/accounting')) ?>" data-gl-setup="<?= $e(site_url('finance-reports/accounting/settings/')) ?>" data-gl-csrf="<?= $e($csrf) ?>">
  <div class="gl-flex mb-2"><div><h4 class="mb-1">Akuntansi dan Jurnal</h4><p class="gl-muted mb-0">Telusuri uang masuk–keluar, lalu susun laporan dari jurnal yang telah ditinjau.</p></div></div>
  <nav class="gl-nav" aria-label="Bagian akuntansi"><?php foreach($tabs as $key=>$label): ?><a class="btn btn-sm <?= $tab===$key?'btn-primary':'btn-outline-secondary' ?>" href="<?= $e($url(['tab'=>$key])) ?>"><?= $e($label) ?></a><?php endforeach; ?></nav>
  <?php if(!in_array($tab,['entry','guide','settings'],true)): ?>
  <form method="get" class="gl-card gl-flex"><input type="hidden" name="tab" value="<?= $e($tab) ?>"><label>Bulan laporan<input class="form-control" type="month" name="month" value="<?= $e($month) ?>" required></label>
    <?php if($tab==='cash'): ?><label>Mata uang<select class="form-select" name="currency"><?php foreach(array_unique(array_merge(['IDR'],$currencies)) as $c): ?><option <?= $currency===$c?'selected':'' ?> value="<?= $e($c) ?>"><?= $e($c) ?></option><?php endforeach; ?></select></label><?php endif; ?>
    <?php if($tab==='ledger'): ?><label>Akun buku besar<select class="form-select" name="code"><?php foreach($accounts as $code=>$a): ?><option value="<?= $e($code) ?>" <?= ($result['code']??'1100')===(string)$code?'selected':'' ?>><?= $e($code.' · '.$a['name']) ?></option><?php endforeach; ?></select></label><?php endif; ?>
    <button class="btn btn-primary">Tampilkan</button>
    <?php if($can_post && $ready): ?><a class="btn btn-outline-primary" href="<?= $e($url(['tab'=>'entry','kind'=>$opening?'ADJUSTMENT':'OPENING','date'=>$opening?date('Y-m-d'):date('Y-m-d',strtotime($month.'-01 -1 day'))])) ?>"><?= $opening?'Jurnal penyesuaian nonkas':'Siapkan saldo awal' ?></a><?php endif; ?>
  </form><?php endif; ?>
  <div id="gl-message" role="alert" aria-live="polite"></div>
  <?php if($error): ?><div class="alert alert-warning"><?= $e($error) ?></div>
  <?php elseif($tab==='cash'): $r=$result; ?>
    <div class="gl-stats mb-3"><?php foreach(['opening'=>'Saldo awal bulan','inflow'=>'Kas masuk (termasuk transfer)','outflow'=>'Kas keluar (termasuk transfer)','closing'=>'Saldo akhir dari mutasi'] as $key=>$label): ?><div class="gl-stat"><?= $e($label) ?><strong><?= $e($currency).' '.$money($r['total'][$key]) ?></strong></div><?php endforeach; ?></div>
    <div class="alert alert-info">Saldo awal + semua kas masuk − semua kas keluar = saldo akhir. Termasuk purchase, sales, mutasi manual, pinjaman, payroll, DP dan pembalikan sesuai tanggalnya. Ini bukan angka laba. Rekening nonaktif tetap disertakan.</div>
    <?php if($r['mismatch']): ?><div class="alert alert-warning"><?= (int)$r['mismatch'] ?> rekening mempunyai selisih saldo tersimpan saat ini terhadap seluruh riwayat. Bukan otomatis biaya; telusuri saldo awal dan riwayat mutasi.</div><?php endif; ?>
    <div class="gl-card"><h5>Rekonsiliasi per rekening</h5><div class="gl-scroll"><table class="table"><thead><tr><th>Rekening</th><th>Awal bulan</th><th>Masuk</th><th>Keluar</th><th>Akhir bulan</th><th>Selisih saldo saat ini*</th></tr></thead><tbody>
      <?php foreach($r['rows'] as $row): ?><tr><td><?= $e($row['account_name']) ?><?= empty($row['is_active'])?' <span class="badge bg-secondary">Nonaktif</span>':'' ?><div class="gl-muted"><?= $e($row['account_type']) ?></div></td><?php foreach(['opening','inflow','outflow','closing','live_difference'] as $k): ?><td><?= $money($row[$k]) ?></td><?php endforeach; ?></tr><?php endforeach; ?>
      <?php if(!$r['rows']): ?><tr><td colspan="6">Belum ada rekening pada mata uang ini.</td></tr><?php endif; ?></tbody></table></div><p class="gl-muted mt-2">*Selisih saat ini membandingkan current balance dengan saldo awal rekening + seluruh mutasi, bukan saldo bulan lama. Rekening OTHER/EWALLET perlu ditinjau apakah termasuk kas/setara kas; mata uang tidak digabung tanpa kurs.</p></div>
    <div class="gl-card"><h5>Kelompok arus kas</h5><p class="gl-muted">Klasifikasi mengikuti jurnal yang ditinjau. Baris belum dijurnal tetap masuk angka kas di atas, tidak disembunyikan atau otomatis dianggap pendapatan/beban. Transfer internal ditampilkan terpisah, bukan arus eksternal usaha.</p><div class="gl-scroll"><table class="table"><thead><tr><th>Kelompok</th><th>Mutasi</th><th>Masuk</th><th>Keluar</th><th>Neto</th></tr></thead><tbody><?php foreach($r['groups'] as $g): ?><tr><td><?= $e($flowLabels[$g['flow_class']]??$g['flow_class']) ?></td><td><?= (int)$g['row_count'] ?></td><td><?= $money($g['inflow']) ?></td><td><?= $money($g['outflow']) ?></td><td><?= $money($g['inflow']-$g['outflow']) ?></td></tr><?php endforeach; ?></tbody></table></div><p class="gl-muted mt-2">Transfer neto yang tidak nol perlu ditelusuri kedua sisi/tanggalnya, bukan dimasukkan ke laba. Transaksi nonkas tidak masuk arus kas.</p></div>
  <?php elseif($tab==='queue'): ?>
    <div class="alert alert-info">Jurnalkan mutasi setelah tanggal saldo awal. Penerimaan penjualan bisa memuat pajak/DP/pelunasan piutang; pembayaran purchase bisa berupa persediaan, aset atau pelunasan utang. Pilih akun lawan berdasarkan dokumen.</div>
    <?php if(!$opening): ?><div class="alert alert-warning">Siapkan saldo awal sebelum mulai menjurnal. Tidak ada transaksi historis yang otomatis diposting.</div><?php endif; ?>
    <div class="gl-card gl-scroll"><table class="table"><thead><tr><th>Tanggal / nomor</th><th>Rekening / sumber</th><th>Arah</th><th>Nominal</th><th>Tindakan</th></tr></thead><tbody><?php foreach($result['rows'] as $row): ?><tr><td><?= $e($row['mutation_date']) ?><div><?= $e($row['mutation_no']) ?></div></td><td><?= $e($row['account_name']) ?><div class="gl-muted"><?= $e($row['ref_module']) ?><?= !empty($row['reversal_of_mutation_id'])?' · Pembalikan':'' ?></div></td><td><?= $e($row['mutation_type']) ?></td><td><?= $money($decimal($row['amount'])) ?></td><td><?php if($can_post): ?><a class="btn btn-sm btn-outline-primary" href="<?= $e($url(['tab'=>'entry','kind'=>'MUTATION','source_id'=>$row['id']])) ?>">Tinjau &amp; jurnal</a><?php endif; ?></td></tr><?php endforeach; ?><?php if(!$result['rows']): ?><tr><td colspan="5">Tidak ada antrean pada filter ini. Bukan bukti seluruh akrual sudah lengkap.</td></tr><?php endif; ?></tbody></table></div>
  <?php elseif($tab==='entry'): $r=$result; ?>
    <div class="gl-card"><h5><?= $r['kind']==='OPENING'?'Saldo awal pembukuan':($r['kind']==='MUTATION'?'Jurnal dari mutasi kas':'Jurnal penyesuaian nonkas') ?></h5>
      <p class="gl-muted">Posting jurnal hanya mencatat akuntansi, tidak menambah/mengurangi saldo kas lagi. Nilai sudah diposting tidak bisa dihapus/ditimpa. Koreksi akun memakai penyesuaian nonkas dengan referensi jurnal asal.</p>
      <?php if($r['warning']): ?><div class="alert alert-warning"><?= $e($r['warning']) ?></div><?php endif; ?>
      <?php if($r['kind']==='OPENING'): ?><form method="get" class="gl-flex mb-3"><input type="hidden" name="tab" value="entry"><input type="hidden" name="kind" value="OPENING"><label>Tanggal saldo awal<input type="date" class="form-control" name="date" value="<?= $e($r['date']) ?>" required></label><button class="btn btn-outline-primary">Perbarui pratinjau saldo kas</button></form><?php endif; ?>
      <?php if($r['source']): ?><p><?= $e($r['source']['mutation_no'].' · '.$r['source']['account_name'].' · '.$r['source']['mutation_type']) ?> <strong><?= $money($decimal($r['source']['amount'])) ?></strong></p><?php endif; ?>
      <form id="gl-entry" data-kind="<?= $e($r['kind']) ?>" data-auto-counter="<?= $r['auto_counter']?'1':'0' ?>" data-source="<?= (int)($r['source']['id']??0) ?>" data-hash="<?= $e($r['source_hash']) ?>" data-key="<?= bin2hex(random_bytes(16)) ?>">
        <?php if(!empty($r['assistant_options'])): ?><section class="gl-card" aria-label="Asisten memilih akun jurnal"><h6>1. Uang ini untuk apa?</h6><p class="gl-muted">Pilih hanya jika seluruh nominal sesuai satu jenis transaksi. Untuk campuran pajak/bunga/beberapa kelompok, gunakan baris manual. Tidak ada posting otomatis.</p>
          <label class="d-block">Jenis transaksi<select id="gl-assistant-choice" class="form-select"><option value="">Saya memilih akun secara manual</option><?php foreach($r['assistant_options'] as $choice): ?><option value="<?= $e($choice['scenario_code']) ?>" data-account="<?= $e($choice['account_code']) ?>" data-flow="<?= $e($choice['cashflow_class']) ?>" data-hash="<?= $e($choice['hash']) ?>" data-help="<?= $e($choice['help']) ?>" data-direction="<?= $e($choice['direction']) ?>" data-configured="<?= $choice['configured']?'1':'0' ?>"><?= $e($choice['label']) ?></option><?php endforeach; ?></select></label>
          <p id="gl-assistant-explanation" class="gl-muted mt-2" aria-live="polite">Pilih jenis transaksi, periksa penjelasannya, lalu gunakan sarannya.</p><label class="d-block mb-2"><input type="checkbox" id="gl-assistant-confirm"> Saya sudah memeriksa bukti dan memastikan transaksi ini belum diakui dua kali.</label><button type="button" class="btn btn-outline-primary" id="gl-assistant-apply">2. Isi baris sesuai saran</button><p id="gl-assistant-state" class="gl-muted mt-2" aria-live="polite">Belum memakai saran. Posting tetap memerlukan konfirmasi Anda.</p></section><?php endif; ?>
        <div class="gl-flex mb-3"><label>Tanggal jurnal<input type="date" name="date" class="form-control" value="<?= $e($r['date']) ?>" <?= $r['kind']!=='ADJUSTMENT'?'readonly':'' ?> required></label><label>Referensi dokumen<input name="reference" class="form-control" maxlength="120" value="<?= $e($r['source']['mutation_no']??'') ?>" placeholder="Nomor bukti / jurnal asal" required></label>
        <?php if($r['kind']==='MUTATION'): ?><label>Kelompok arus kas<select name="cashflow_class" class="form-select" required><option value="">Pilih sesuai dokumen</option><?php foreach(array_diff_key($flowLabels,['UNCLASSIFIED'=>true]) as $k=>$label): ?><option value="<?= $e($k) ?>" <?= $r['flow']===$k?'selected':'' ?>><?= $e($label) ?></option><?php endforeach; ?></select></label><?php endif; ?></div>
        <label class="d-block mb-3">Keterangan / dasar pengakuan<textarea name="memo" class="form-control" maxlength="500" required rows="2" placeholder="Jelaskan dokumen, akun dan alasan pencatatan"></textarea></label>
        <div class="gl-scroll"><table class="table gl-lines"><thead><tr><th>Akun akuntansi</th><th>Debit</th><th>Kredit</th><th></th></tr></thead><tbody id="gl-lines">
          <?php foreach($r['fixed'] as $line): ?><tr data-fixed-debit="<?= $e($line['debit']) ?>" data-fixed-credit="<?= $e($line['credit']) ?>"><td><?= $e($line['account_code'].' · '.($accounts[$line['account_code']]['name']??'Akun sumber')) ?><?= isset($line['account_name'])?' · '.$e($line['account_name']):'' ?><div class="gl-muted">Otomatis dari sumber, tidak dapat diubah</div></td><td><?= $money($decimal($line['debit'])) ?></td><td><?= $money($decimal($line['credit'])) ?></td><td></td></tr><?php endforeach; ?>
        </tbody><tfoot><tr><th>Total</th><th id="gl-debit">0,00</th><th id="gl-credit">0,00</th><th id="gl-difference"></th></tr></tfoot></table></div>
        <div class="gl-flex mt-3"><button type="button" class="btn btn-outline-secondary" id="gl-add" <?= $r['auto_counter']?'hidden':'' ?>>Tambah baris nonkas</button><button class="btn btn-primary" type="submit">Posting jurnal</button></div>
        <p class="gl-muted mt-2">Gunakan angka tanpa pemisah ribuan, desimal titik (contoh 12500.50). Transfer memakai akun perantara otomatis. Pembalikan kas yang asalnya sudah dijurnal mengikuti akun jurnal asal, bukan pilihan baru di formulir.</p>
      </form>
      <template id="gl-line-template"><tr data-edit-line><td><select class="form-select" data-code required><option value="">Pilih akun lawan</option><?php foreach($accounts as $code=>$a): if(!empty($a['is_cash'])||empty($a['is_active']))continue; ?><option value="<?= $e($code) ?>"><?= $e($code.' · '.$a['name'].' ('.($typeLabels[$a['account_type']]??$a['account_type']).')') ?></option><?php endforeach; ?></select></td><td><input class="form-control" inputmode="decimal" data-debit value="0" aria-label="Debit"></td><td><input class="form-control" inputmode="decimal" data-credit value="0" aria-label="Kredit"></td><td><button class="btn btn-sm btn-outline-danger" type="button" data-remove aria-label="Hapus baris">×</button></td></tr></template>
      <div id="gl-suggestion" data-code="<?= $e($r['suggestion']??'') ?>" data-direction="<?= $e($r['source']['mutation_type']??'') ?>" data-amount="<?= $e($r['source']['amount']??'0') ?>"></div>
    </div>
  <?php elseif($tab==='journals'): ?>
    <div class="gl-card gl-scroll"><table class="table"><thead><tr><th>Jurnal</th><th>Tanggal</th><th>Jenis / referensi</th><th>Debit = kredit</th><th></th></tr></thead><tbody><?php foreach($result['rows'] as $row): ?><tr><td>GL-<?= (int)$row['id'] ?></td><td><?= $e($row['journal_date']) ?></td><td><?= $e($row['kind'].' · '.$row['reference']) ?></td><td><?= $money($decimal($row['total']??'0')) ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= $e($url(['tab'=>'journals','id'=>$row['id']])) ?>">Rincian</a></td></tr><?php endforeach; ?><?php if(!$result['rows']): ?><tr><td colspan="5">Belum ada jurnal pada bulan ini.</td></tr><?php endif; ?></tbody></table></div>
    <?php if($result['detail']): $j=$result['detail']; ?><div class="gl-card"><h5>GL-<?= (int)$j['id'] ?> · <?= $e($j['reference']) ?></h5><p><?= $e($j['memo']) ?></p><p class="gl-muted">Tanggal <?= $e($j['journal_date']) ?> · pengguna #<?= (int)$j['created_by'] ?> · dicatat <?= $e($j['created_at']) ?><?= !empty($j['reversal_of'])?' · pembalik GL-'.(int)$j['reversal_of']:'' ?></p><div class="gl-scroll"><table class="table"><thead><tr><th>Akun</th><th>Rekening</th><th>Debit</th><th>Kredit</th></tr></thead><tbody><?php foreach($result['lines'] as $line): ?><tr><td><?= $e($line['account_code'].' · '.$line['name']) ?></td><td><?= $e($line['account_name']??'—') ?></td><td><?= $money($decimal($line['debit'])) ?></td><td><?= $money($decimal($line['credit'])) ?></td></tr><?php endforeach; ?></tbody></table></div>
      <?php if($can_post&&$j['kind']==='ADJUSTMENT'): ?><form id="gl-reverse" class="gl-flex mt-3" data-id="<?= (int)$j['id'] ?>" data-key="<?= bin2hex(random_bytes(16)) ?>"><label>Tanggal pembalik<input class="form-control" type="date" name="date" value="<?= date('Y-m-d') ?>" required></label><label>Alasan pembalikan<input class="form-control" name="memo" maxlength="500" required></label><button class="btn btn-outline-danger">Buat jurnal pembalik</button></form><?php endif; ?></div><?php endif; ?>
  <?php elseif($tab==='ledger'): ?>
    <div class="gl-card"><h5>Saldo awal periode (debit − kredit): <?= $money($result['opening']) ?></h5><div class="gl-scroll"><table class="table"><thead><tr><th>Tanggal / jurnal</th><th>Referensi / keterangan</th><th>Rekening</th><th>Debit</th><th>Kredit</th></tr></thead><tbody><?php foreach($result['rows'] as $row): ?><tr><td><?= $e($row['journal_date']) ?><div><a href="<?= $e($url(['tab'=>'journals','id'=>$row['journal_id']])) ?>">GL-<?= (int)$row['journal_id'] ?></a></div></td><td><?= $e($row['reference']) ?><div class="gl-muted"><?= $e($row['memo']) ?></div></td><td><?= $e($row['account_name']??'—') ?></td><td><?= $money($decimal($row['debit'])) ?></td><td><?= $money($decimal($row['credit'])) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
  <?php elseif(in_array($tab,['trial','profit','balance','equity'],true)): $s=$result['sum']; ?>
    <div class="alert alert-warning"><strong>Draf laporan berbasis jurnal · IDR</strong><ul class="mb-0"><?php foreach($result['warnings'] as $warning): ?><li><?= $e($warning) ?></li><?php endforeach; ?></ul></div>
    <?php if($result['cashDifference']): ?><details class="gl-card"><summary>Rincian selisih kas buku besar vs mutasi</summary><?php foreach($result['cashDifference'] as $d): ?><p class="mb-1"><?= $e($d['name']) ?>: <?= $money($d['difference']) ?></p><?php endforeach; ?></details><?php endif; ?>
    <div class="gl-card"><h5><?= $e($tabs[$tab]) ?> · <?= $e($month) ?></h5>
    <?php if($tab==='trial'): ?><div class="gl-scroll"><table class="table"><thead><tr><th>Akun</th><th>Awal D−K</th><th>Debit periode</th><th>Kredit periode</th><th>Saldo debit</th><th>Saldo kredit</th></tr></thead><tbody><?php foreach($result['rows'] as $row): ?><tr><td><?= $e($row['code'].' · '.$row['name']) ?></td><td><?= $money($row['opening']) ?></td><td><?= $money($row['debit']) ?></td><td><?= $money($row['credit']) ?></td><td><?= $money(max(0,$row['closing'])) ?></td><td><?= $money(max(0,-$row['closing'])) ?></td></tr><?php endforeach; ?></tbody></table></div><p class="mt-2">Selisih neraca saldo: <strong><?= $money($s['trial_difference']) ?></strong></p>
    <?php elseif($tab==='profit'): ?><table class="table"><tbody><?php foreach($result['rows'] as $row): if(!in_array($row['account_type'],['INCOME','EXPENSE'],true))continue; ?><tr><td><?= $e($row['name']) ?></td><td class="text-end"><?= $money($row['account_type']==='INCOME'?$row['credit']-$row['debit']:$row['debit']-$row['credit']) ?></td></tr><?php endforeach; ?><tr><th>Laba / rugi periode</th><th class="text-end"><?= $money($s['profit']) ?></th></tr></tbody></table>
    <?php elseif($tab==='balance'): ?><table class="table"><tbody><?php foreach(['ASSET','LIABILITY','EQUITY'] as $type): ?><tr><th colspan="2"><?= $e($typeLabels[$type]) ?></th></tr><?php foreach($result['rows'] as $row): if($row['account_type']!==$type)continue; ?><tr><td><?= $e($row['name']) ?></td><td class="text-end"><?= $money($type==='ASSET'?$row['closing']:-$row['closing']) ?></td></tr><?php endforeach; ?><?php endforeach; ?><tr><td>Laba akumulasi sebelum periode (belum ditutup)</td><td class="text-end"><?= $money($s['prior_earnings']) ?></td></tr><tr><td>Laba/rugi periode berjalan</td><td class="text-end"><?= $money($s['profit']) ?></td></tr><tr><th>Total aset</th><th class="text-end"><?= $money($s['assets']) ?></th></tr><tr><th>Total liabilitas + ekuitas termasuk laba</th><th class="text-end"><?= $money($s['liabilities']+$s['total_equity']) ?></th></tr><tr><th>Selisih persamaan neraca</th><th class="text-end"><?= $money($s['balance_difference']) ?></th></tr></tbody></table>
    <?php else: ?><table class="table"><tbody><?php foreach(['Ekuitas awal termasuk laba sebelumnya'=>$s['opening_equity']+$s['prior_earnings'],'Perubahan akun ekuitas (modal/prive/penyesuaian)'=>$s['capital_movement'],'Laba/rugi periode'=>$s['profit'],'Ekuitas akhir'=>$s['total_equity']] as $label=>$n): ?><tr><td><?= $e($label) ?></td><td class="text-end"><?= $money($n) ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
  <?php elseif($tab==='settings'): ?>
    <?php $this->load->view('finance/accounting_settings',get_defined_vars()); ?>
  <?php elseif($tab==='guide'): ?>
    <?php $this->load->view('finance/accounting_guide',get_defined_vars()); ?>
    <details class="gl-card"><summary>Ringkasan alur teknis dan batas modul</summary>
    <div class="gl-card gl-note"><h5>Mulai dari mana?</h5><ol><li>Buka <strong>Arus Kas Aktual</strong>. Pilih bulan/mata uang, telusuri selisih saldo per rekening. Semua IN/OUT tetap tampil, termasuk di luar sales/purchase.</li><li>Setelah SQL aktif, tentukan tanggal mulai pembukuan. Klik <strong>Siapkan saldo awal</strong> pada hari sebelumnya. Kas diisi dari mutasi; lengkapi persediaan, piutang, aset, utang dan ekuitas berdasarkan bukti. Jangan menebak akun penyeimbang.</li><li>Buka <strong>Belum Dijurnal</strong>. Tinjau tiap mutasi dan pilih akun lawan serta kelompok operasi/investasi/pendanaan. Satu kas masuk bisa dibagi kredit penjualan, utang pajak dan DP sesuai dokumen.</li><li>Tambahkan <strong>jurnal penyesuaian nonkas</strong> untuk pengakuan penjualan kredit, HPP, gaji terutang dan penyusutan. Misalnya HPP: debit HPP, kredit Persediaan. Jangan menjurnal ulang pengakuan yang sudah dicatat.</li><li>Periksa neraca saldo, laba-rugi, neraca dan perubahan ekuitas. Antrean kosong dan debit=kredit belum membuktikan seluruh akrual/dokumen lengkap. Penanggung jawab keuangan harus meninjau sebelum penerbitan.</li></ol>
      <h6>Koreksi tanpa menghilangkan jejak</h6><p>Jurnal sudah diposting tidak diedit/dihapus. Jurnal penyesuaian nonkas dapat dibalik lewat Rincian Jurnal lalu dibuat ulang. Untuk salah akun pada jurnal kas, buat penyesuaian nonkas dengan referensi GL asal; nominal kas tetap. Jika transaksi kasnya salah, VOID/koreksi melalui modul asal dan jurnalkan mutasi pembalik yang muncul.</p>
      <h6>Batas yang perlu diketahui</h6><p>Jurnal tahap ini IDR, ditinjau manual, bukan auto-post seluruh sales/purchase/payroll. Belum mencakup otomatisasi pengakuan akrual, catatan laporan, persetujuan penerbitan atau penutupan tahun akuntansi. Tutup periode aplikasi yang sudah ada tetap mengunci tanggal posting. Perubahan sumber historis ditandai, tidak diam-diam mengubah jurnal.</p>
      <p>Rancangan mengacu pemisahan arus operasi/investasi/pendanaan pada <a href="https://www.ifrs.org/issued-standards/list-of-standards/ias-7-statement-of-cash-flows/" target="_blank" rel="noopener noreferrer">IAS 7</a> dan komponen penyajian pada <a href="https://www.ifrs.org/issued-standards/list-of-standards/ias-1-presentation-of-financial-statements/" target="_blank" rel="noopener noreferrer">IAS 1</a>. Ini fondasi pencatatan, bukan klaim kepatuhan penuh SAK/IFRS.</p>
    </div></details>
  <?php endif; ?>
  <?php if(!$error&&in_array($tab,['queue','journals','ledger'],true)): $per=$tab==='ledger'?50:25;$page=(int)$result['page'];$pages=max(1,(int)ceil($result['count']/$per)); ?><nav class="gl-pager" aria-label="Halaman data"><span><?= (int)$result['count'] ?> baris · halaman <?= $page ?> / <?= $pages ?></span><?php foreach([-1=>'Sebelumnya',1=>'Berikutnya'] as $step=>$label): if($page+$step<1||$page+$step>$pages)continue; ?><a class="btn btn-sm btn-outline-secondary" href="<?= $e($url(['tab'=>$tab,'page'=>$page+$step,'code'=>$result['code']??'1100'])) ?>"><?= $e($label) ?></a><?php endforeach; ?></nav><?php endif; ?>
</div>
<script src="<?= $e(base_url('assets/js/finance-accounting.js')) ?>" defer></script>
