<?php
$esc=static fn($v)=>html_escape((string)$v);
$money=static fn($v)=>'Rp '.number_format((float)$v,2,',','.');
$labels=['settlement'=>'1. Settlement','quality'=>'2. Kualitas laporan','cash-plan'=>'3. Proyeksi kas','profit-loss'=>'4. Laba-rugi HPP'];
if (!empty($operations_ready)) $labels+=['approvals'=>'5. Persetujuan','settings'=>'6. Pengaturan'];
if (!empty($allocation_ready)) $labels+=['bank-review'=>'7. Cocokkan bank'];
$r=(array)$result;
$json=static fn($v)=>json_encode($v,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_INVALID_UTF8_SUBSTITUTE);
?>
<style>
.fc-wrap{max-width:1280px;margin:auto;padding:20px;--fc-ink:#24344a}.fc-wrap h2,.fc-wrap h3{color:var(--fc-ink)}.fc-wrap h3{font-size:1.15rem}.fc-tabs{display:flex;gap:8px;overflow:auto;margin:20px 0}.fc-tabs a{white-space:nowrap;border:1px solid #d7dfe9;padding:10px 16px;border-radius:12px;color:#334155;text-decoration:none}.fc-tabs a.active{background:#253850;color:white}.fc-panel{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:20px;margin-bottom:18px}.fc-filter{display:flex;align-items:end;gap:12px;flex-wrap:wrap;margin-bottom:18px}.fc-filter label{display:block;font-size:.85rem}.fc-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin-bottom:20px}.fc-stat{padding:18px;border-radius:14px;background:#eaf2fb;border-top:4px solid #3b82b6;min-width:0}.fc-stat:nth-child(2){background:#e7f5ef;border-color:#268861}.fc-stat:nth-child(3){background:#fff4df;border-color:#c68a23}.fc-stat:nth-child(4){background:#f1ecfc;border-color:#8661bc}.fc-stat small{display:block;color:#455569}.fc-stat strong{display:block;font-size:1.2rem;margin-top:8px;overflow-wrap:anywhere}.fc-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.fc-form label{display:block;font-size:.9rem}.fc-form .wide{grid-column:1/-1}.fc-scroll{overflow:auto}.fc-table{width:100%;font-size:.9rem}.fc-table th,.fc-table td{padding:11px;border-bottom:1px solid #e6ebf2;text-align:left}.fc-table .num{text-align:right;white-space:nowrap}.fc-muted{color:#64748b;font-size:.86rem}.fc-note{border-left:4px solid #deac46;background:#fffbec;padding:12px 16px;margin-bottom:16px}.fc-status{display:inline-block;background:#edf2f7;padding:5px 10px;border-radius:8px;font-size:.85rem}.fc-alert{position:sticky;top:12px;z-index:10}.fc-edit{margin:4px 0}.fc-row-total{background:#edf5f1;font-weight:bold}.fc-negative{color:#b42318}.fc-wrap button{min-height:40px}.fc-wrap select{max-width:100%}.fc-wrap details summary{cursor:pointer;font-weight:600;padding:8px 0}.fc-chartbar{display:block;height:7px;border-radius:4px;background:#36886b;margin-top:5px}.fc-chartbar.negative{background:#d26754}@media(max-width:700px){.fc-wrap{padding:12px}.fc-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.fc-form{grid-template-columns:1fr}.fc-panel{padding:14px}.fc-table{min-width:570px}.fc-stat{padding:12px}.fc-stat strong{font-size:1rem}.fc-filter>div{flex:1 1 140px}}
.fc-wrap{font-family:system-ui,-apple-system,"Segoe UI",sans-serif}.fc-wrap input,.fc-wrap select,.fc-wrap textarea,.fc-wrap button{font-family:inherit}.fc-wrap h2{font-size:clamp(1.5rem,3vw,2rem)}
</style>
<div class="page-wrapper"><main class="fc-wrap">
<?php $this->load->view('finance/_tabs',['finance_tab_active'=>'control']); ?>
<div class="d-flex justify-content-between align-items-start gap-3"><div><h2>Kontrol Keuangan</h2><p class="fc-muted">Telusuri dana, periksa kualitas angka, lalu rencanakan kas. Tanpa perbaikan transaksi otomatis.</p></div><span class="fc-status">IDR</span></div>
<nav class="fc-tabs" aria-label="Bagian kontrol keuangan"><?php foreach($labels as $key=>$label): ?><a class="<?= $tab===$key?'active':'' ?>" <?= $tab===$key?'aria-current="page"':'' ?> href="<?= site_url('finance-reports/control?tab='.$key) ?>"><?= $esc($label) ?></a><?php endforeach; ?></nav>
<div id="fc-message" class="alert fc-alert d-none" role="status" aria-live="polite"></div>
<?php if(!in_array($tab,['approvals','settings'],true)): ?><form method="get" class="fc-filter"><input type="hidden" name="tab" value="<?= $esc($tab) ?>">
<?php if($tab==='settlement'): ?><div><label for="fc-date">Tanggal pembayaran / refund POS</label><input class="form-control" id="fc-date" type="date" name="date" value="<?= $esc($date) ?>" max="<?= date('Y-m-d') ?>" required></div><div><label for="fc-method">Metode pembayaran</label><select id="fc-method" class="form-select" name="method_id"><?php foreach($methods as $m): ?><option value="<?= (int)$m['id'] ?>" <?= (int)$m['id']===$method_id?'selected':'' ?>><?= $esc($m['method_name'].' · '.$m['account_name']) ?></option><?php endforeach; ?></select></div>
<?php elseif($tab==='cash-plan'): ?><div><label for="fc-days">Jangka proyeksi</label><select id="fc-days" class="form-select" name="days"><option value="7" <?= $days===7?'selected':'' ?>>7 hari</option><option value="30" <?= $days===30?'selected':'' ?>>30 hari</option></select></div>
<?php else: ?><div><label for="fc-month">Bulan laporan</label><input id="fc-month" class="form-control" type="month" name="month" value="<?= $esc($month) ?>" required></div><?php endif; ?><button class="btn btn-primary">Tampilkan</button></form><?php endif; ?>
<?php if($error): ?><div class="alert alert-warning"><?= $esc($error) ?></div>
<?php elseif($tab==='settlement'): $c=$r['case'];$trace=$r['trace']; ?>
<div class="fc-grid"><?php foreach([['POS dikurangi refund',$trace['expected_amount']],['Penyesuaian tercatat',$r['adjustment']],['Penerimaan dikonfirmasi',$r['received']],['Belum dijelaskan / cair',$r['remaining']]] as [$label,$value]): ?><div class="fc-stat"><small><?= $esc($label) ?></small><strong><?= $money($value) ?></strong></div><?php endforeach; ?></div>
<section class="fc-panel"><div class="d-flex justify-content-between gap-2 mb-3"><h3>Konfirmasi pencairan</h3><span class="fc-status"><?= $esc(str_replace('_',' ',$r['status'])) ?></span></div>
<div class="fc-note">Pembayaran sudah dicatat oleh POS. Tombol di bawah <b>hanya menyimpan konfirmasi</b>, tidak menambah saldo. <?php if(!empty($operations_ready)): ?>Buat rekap harian dahulu, kemudian catat setiap transfer pada <a href="#fc-receipts">Rincian transfer</a>. Total dihitung otomatis. Buat dokumen penyesuaian pada <a href="#fc-charges">Rincian biaya</a>.<?php else: ?>Isi total dana yang sudah diterima, bukan nominal transfer terakhir.<?php endif; ?></div>
<?php if($r['stale']): ?><div class="alert alert-warning">Pembayaran/refund berubah sejak konfirmasi terakhir. Tinjau sumber di bawah lalu simpan ulang sebelum posting penyesuaian.</div><?php endif; ?>
<?php if($can_edit): ?><form class="fc-form" data-save="settlement">
<?php foreach(['revenue_date'=>$date,'payment_method_id'=>$method_id,'revision'=>$c['revision']??0,'source_fingerprint'=>$trace['source_fingerprint']] as $key=>$value): ?><input type="hidden" name="<?= $key ?>" value="<?= $esc($value) ?>"><?php endforeach; ?>
<label>Nama / referensi rekap harian<input name="provider_reference" class="form-control" maxlength="80" placeholder="Contoh: PLATFORM-20260914" value="<?= $esc($c['provider_reference']??'') ?>" required></label>
<label>Tanggal perkiraan pencairan<input name="due_date" class="form-control" type="date" value="<?= $esc($c['due_date']??$date) ?>" min="<?= $esc($date) ?>" required></label>
<label>Total dana benar-benar diterima<input name="received_amount" class="form-control" type="number" step="0.01" min="0" max="999999999999.99" value="<?= $esc($c['received_amount']??0) ?>" <?= !empty($operations_ready)&&(!$c||!empty($c['receipt_mode']))?'readonly':'' ?> required><small class="fc-muted"><?= !empty($c['receipt_mode'])?'Dihitung dari konfirmasi awal + rincian transfer aktif.':'' ?></small></label>
<label>Status pencairan<select name="settlement_complete" class="form-select"><option value="0" <?= empty($c['settlement_complete'])?'selected':'' ?>>Belum / baru sebagian cair</option><option value="1" <?= !empty($c['settlement_complete'])?'selected':'' ?>>Seluruh batch sudah cair (biaya tetap diperiksa)</option></select></label>
<label class="wide">Catatan pemeriksaan / bukti transfer<textarea name="notes" class="form-control" maxlength="255" required><?= $esc($c['notes']??'') ?></textarea></label>
<div class="wide"><button class="btn btn-primary">Simpan konfirmasi, tanpa posting kas</button></div></form><?php else: ?><p>Hak akses Anda hanya melihat. Penerimaan terakhir: <?= $money($r['received']) ?> · <?= $esc($c['notes']??'Belum ada konfirmasi') ?></p><?php endif; ?>
<?php if($c): ?><p class="fc-muted mt-3">Referensi kontrol <b>#<?= (int)$c['id'] ?></b> · perubahan ke-<?= (int)$c['revision'] ?>. Untuk biaya tambahan yang belum dipotong POS, pilih referensi ini di <a href="<?= site_url('finance/mutations') ?>">Mutasi Rekening</a> atau <a href="<?= site_url('finance-reports/revenue-reconciliation?revenue_date='.$date) ?>">Rekon Pendapatan</a>. Setiap dokumen/baris biaya hanya boleh diposting sekali; beberapa biaya dengan kategori sama dapat memiliki identitas berbeda. Bila salah posting, buka rincian penyesuaian di bawah → Batalkan; setelah VOID, buat posting koreksi baru dari modul asal.</p><?php endif; ?>
</section>
<section class="fc-panel"><h3>Pembayaran sumber</h3><p class="fc-muted">Angka metode sudah setelah diskon/promo POS. Potongan di kolom terakhir adalah informasi satu pembayaran, bukan biaya baru; pada pembayaran campuran jangan menjumlahkan potongan header per metode.</p>
<div class="fc-scroll"><table class="fc-table"><thead><tr><th>Pembayaran / order</th><th>Jenis / waktu</th><th class="num">Nilai metode</th><th class="num">Diskon/promo/voucher/poin</th></tr></thead><tbody>
<?php foreach($r['payment_rows'] as $p): ?><tr><td><?= $esc($p['payment_no']) ?><?php if($p['order_id']): ?><br><a href="<?= site_url('pos/reports/sales-detail/'.(int)$p['order_id']) ?>">Order #<?= (int)$p['order_id'] ?></a><?php endif; ?></td><td><?= $esc($p['payment_type'].' · '.$p['paid_at']) ?></td><td class="num"><?= $money($p['amount']) ?></td><td class="num"><?= $money((float)$p['discount_amount']+(float)$p['promo_amount']+(float)$p['voucher_amount']+(float)$p['point_redeem_amount']+(float)$p['compliment_amount']) ?></td></tr><?php endforeach; ?>
<?php if(!$r['payment_rows']): ?><tr><td colspan="4">Tidak ada pembayaran pada filter ini.</td></tr><?php endif; ?></tbody></table></div>
<div class="d-flex gap-3 mt-3"><span>Halaman <?= (int)$r['page'] ?> / <?= (int)$r['pages'] ?></span><?php foreach([-1=>'Sebelumnya',1=>'Berikutnya'] as $step=>$label): $pg=$r['page']+$step;if($pg<1||$pg>$r['pages'])continue; ?><a href="?<?= $esc(http_build_query(['tab'=>$tab,'date'=>$date,'method_id'=>$method_id,'page'=>$pg])) ?>"><?= $label ?></a><?php endforeach; ?></div>
<details class="mt-3"><summary>Refund (<?= count($trace['refunds']) ?>) dan penyesuaian (<?= count($r['mutations']) ?>)</summary><div class="fc-scroll"><table class="fc-table"><thead><tr><th>Referensi</th><th>Keterangan</th><th class="num">Nominal</th></tr></thead><tbody>
<?php foreach($trace['refunds'] as $p): ?><tr><td><a href="<?= site_url('pos/reports/sales-detail/'.(int)$p['order_id']) ?>"><?= $esc($p['refund_no']) ?></a></td><td>Refund · <?= $esc($p['refunded_at']) ?></td><td class="num"><?= $money($p['refund_amount']) ?></td></tr><?php endforeach; ?>
<?php foreach($r['mutations'] as $m): ?><tr><td><a href="<?= $esc(site_url('finance/mutations?'.http_build_query(['account_id'=>$m['account_id'],'date_from'=>$m['mutation_date'],'date_to'=>$m['mutation_date'],'module_filter'=>$m['ref_module']]))) ?>"><?= $esc($m['mutation_no']) ?></a></td><td><?= $esc($m['ref_module'].' · '.Finance_mutation_policy::label($m['report_category']??'')) ?><?= $m['effective']?'':' · VOID / pembalikan (tidak dihitung)' ?>
<?php if($can_edit && $m['effective'] && !empty($can_void_modules[$m['ref_module']])): ?><details><summary>Batalkan penyesuaian ini</summary><form data-save="void-adjustment" data-confirm="Pembatalan <?= $esc($m['mutation_no']) ?> akan membuat mutasi pembalikan <?= $esc($money($m['amount'])) ?> dan mengubah saldo. Lanjutkan?">
<input type="hidden" name="mutation_id" value="<?= (int)$m['id'] ?>"><label class="small">Alasan pembatalan<input class="form-control" name="reason" maxlength="200" required></label><button class="btn btn-sm btn-outline-danger mt-2">VOID dengan audit</button></form><?php if(!empty($operations_ready)): ?><form data-save="approval-request" class="mt-2"><input type="hidden" name="action_code" value="VOID_ADJUSTMENT"><input type="hidden" name="target_id" value="<?= (int)$m['id'] ?>"><input name="reason" class="form-control" maxlength="255" placeholder="Alasan meminta persetujuan VOID" aria-label="Alasan persetujuan VOID" required><button class="btn btn-sm btn-outline-secondary mt-1">Ajukan persetujuan VOID (bila diwajibkan)</button></form><?php endif; ?></details><?php endif; ?>
</td><td class="num"><?= $esc($m['mutation_type']) ?> <?= $money($m['amount']) ?></td></tr><?php endforeach; ?></tbody></table></div></details></section>
<?php elseif($tab==='quality'): ?>
<div class="fc-note">Daftar ini membantu pemeriksaan, bukan perintah memperbaiki data otomatis. Jumlah pemeriksaan bisa merujuk transaksi yang sama; bukan jumlah unik kerugian.</div>
<section class="fc-panel"><h3>Pemeriksaan sumber laporan</h3><div class="fc-scroll"><table class="fc-table"><thead><tr><th>Pemeriksaan</th><th class="num">Temuan</th><th>Tindak lanjut</th></tr></thead><tbody><?php foreach($r['issues'] as $i): ?><tr><td><?= $esc($i['title']) ?><br><small class="fc-muted"><?= $esc($i['count']?$i['level']:'Tidak ada temuan pada cakupan ini') ?></small></td><td class="num <?= $i['count']?'fc-negative':'' ?>"><?= (int)$i['count'] ?></td><td><?= $esc($i['action']) ?><br><a href="<?= $esc(site_url($i['url'])) ?>">Buka sumber →</a></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php if($r['account_samples']): ?><section class="fc-panel"><h3>Rekening untuk ditelusuri (maksimal 20)</h3><p><?= $esc(implode(', ',array_column($r['account_samples'],'account_name'))) ?></p></section><?php endif; ?>
<?php elseif($tab==='cash-plan'): ?>
<div class="fc-grid"><?php foreach([['Saldo buku saat ini',$r['book']],['Settlement terlacak belum diterima',$r['pending']],['Saldo awal indikatif',$r['opening']],['Proyeksi akhir '.$days.' hari',$r['projected']]] as [$label,$value]): ?><div class="fc-stat"><small><?= $esc($label) ?></small><strong><?= $money($value) ?></strong></div><?php endforeach; ?></div>
<details class="fc-note"><summary>Proyeksi indikatif — baca dasar perhitungan dan <?= count($r['warnings']) ?> catatan</summary><?php foreach($r['warnings'] as $warning): ?><p class="mb-2"><?= $esc($warning) ?></p><?php endforeach; ?></details>
<section class="fc-panel"><h3>Pergerakan <?= (int)$days ?> hari</h3><p class="fc-muted">Komitmen = tagihan/rencana pasti. Proyeksi = komitmen + perkiraan. Jatuh tempo terlewat ditempatkan hari ini, bukan dianggap sudah dibayar.</p><div class="fc-scroll"><table class="fc-table"><thead><tr><th>Tanggal</th><th class="num">Rencana masuk</th><th class="num">Rencana keluar</th><th class="num">Saldo komitmen</th><th class="num">Saldo proyeksi</th></tr></thead><tbody><?php foreach($r['daily'] as $d): ?><tr><td><?= $esc($d['date']) ?></td><td class="num"><?= $money($d['in']) ?></td><td class="num"><?= $money($d['out']) ?></td><td class="num"><?= $money($d['committed']) ?></td><td class="num <?= $d['projected']<0?'fc-negative':'' ?>"><?= $money($d['projected']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<details class="mt-3"><summary>Rincian sumber proyeksi (<?= count($r['visible']) ?>)</summary><div class="fc-scroll"><table class="fc-table"><thead><tr><th>Sumber</th><th>Jadwal / kepastian</th><th class="num">Nominal</th></tr></thead><tbody><?php foreach($r['visible'] as $e): ?><tr><td><a href="<?= $esc(site_url($e['url'])) ?>"><?= $esc($e['label']) ?></a></td><td><?= $esc($e['date'].' · '.($e['certainty']==='COMMITTED'?'Komitmen':'Perkiraan').($e['overdue']?' · lewat tempo':'')) ?></td><td class="num"><?= $esc($e['direction']) ?> <?= $money($e['amount']) ?></td></tr><?php endforeach; ?></tbody></table></div></details></section>
<section class="fc-panel"><h3>Rencana manual</h3><p class="fc-muted">Hanya untuk kebutuhan yang belum ada dalam sumber otomatis. Selesai/batal tidak memposting kas. Semua penyimpanan memiliki riwayat audit.</p>
<?php if($can_edit): ?><form class="fc-form" data-save="cash-plan" id="fc-plan-form">
<input type="hidden" name="id" value="0"><input type="hidden" name="revision" value="0"><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>">
<label>Nama rencana<input class="form-control" name="title" maxlength="160" required></label><label>Jadwal<input class="form-control" name="due_date" type="date" value="<?= date('Y-m-d') ?>" required></label>
<label>Arah<select class="form-select" name="direction"><option value="OUT">Keluar</option><option value="IN">Masuk</option></select></label><label>Nominal<input class="form-control" name="amount" type="number" min="0.01" step="0.01" max="999999999999.99" required></label>
<label>Kepastian<select class="form-select" name="certainty"><option value="ESTIMATE">Perkiraan</option><option value="COMMITTED">Komitmen pasti</option></select></label><label>Status<select class="form-select" name="status"><option value="OPEN">Direncanakan</option><option value="DONE">Selesai manual (tanpa tautan)</option><option value="CANCELLED">Dibatalkan</option></select></label>
<label class="wide">Catatan / alasan perubahan<textarea class="form-control" name="notes" maxlength="255" required></textarea></label><div class="wide"><button class="btn btn-primary">Simpan rencana</button> <a class="btn btn-outline-secondary" href="?tab=cash-plan&days=<?= (int)$days ?>">Rencana baru</a></div></form><?php endif; ?>
<div class="fc-scroll mt-3"><table class="fc-table"><thead><tr><th>Rencana</th><th>Jadwal / status</th><th class="num">Nominal</th><th>Aksi</th></tr></thead><tbody><?php foreach($r['plans'] as $p): ?><tr><td><?= $esc($p['title']) ?></td><td><?= $esc($p['due_date'].' · '.($p['computed_status']??$p['status'])) ?></td><td class="num"><?= $esc($p['direction']) ?> <?= $money($p['amount']) ?></td><td><?php if($can_edit): ?><button type="button" class="btn btn-sm btn-outline-primary fc-edit" data-plan="<?= $esc($json($p)) ?>">Ubah rencana / batalkan</button><?php else: ?>Hanya lihat<?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php elseif($tab==='profit-loss'): $b=$r['basis'];$m=$r['m']; ?>
<div class="fc-grid"><?php foreach([['Penjualan bersih (tanpa pajak)',$b['net_sales']],['HPP diakui periode ini',$b['hpp']],['Margin kotor',$b['net_sales']-$b['hpp']],['Hasil operasional indikatif',$r['result']]] as [$label,$value]): ?><div class="fc-stat"><small><?= $esc($label) ?></small><strong><?= $money($value) ?></strong></div><?php endforeach; ?></div>
<section class="fc-panel"><h3>Jembatan dari transaksi ke hasil usaha</h3><p class="fc-muted"><?= (int)$b['order_count'] ?> order lunas di periode ini. Refund order lama masuk pada tanggal refund, bukan mengurangi ulang bulan penjualannya.</p><div class="fc-scroll"><table class="fc-table"><thead><tr><th>Komponen</th><th class="num">Nilai</th></tr></thead><tbody>
<?php foreach([['Tagihan saat penjualan (termasuk service/pembulatan)',$b['billing']],['Kurangi pajak penjualan',$b['tax']],['Kurangi refund periode ini',$b['refund']],['Penjualan bersih',$b['net_sales']],['HPP snapshot saat penjualan',$b['sale_hpp']],['Kurangi HPP yang dibalik oleh refund',$b['refund_hpp']],['Tambah koreksi HPP diakui periode ini',$b['correction']],['Kurangi pembalikan koreksi HPP',$b['reversal']],['HPP bersih',$b['hpp']],['Tambah pendapatan lain berkategori',$m['other_income_total']],['Kurangi biaya lain berkategori (termasuk promo/fee tambahan)',$m['other_expense_total']],['Kurangi beban payroll final',$r['salary']]] as [$label,$value]): ?><tr><td><?= $esc($label) ?></td><td class="num"><?= $money($value) ?></td></tr><?php endforeach; ?><tr class="fc-row-total"><td>Hasil operasional indikatif</td><td class="num"><?= $money($r['result']) ?></td></tr></tbody></table></div></section>
<div class="fc-note"><?php foreach($r['warnings'] as $warning): ?><p class="mb-2"><?= $esc($warning) ?></p><?php endforeach; ?><?php if(!$b['correction_ready']): ?><p>Koreksi HPP defisit belum dapat dibaca: periksa kesiapan schema.</p><?php endif; ?></div>
<?php endif; ?>
<?php if(!empty($operations_ready) && !$error): $this->load->view('finance/control_operations',['tab'=>$tab,'result'=>$r,'operation_details'=>$operation_details??[],'can_edit'=>$can_edit,'can_approve'=>$can_approve??false,'can_settings'=>$can_settings??false,'can_void_modules'=>$can_void_modules??[],'allocation_ready'=>$allocation_ready??false]); ?>
<?php if(!empty($allocation_ready)): $this->load->view('finance/control_allocations',['tab'=>$tab,'result'=>$r,'operation_details'=>$operation_details??[],'can_edit'=>$can_edit,'accounts'=>$accounts??[]]); ?>
<script src="<?= $esc(base_url('assets/js/finance-control-allocations.js')) ?>" defer></script>
<?php else: ?><div class="fc-note">Alokasi lintas rekap, pembagian rencana dan impor rekening koran belum aktif. SQL 2026-09-14c disiapkan untuk dijalankan admin melalui IDE. Alur lama tetap tersedia.</div><?php endif; ?>
<div id="fc-operations-config" data-base="<?= $esc(site_url('finance-reports/control/')) ?>" data-csrf="<?= $esc($csrf) ?>"></div><script src="<?= $esc(base_url('assets/js/finance-control-operations.js')) ?>" defer></script>
<?php endif; ?>
</main></div>
<script>
(() => {
  const message=document.getElementById('fc-message');
  const notify=(text,error=false)=>{message.textContent=text;message.className='alert fc-alert '+(error?'alert-danger':'alert-success');message.scrollIntoView({block:'nearest'});};
  document.querySelectorAll('form[data-save]').forEach(form=>form.addEventListener('submit',async event=>{
    event.preventDefault();if(form.dataset.busy==='1'||!form.reportValidity())return;
    if(form.dataset.confirm&&!window.confirm(form.dataset.confirm))return;
    const body=Object.fromEntries(new FormData(form));if('settlement_complete' in body)body.settlement_complete=body.settlement_complete==='1';
    form.dataset.busy='1';const button=form.querySelector('button');button.disabled=true;
    try{const response=await fetch(<?= $json(site_url('finance-reports/control/save/')) ?>+form.dataset.save,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Finance-Control-CSRF':<?= $json($csrf) ?>},body:JSON.stringify(body)});
      let data;try{data=await response.json();}catch(e){throw Error('Respons tidak dapat dibaca. Periksa sesi login lalu muat ulang; jangan mengulang posting kas.');}
      if(!response.ok||!data.ok)throw Error(data.message||'Penyimpanan ditolak.');notify(data.message);setTimeout(()=>location.reload(),1000);
    }catch(error){notify(error.message,true);button.disabled=false;form.dataset.busy='0';}
  }));
  document.querySelectorAll('[data-plan]').forEach(button=>button.addEventListener('click',()=>{
    const form=document.getElementById('fc-plan-form');if(!form||form.dataset.busy==='1')return;
    const data=JSON.parse(button.dataset.plan);for(const [key,value] of Object.entries(data)){const field=form.elements.namedItem(key);if(field)field.value=value??'';}
    const linked=(data.realizations||[]).some(row=>Number(row.active_mutation_id)>0);
    const done=form.querySelector('[name="status"] option[value="DONE"]');if(done)done.disabled=linked;
    if(linked&&form.elements.namedItem('status').value==='DONE')form.elements.namedItem('status').value='OPEN';
    form.scrollIntoView({behavior:'smooth',block:'center'});form.elements.namedItem('title').focus();
  }));
})();
</script>
