<?php
$esc=static fn($v)=>html_escape((string)$v);
$money=static fn($v)=>'Rp '.number_format((float)$v,2,',','.');
$json=static fn($v)=>json_encode($v,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_INVALID_UTF8_SUBSTITUTE);
$r=(array)$result;$c=$r['case']??[];$op=(array)($operation_details??[]);
$hidden=static function(array $fields)use($esc){foreach($fields as $key=>$value)echo '<input type="hidden" name="'.$esc($key).'" value="'.$esc($value).'">';};
$evidenceOptions=static function()use($op,$esc){echo '<option value="">Belum memilih bukti</option>';foreach($op['evidence']??[] as $e)echo '<option value="'.(int)$e['id'].'">#'.(int)$e['id'].' · '.$esc($e['original_name']).'</option>';};
?>
<?php if($tab==='settlement'): ?>
<section class="fc-panel"><details><summary>Cari settlement lama — seluruh riwayat</summary>
<form id="fc-history-search" class="fc-filter"><div><label>Nomor / metode / nama rekap<input class="form-control" name="q" maxlength="80"></label></div><div><label>Dari tanggal<input class="form-control" type="date" name="from"></label></div><div><label>Sampai tanggal<input class="form-control" type="date" name="to"></label></div><button class="btn btn-outline-primary">Cari</button></form>
<div id="fc-history-results" aria-live="polite"></div><div class="d-flex gap-2 mt-2"><button class="btn btn-sm btn-outline-secondary" type="button" data-history-page="-1">Sebelumnya</button><span id="fc-history-page"></span><button class="btn btn-sm btn-outline-secondary" type="button" data-history-page="1">Berikutnya</button></div>
</details></section>
<?php if($c): ?>
<section class="fc-panel" id="fc-receipts"><h3>Rincian transfer pencairan</h3>
<p class="fc-muted">Satu baris untuk satu transfer bank/platform. Total dihitung otomatis. Ini konfirmasi dana dari POS yang sudah dibukukan, <b>bukan pemasukan bank baru</b>.</p>
<div class="fc-note">Konfirmasi lama tanpa rincian: <?= $money(!empty($c['receipt_mode'])?$c['receipt_opening_amount']:$c['received_amount']) ?>. Nilai ini dipertahankan sebagai saldo konfirmasi awal; jangan masukkan lagi sebagai transfer baru. <?php if(empty($c['receipt_mode'])): ?>Jika nilai konfirmasi lama salah, koreksi total di formulir konfirmasi sebelum menambahkan transfer pertama.<?php endif; ?></div>
<?php if($can_edit): ?><form data-save="receipt" class="fc-form">
<?php $hidden(['settlement_id'=>$c['id'],'revision'=>$c['revision'],'request_key'=>bin2hex(random_bytes(16))]); ?>
<label>Tanggal transfer<input class="form-control" name="received_date" type="date" min="<?= $esc($c['revenue_date']) ?>" max="<?= date('Y-m-d') ?>" value="<?= date('Y-m-d') ?>" required></label>
<label>Nomor referensi transfer<input class="form-control" name="reference_no" maxlength="80" placeholder="Contoh: TRF-1409-001" required></label>
<label>Nominal transfer ini<input class="form-control" name="amount" type="number" step="0.01" min="0.01" max="999999999999.99" required></label>
<label>Bukti transfer<select class="form-select" name="evidence_id"><?php $evidenceOptions(); ?></select></label>
<label class="wide">Catatan<input class="form-control" name="notes" maxlength="255" required></label><div class="wide"><button class="btn btn-primary">Catat transfer, tanpa posting kas</button></div></form><?php endif; ?>
<div class="fc-scroll mt-3"><table class="fc-table"><thead><tr><th>Transfer / tanggal</th><th>Nominal</th><th>Status / koreksi</th></tr></thead><tbody><?php foreach($op['receipts']??[] as $receipt): ?><tr><td><?= $esc($receipt['reference_no']) ?><br><?= $esc($receipt['received_date']) ?><?php if($receipt['evidence_id']): ?><br><a href="<?= site_url('finance-reports/control/evidence/'.(int)$receipt['evidence_id']) ?>">Unduh bukti</a><?php endif; ?></td><td class="num"><?= $money($receipt['amount']) ?><?php if(!empty($receipt['distribution'])): ?><br><small>Nominal transfer penuh; pembagian per rekap ada di bawah.</small><?php endif; ?></td><td><?= $esc($receipt['status']) ?><?php if($can_edit && $receipt['status']==='ACTIVE'): ?><details><summary>Koreksi rincian ini</summary><form data-save="void-receipt" data-confirm="Batalkan seluruh transfer ini termasuk pembagiannya ke rekap lain? Total konfirmasi rekap terkait berkurang; saldo bank tidak berubah."><?php $hidden(['id'=>$receipt['id'],'revision'=>$c['revision'],'distribution_revision'=>$receipt['distribution']['revision']??0]); ?><input name="reason" class="form-control" maxlength="255" placeholder="Alasan wajib" aria-label="Alasan pembatalan transfer" required><button class="btn btn-sm btn-outline-danger mt-2">Batalkan rincian</button></form><small>Setelah dibatalkan, tambah rincian baru yang benar.</small></details><?php elseif($receipt['void_reason']): ?><br><?= $esc($receipt['void_reason']) ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="fc-panel" id="fc-charges"><h3>Identitas biaya / penyesuaian</h3><p class="fc-muted">Boleh beberapa biaya dengan kategori sama. Bedakan <b>nomor dokumen + baris biaya</b>; contoh INV-001 / MDR dan INV-001 / PROMO. Nominal harus biaya tambahan yang belum dihitung POS. Simpan rincian dulu, lalu pilih rincian yang sama saat posting di Mutasi Rekening atau Rekonsiliasi.</p>
<?php if($can_edit): ?><details id="fc-charge-editor"><summary>Buat / ubah rincian biaya</summary><form data-save="charge" id="fc-charge-form" class="fc-form">
<?php $hidden(['id'=>0,'revision'=>0,'settlement_id'=>$c['id'],'request_key'=>bin2hex(random_bytes(16))]); ?>
<label>Nomor dokumen<input class="form-control" name="document_no" maxlength="80" required></label><label>Baris / identitas biaya<input class="form-control" name="line_reference" maxlength="40" placeholder="Contoh: MDR-1" required></label>
<label>Tanggal posting biaya<input class="form-control" name="charge_date" type="date" value="<?= date('Y-m-d') ?>" min="<?= $esc($c['revenue_date']) ?>" max="<?= date('Y-m-d') ?>" required></label><label>Kategori<select class="form-select" name="category"><?php foreach(Finance_mutation_policy::categories() as $key=>$category): ?><option value="<?= $esc($key) ?>" data-direction="<?= $esc($category['direction']) ?>" <?= $key==='PLATFORM_FEE'?'selected':'' ?>><?= $esc($category['label']) ?></option><?php endforeach; ?></select></label>
<label>Arah<select class="form-select" name="direction"><option value="OUT">Keluar</option><option value="IN">Masuk</option></select></label><label>Nominal<input class="form-control" name="amount" type="number" step="0.01" min="0.01" max="999999999999.99" required></label>
<label>Bukti<select class="form-select" name="evidence_id"><?php $evidenceOptions(); ?></select></label><label>Mutasi lama yang sudah diposting (opsional)<select class="form-select" name="existing_mutation_id"><option value="">Belum diposting</option><?php foreach($r['mutations'] as $m) if($m['effective'] && empty($m['settlement_charge_id']) && !empty($can_void_modules[$m['ref_module']])): ?><option value="<?= (int)$m['id'] ?>"><?= $esc($m['mutation_no'].' · '.$m['mutation_date'].' · '.$m['mutation_type'].' '.$money($m['amount'])) ?></option><?php endif; ?></select><small class="fc-muted">Pilih hanya jika mengidentifikasi transaksi lama; tidak memposting ulang.</small></label>
<label class="wide">Catatan<input class="form-control" name="notes" maxlength="255" required></label><div class="wide"><button class="btn btn-primary">Simpan rincian, belum posting kas</button> <button class="btn btn-outline-secondary" type="reset">Rincian baru</button></div></form></details><?php endif; ?>
<div class="fc-scroll"><table class="fc-table"><thead><tr><th>Dokumen / biaya</th><th>Nominal / bukti</th><th>Status / tindakan</th></tr></thead><tbody><?php foreach($op['charges']??[] as $charge): ?><tr><td>#<?= (int)$charge['id'] ?> · <?= $esc($charge['document_no'].' / '.$charge['line_reference']) ?><br><?= $esc($charge['charge_date'].' · '.Finance_mutation_policy::label($charge['category'])) ?></td><td><?= $esc($charge['direction']) ?> <?= $money($charge['amount']) ?><?php if($charge['evidence_id']): ?><br><a href="<?= site_url('finance-reports/control/evidence/'.(int)$charge['evidence_id']) ?>">Unduh bukti</a><?php endif; ?></td><td><?= $esc($charge['mutation_no']?:'Belum diposting / sudah VOID') ?><?php if($can_edit && !$charge['mutation_id']): ?><br><button class="btn btn-sm btn-outline-primary" type="button" data-charge="<?= $esc($json($charge)) ?>">Ubah rincian</button><form data-save="approval-request" class="mt-2"><?php $hidden(['action_code'=>'POST_CHARGE','target_id'=>$charge['id']]); ?><input name="reason" class="form-control form-control-sm" maxlength="255" placeholder="Alasan pengajuan persetujuan" aria-label="Alasan persetujuan biaya" required><button class="btn btn-sm btn-outline-secondary mt-1">Ajukan persetujuan (bila diwajibkan)</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="fc-panel"><details><summary>Bukti privat — unggah sebelum memilih bukti di rincian</summary><p class="fc-muted">PDF/JPG/PNG, maksimal 5 MB; hanya pengguna berhak yang dapat mengunduh. Tidak dimasukkan ke paket customer.</p>
<?php if($can_edit): ?><form id="fc-evidence-upload" class="fc-filter" enctype="multipart/form-data"><?php $hidden(['settlement_id'=>$c['id']]); ?><label>File bukti<input class="form-control" type="file" name="evidence" accept=".pdf,.jpg,.jpeg,.png" required></label><button class="btn btn-outline-primary">Unggah bukti</button></form><?php endif; ?>
<ul><?php foreach($op['evidence']??[] as $e): ?><li>#<?= (int)$e['id'] ?> · <a href="<?= site_url('finance-reports/control/evidence/'.(int)$e['id']) ?>"><?= $esc($e['original_name']) ?></a> (<?= number_format((int)$e['byte_size']/1024,1) ?> KB)</li><?php endforeach; ?></ul></details></section>
<?php endif; ?>
<?php elseif($tab==='cash-plan'): ?>
<section class="fc-panel"><h3>Rencana → realisasi → sisa</h3><p class="fc-muted">Tautkan <b>mutasi manual yang sudah diposting</b>. <?= !empty($allocation_ready)?'Nominal mutasi dapat dibagi ke beberapa rencana, maksimal sebesar sisa mutasi.':'Satu mutasi utuh hanya dapat dipakai satu rencana.' ?> Sisa otomatis kembali jika mutasi di-VOID. POS, utang/piutang, dan payroll otomatis tidak boleh ditautkan ulang di sini.</p>
<?php if($can_edit): ?><details><summary>Tautkan realisasi dari Mutasi Rekening</summary>
<form id="fc-mutation-search" class="fc-filter"><label>Cari nomor mutasi / referensi<input class="form-control" name="q" maxlength="80"></label><label>Dari tanggal<input class="form-control" name="from" type="date"></label><label>Sampai tanggal<input class="form-control" name="to" type="date"></label><button class="btn btn-outline-secondary">Cari mutasi</button></form>
<div class="d-flex gap-2 mb-3"><button class="btn btn-sm btn-outline-secondary" type="button" data-mutation-page="-1">Sebelumnya</button><span id="fc-mutation-page"></span><button class="btn btn-sm btn-outline-secondary" type="button" data-mutation-page="1">Berikutnya</button></div>
<form data-save="<?= !empty($allocation_ready)?'plan-allocate':'plan-link' ?>" class="fc-form" id="fc-plan-link-form"><input type="hidden" name="revision" value="0"><label>Rencana<select class="form-select" name="plan_id" required><option value="">Pilih rencana</option><?php foreach($r['plans'] as $plan) if($plan['status']!=='CANCELLED'): ?><option value="<?= (int)$plan['id'] ?>" data-revision="<?= (int)$plan['revision'] ?>"><?= $esc($plan['title'].' · '.$plan['direction'].' '.$money($plan['amount'])) ?></option><?php endif; ?></select></label><label>Mutasi efektif<select class="form-select" name="mutation_id" id="fc-mutation-options" required><option value="">Gunakan Cari mutasi di atas</option></select></label><?php if(!empty($allocation_ready)): ?><input type="hidden" name="request_key" value="<?= bin2hex(random_bytes(16)) ?>"><label>Nominal untuk rencana ini<input class="form-control" name="amount" type="number" min="0.01" step="0.01" max="999999999999.99" required><small>Sisa mutasi terlihat pada pilihan mutasi. Lepas tautan lama terlebih dahulu jika ingin membagi mutasi yang sudah tertaut utuh.</small></label><?php endif; ?><label class="wide">Catatan penautan<input class="form-control" name="notes" maxlength="255" required></label><div class="wide"><button class="btn btn-primary">Tautkan, tanpa pembayaran baru</button></div></form></details><?php endif; ?>
<div class="fc-scroll"><table class="fc-table"><thead><tr><th>Rencana / status</th><th>Rencana</th><th>Realisasi</th><th>Sisa / lebih</th><th>Riwayat tautan</th></tr></thead><tbody><?php foreach($r['plans'] as $plan): ?><tr><td><?= $esc($plan['title']) ?><br><?= $esc($plan['computed_status']) ?></td><td class="num"><?= $money($plan['amount']) ?></td><td class="num"><?= $money($plan['actual']) ?></td><td class="num"><?= $money($plan['remaining']) ?><?php if($plan['overage']>.005): ?><br>Lebih <?= $money($plan['overage']) ?><?php endif; ?></td><td><?php foreach($plan['realizations'] as $link): ?><details><summary><?= $esc($link['mutation_no']) ?> · <?= $link['effective']?'Dihitung':($link['active_mutation_id']?'VOID, tidak dihitung':'Tautan dilepas') ?></summary><p><?= $money($link['amount']) ?> · <?= $esc($link['notes']) ?></p><?php if($can_edit && $link['active_mutation_id']): ?><form data-save="<?= !empty($link['allocation_link'])?'plan-allocation-unlink':'plan-unlink' ?>" data-confirm="Lepas tautan realisasi? Mutasi asli tetap utuh; sisa proyeksi akan bertambah."><?php $hidden(['id'=>$link['id'],'revision'=>$plan['revision']]); ?><input class="form-control" name="reason" maxlength="255" placeholder="Alasan melepas tautan" aria-label="Alasan melepas tautan" required><button class="btn btn-sm btn-outline-danger mt-1">Lepas tautan</button></form><?php endif; ?></details><?php endforeach; ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<?php elseif($tab==='settings'): ?>
<section class="fc-panel"><h3>Pengaturan kontrol keuangan</h3><div class="fc-note">Persetujuan berlaku hanya untuk <b>posting biaya tertaut settlement dan pembatalannya</b>, bukan semua transaksi aplikasi. Konfirmasi transfer/rencana tidak memposting kas. Pemeriksa harus pengguna berbeda dari pembuat/pengaju. Menonaktifkan kebijakan dicatat dalam audit.</div>
<?php if($can_edit && $can_settings): ?><form data-save="policy" class="fc-form" data-confirm="Simpan kebijakan baru? Persetujuan lama perlu diajukan ulang karena kebijakan berubah."><?php $hidden(['revision'=>$r['revision']]); ?>
<label>Persetujuan sebelum posting / VOID<select class="form-select" name="approval_enabled"><option value="0" <?= !$r['approval_enabled']?'selected':'' ?>>Tidak diwajibkan (default)</option><option value="1" <?= $r['approval_enabled']?'selected':'' ?>>Wajib mulai nominal ambang</option></select></label><label>Nominal minimal perlu persetujuan<input class="form-control" name="approval_threshold" type="number" step="0.01" min="0.01" max="999999999999.99" value="<?= $esc($r['approval_threshold']) ?>" required></label>
<label>Bukti biaya sebelum posting<select class="form-select" name="evidence_required"><option value="0" <?= !$r['evidence_required']?'selected':'' ?>>Opsional</option><option value="1" <?= $r['evidence_required']?'selected':'' ?>>Wajib untuk semua biaya tertaut</option></select></label><label>Tanggal proyeksi pembayaran payroll<input class="form-control" name="payroll_day" type="number" min="1" max="31" value="<?= (int)$r['payroll_day'] ?>" required><small class="fc-muted">Tanggal berikutnya setelah akhir periode. Tanggal 31 dibatasi akhir bulan jika bulan lebih pendek. Tidak mengubah gaji atau aturan uang makan.</small></label><label class="wide">Alasan perubahan<input class="form-control" name="notes" maxlength="255" required></label><div class="wide"><button class="btn btn-primary">Simpan pengaturan</button></div></form>
<?php else: ?><p>Persetujuan: <?= $r['approval_enabled']?'Wajib mulai '.$money($r['approval_threshold']):'Opsional' ?> · Bukti <?= $r['evidence_required']?'wajib':'opsional' ?> · Tanggal payroll: <?= (int)$r['payroll_day'] ?>.</p><p class="fc-muted">Perubahan memerlukan hak Kebijakan kontrol keuangan.</p><?php endif; ?></section>
<?php elseif($tab==='approvals'): ?>
<section class="fc-panel"><h3>Persetujuan penyesuaian settlement</h3><p class="fc-muted">Periksa nominal, rekening, tanggal, kategori dan bukti. Perubahan rincian, konfirmasi settlement, atau kebijakan membatalkan validitas persetujuan lama. Persetujuan dipakai satu kali oleh posting yang berhasil.</p>
<?php if(!$r['rows']): ?><p>Belum ada pengajuan. Ajukan dari rincian biaya atau menu pembatalan penyesuaian.</p><?php endif; ?>
<?php foreach($r['rows'] as $approval): $target=$approval['target'];$caseId=(int)($target['settlement_id']??$target['settlement_control_id']??0); ?>
<details class="fc-panel"><summary>#<?= (int)$approval['id'] ?> · <?= $approval['action_code']==='POST_CHARGE'?'Posting biaya':'VOID penyesuaian' ?> #<?= (int)$approval['target_id'] ?> · <?= !empty($approval['stale'])?'Rincian berubah — ajukan ulang':$esc($approval['status']) ?> · <?= $money($target['amount']??0) ?></summary>
<p>Pengaju: <?= $esc($approval['requester_name']?:'#'.$approval['requested_by']) ?> · Pemeriksa: <?= $esc($approval['reviewer_name']?:'Belum diperiksa') ?></p><p>Rekening: <?= $esc($approval['account']) ?> · <?= $esc($target['direction']??$target['mutation_type']??'') ?> <?= $money($target['amount']??0) ?><br>Tanggal: <?= $esc($target['charge_date']??$target['mutation_date']??'') ?> · <?= $esc(Finance_mutation_policy::label($target['category']??$target['report_category']??'')) ?><br>Dokumen: <?= $esc(($target['document_no']??$target['mutation_no']??'').' / '.($target['line_reference']??'')) ?><br>Alasan: <?= $esc($approval['reason']) ?></p>
<?php if(!empty($target['evidence_id'])): ?><p><a href="<?= site_url('finance-reports/control/evidence/'.(int)$target['evidence_id']) ?>">Unduh bukti biaya</a></p><?php endif; ?>
<?php if($can_edit && $can_approve && $approval['status']==='PENDING' && empty($approval['stale'])): ?><form data-save="approval-review" class="fc-form" data-confirm="Pastikan nominal, rekening, dan bukti telah diperiksa. Simpan keputusan ini?"><?php $hidden(['id'=>$approval['id']]); ?><label>Keputusan<select class="form-select" name="decision"><option value="APPROVED">Setujui</option><option value="REJECTED">Tolak</option></select></label><label>Alasan pemeriksaan<input class="form-control" name="reason" maxlength="255" required></label><div class="wide"><button class="btn btn-primary">Simpan keputusan</button></div></form><?php endif; ?></details><?php endforeach; ?>
<div class="d-flex gap-3"><span>Halaman <?= (int)$r['page'] ?></span><?php if($r['page']>1): ?><a href="?tab=approvals&page=<?= (int)$r['page']-1 ?>">Sebelumnya</a><?php endif; ?><?php if($r['more']): ?><a href="?tab=approvals&page=<?= (int)$r['page']+1 ?>">Berikutnya</a><?php endif; ?></div></section>
<?php endif; ?>
