<?php
$inv=$inventory;
$focus=$inv['focus_groups'];
$nullableMoney=static fn($value)=>$value===null?'<span class="rw-zero">Belum tersedia</span>':$money($value);
$percent=static fn($value)=>$value===null?'-':number_format($value,1,',','.').'%';
$locationLabel=static fn($value)=>$value==='EVENT'?'Event':'Reguler';
$lossLabels=['WASTE'=>'Waste / dibuang','SPOIL'=>'Spoil / rusak','PROCESS_LOSS'=>'Susut proses','VARIANCE'=>'Selisih hitung','ADJUSTMENT_MINUS'=>'Koreksi minus'];
$monthly=$inv['monthly'];foreach($monthly as &$point){$point['url']=$url(['month'=>$point['label'],'page'=>1,'day'=>'']);$point['note']=$point['label']===date('Y-m')?'Bulan berjalan':'';}unset($point);
?>
<?php foreach($inv['warnings'] as $warning): ?><div class="rw-notice"><?= $esc($warning) ?></div><?php endforeach ?>
<div class="rw-notice info">Basis <strong>nilai persediaan IDR</strong>, bukan pembayaran kas. Filter divisi dan Reguler/Event berlaku pada seluruh tab ini.<?= $cashFiltered?' Filter kas sebelumnya tidak dipakai di analisis persediaan.':'' ?></div>
<?php if($f['view']==='efficiency'): ?>
<?php
$totalRevenue=array_sum(array_column($focus,'revenue'));$totalHpp=array_sum(array_column($focus,'hpp'));$totalSupply=array_sum(array_column($focus,'supply'));$totalUsed=array_sum(array_column($focus,'used'));$totalClosing=0;$issues=0;
foreach($focus as $group){foreach(['material','component'] as $kind){if($group[$kind]){$totalClosing+=$group[$kind]['closing'];}}$stock=$group['material'];
    if(!$group['usage_reliable']){$issues++;}}
?>
<div class="rw-kpis rw-efficiency-kpis">
  <div class="rw-kpi teal"><span>Omzet neto / alokasi divisi</span><strong><?= $inv['revenue_available']?'Rp '.$money($totalRevenue):'Belum tersedia' ?></strong><small>Lokasi mengikuti divisi produk POS, bukan dibagi rata.</small></div>
  <div class="rw-kpi"><span>Pengadaan bahan ke divisi</span><strong>Rp <?= $money($totalSupply) ?></strong><small>PO langsung + SR diterima. <?= $issues?'Periksa kualitas data sebelum membaca rasio.':($totalRevenue>0?$percent(100*$totalSupply/$totalRevenue).' dari omzet.':'Belum ada basis omzet positif.') ?></small></div>
  <div class="rw-kpi gold"><span>HPP POS</span><strong><?= $inv['hpp_available']?'Rp '.$money($totalHpp):'Belum tersedia' ?></strong><small><?= $inv['hpp_available']&&$totalRevenue>0?$percent(100*$totalHpp/$totalRevenue).' dari omzet.':'HPP nota lunas sesuai snapshot biaya POS.' ?></small></div>
  <div class="rw-kpi"><span>Bahan dipakai / ledger</span><strong>Rp <?= $money($totalUsed) ?></strong><small>Pemakaian produksi / penjualan; bukan HPP POS, waste, atau koreksi.</small></div>
  <div class="rw-kpi"><span>Nilai akhir persediaan / buku</span><strong>Rp <?= $money($totalClosing) ?></strong><small>Gabungan bahan baku dan component yang tercatat pada snapshot.</small></div>
</div>
<?php if($issues): ?><div class="rw-notice"><strong><?= $issues ?> kelompok perlu pemeriksaan data.</strong> Ada nilai belum tersedia, biaya nol, saldo negatif, atau ketidaksesuaian nilai buku, mutasi, dan opname. Rasio pemakaian yang tidak dapat dipercaya ditampilkan "-", bukan dianggap efisien.</div><?php endif ?>
<article class="rw-panel"><div class="rw-section-head"><div><span class="rw-eyebrow">Omzet, biaya barang terjual, dan persediaan</span><h2>Apakah HPP sebanding dengan omzet?</h2></div><span class="rw-period-tag">HPP POS / nilai buku stok</span></div><p class="rw-sub">HPP berasal dari biaya snapshot barang dan extra pada nota POS, termasuk pengaruh refund/koreksi. Pemakaian ledger ditampilkan terpisah karena bahan yang masuk produksi component belum tentu sudah terjual. Klik titik untuk mengganti bulan fokus.</p><div class="rw-chart" data-report-chart="inventory-trend"></div></article>
<script type="application/json" id="inventory-trend"><?= $json(['type'=>'line','title'=>'Omzet, HPP POS, pengadaan, dan pemakaian stok','currency'=>'IDR','rows'=>$monthly,'series'=>[['key'=>'revenue','label'=>'Omzet neto alokasi','color'=>'#11786d'],['key'=>'hpp','label'=>'HPP POS','color'=>'#7b3455'],['key'=>'supply','label'=>'PO langsung + SR','color'=>'#b76a16'],['key'=>'used','label'=>'Pemakaian ledger','color'=>'#3076a6']]]) ?></script>
<div class="rw-division-grid"><?php foreach($focus as $group): ?><article class="rw-division-card"><span class="rw-eyebrow"><?= $esc($locationLabel($group['location'])) ?></span><h3><?= $esc($group['division_name']) ?></h3><div><span>HPP POS / omzet</span><strong><?= $percent($group['hpp_ratio']) ?></strong></div><p>Omzet <?= $inv['revenue_available']?'Rp '.$money($group['revenue']):'belum tersedia' ?><br>HPP POS <?= $inv['hpp_available']?'Rp '.$money($group['hpp']):'belum tersedia' ?><br>Pengadaan Rp <?= $money($group['supply']) ?></p><small>Pengadaan / omzet: <?= $percent($group['supply_ratio']) ?><br>Pemakaian ledger / omzet: <?= $percent($group['usage_ratio']) ?></small><?php if(!$group['usage_reliable']): ?><span class="rw-quality-flag">Perlu rekonsiliasi stok<?php if($group['unvalued']): ?> / <?= (int)$group['unvalued'] ?> mutasi tanpa biaya<?php endif ?></span><?php endif ?></article><?php endforeach ?></div>
<article class="rw-panel">
  <h2>Alur nilai persediaan / <?= $esc(Report_workspace::monthLabel($f['month'])) ?></h2>
  <p class="rw-sub">HPP POS mencatat biaya barang saat terjual. Pemakaian ledger mencatat bahan yang keluar, termasuk input produksi component. Component yang belum terjual tetap muncul di saldo component. PO + SR adalah rincian pengadaan; "masuk buku" bisa juga mencakup perpindahan dan pembalik.</p>
  <div class="rw-table-wrap"><table class="rw-matrix rw-inventory-table"><thead><tr>
    <th>Divisi / lokasi</th><th>Omzet neto</th><th>HPP POS</th><th>HPP / omzet</th><th>Awal bahan</th><th>Awal component</th><th>Masuk component</th><th>PO langsung</th><th>SR diterima</th><th>Masuk bahan</th><th>Dipakai / ledger</th><th>Keluar component</th><th>Transfer bahan</th><th>Waste + spoil</th><th>Susut proses</th><th>Koreksi minus / selisih</th><th>Koreksi plus</th><th>Sisa bahan</th><th>Sisa component</th><th>Selisih persamaan buku</th>
  </tr></thead><tbody><?php foreach($focus as $group): $stock=$group['material'];$component=$group['component']; ?>
    <tr><td><strong><?= $esc($group['division_name']) ?></strong><small><?= $locationLabel($group['location']) ?></small></td>
    <td class="rw-num"><?= $inv['revenue_available']?$money($group['revenue']):'<span class="rw-zero">Belum tersedia</span>' ?></td>
    <td class="rw-num"><?= $inv['hpp_available']?$money($group['hpp']):'<span class="rw-zero">Belum tersedia</span>' ?></td>
    <td class="rw-num"><?= $percent($group['hpp_ratio']) ?></td>
    <td class="rw-num"><?= $nullableMoney($stock['opening']??null) ?></td><td class="rw-num"><?= $nullableMoney($component['opening']??null) ?></td><td class="rw-num"><?= $nullableMoney($component['incoming']??null) ?></td>
    <td class="rw-num"><?= $money($group['purchase']) ?></td><td class="rw-num"><?= $money($group['sr']) ?></td><td class="rw-num"><?= $nullableMoney($stock['incoming']??null) ?></td>
    <td class="rw-num"><?= $money($group['used']) ?><?php if($group['unvalued']): ?><small><?= $group['unvalued'] ?> baris biaya nol / minus</small><?php endif ?></td>
    <td class="rw-num"><?= $nullableMoney($component['outgoing']??null) ?></td><td class="rw-num"><?= $money($group['transferred']) ?></td>
    <td class="rw-num"><?= $nullableMoney($stock['loss']??null) ?></td><td class="rw-num"><?= $nullableMoney($stock['process_loss']??null) ?></td>
    <td class="rw-num"><?= $nullableMoney($stock?$stock['variance']+$stock['minus']:null) ?></td><td class="rw-num"><?= $nullableMoney($stock['plus']??null) ?></td>
    <td class="rw-num"><?= $nullableMoney($stock['closing']??null) ?></td><td class="rw-num"><?= $nullableMoney($component['closing']??null) ?></td>
    <td class="rw-num <?= $stock && abs($stock['reconciliation_gap'])>100?'rw-amount-out':'' ?>"><?= $nullableMoney($stock['reconciliation_gap']??null) ?><small>Keluar bahan: <?= $nullableMoney($stock['outgoing']??null) ?></small></td></tr>
  <?php endforeach ?></tbody></table></div>
<p class="rw-sub rw-footnote">Persamaan buku: awal + masuk + koreksi plus - keluar buku - waste/spoil - susut proses - selisih/koreksi minus = sisa. HPP dihitung saat barang POS terjual dari biaya snapshot. Selisih nilai tidak otomatis dianggap konsumsi atau kerugian; valuasi FIFO, koreksi biaya, dan snapshot perlu ditelusuri.</p></article>
<article class="rw-panel rw-opname-panel"><h2>Jembatan opname sebelumnya ke opname akhir</h2><p class="rw-sub">Snapshot opname bulanan yang sudah di-generate, bukan jaminan seluruh item sudah dihitung fisik. Opname yang belum ada ditulis "Belum tersedia", tidak diganti nol. Component dipisahkan agar bahan yang diproduksi menjadi component tidak dihitung dua kali.</p><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Divisi / lokasi / stok</th><th>Opname bulan sebelumnya</th><th>Awal buku</th><th>Selisih awal</th><th>Sisa buku</th><th>Opname akhir</th><th>Selisih akhir</th><th>Kualitas data</th></tr></thead><tbody><?php foreach($focus as $group): foreach(['material'=>'Bahan baku','component'=>'Component'] as $kind=>$caption): $stock=$group[$kind];if(!$stock){continue;} ?><tr><td><strong><?= $esc($group['division_name'].' / '.$locationLabel($group['location'])) ?></strong><small><?= $caption ?></small></td><td class="rw-num"><?= $nullableMoney($stock['opname_before']['value']??null) ?><small><?= $esc($stock['opname_before']['generated_at']??'Belum generate') ?></small></td><td class="rw-num"><?= $money($stock['opening']) ?></td><td class="rw-num"><?= $nullableMoney($stock['opening_gap']) ?></td><td class="rw-num"><?= $money($stock['closing']) ?></td><td class="rw-num"><?= $nullableMoney($stock['opname_after']['value']??null) ?><small><?= $esc($stock['opname_after']['generated_at']??'Belum generate') ?></small></td><td class="rw-num"><?= $nullableMoney($stock['closing_gap']) ?></td><td><?php if($stock['negative_profiles']): ?><span class="rw-pill out"><?= $stock['negative_profiles'] ?> profil negatif</span><?php elseif($stock['snapshot_incomplete']): ?>Jumlah profil opname berbeda<?php elseif(!$stock['opname_before'] || !$stock['opname_after']): ?>Opname belum lengkap<?php elseif(abs($stock['opening_gap'])>100 || abs($stock['closing_gap'])>100): ?>Nilai perlu rekonsiliasi<?php else: ?><span class="rw-pill">Snapshot sejalan</span><?php endif ?></td></tr><?php endforeach;endforeach ?></tbody></table></div></article>
<details class="rw-guide"><summary>Perbandingan divisi tiap bulan dalam rentang</summary><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Bulan</th><th>Divisi / lokasi</th><th>Omzet neto</th><th>HPP POS</th><th>HPP / omzet</th><th>PO + SR</th><th>Belanja / omzet</th><th>Dipakai ledger</th><th>Sisa bahan</th><th>Sisa component</th></tr></thead><tbody><?php foreach($inv['groups'] as $group): ?><tr><td><a href="<?= $esc($url(['month'=>$group['month'],'page'=>1])) ?>"><?= $esc($group['month']) ?></a></td><td><?= $esc($group['division_name'].' / '.$locationLabel($group['location'])) ?></td><td class="rw-num"><?= $inv['revenue_available']?$money($group['revenue']):'-' ?></td><td class="rw-num"><?= $inv['hpp_available']?$money($group['hpp']):'Belum tersedia' ?></td><td class="rw-num"><?= $percent($group['hpp_ratio']) ?></td><td class="rw-num"><?= $money($group['supply']) ?></td><td class="rw-num"><?= $percent($group['supply_ratio']) ?></td><td class="rw-num"><?= $money($group['used']) ?></td><td class="rw-num"><?= $nullableMoney($group['material']['closing']??null) ?></td><td class="rw-num"><?= $nullableMoney($group['component']['closing']??null) ?></td></tr><?php endforeach ?></tbody></table></div></details>
<?php else: require __DIR__.'/_financial_waste.php'; endif ?>
<details class="rw-guide"><summary>Metode analisis divisi, lokasi, opname, dan susut</summary><p>Omzet nota lunas tanpa pajak dialokasikan proporsional menurut nilai produk/extra sebelum refund. Promo tingkat nota, service, dan pembulatan ikut dibagi secara proporsional; selisih sen dialokasikan deterministik agar jumlah divisi tepat sama dengan omzet. Refund dikurangi pada bulan refund, mengikuti snapshot divisi baris yang direfund. Pembayaran split tidak menggandakan omzet.</p><p>HPP POS memakai cogs_amount dan biaya extra yang tersimpan pada nota, ditambah koreksi HPP defisit yang diposting serta dikurangi nilai HPP refund pada tanggal refund. Rumus mengikuti dasar HPP laporan keuangan POS; biaya master/resep saat ini tidak dipakai untuk menulis ulang histori. Rasio HPP/omzet mengukur biaya penjualan tercatat, sedangkan pemakaian ledger menunjukkan stok yang keluar untuk produksi/penjualan.</p><p>Divisi operasional memakai snapshot pada baris POS. Reguler/Event mengikuti pos_scope divisi produk yang dirujuk snapshot POS; jika tidak spesifik, memakai order_scope. Ini penting karena nota Reguler dapat memuat produk Event. Perubahan pengaturan pos_scope master dapat memengaruhi pemetaan histori; pendapatan tanpa snapshot divisi ditampilkan terpisah. Divisi pembuat resep belum tentu divisi penerima omzet.</p><p>Pengadaan = PO langsung ke divisi + pemenuhan SR posted, memakai harga snapshot yang sama dengan laporan bahan baku ke divisi. Barang masuk gudang belum menjadi pengadaan divisi sebelum SR, sehingga tidak dihitung dua kali. PO mata uang selain IDR tidak dikonversi secara tebakan. Pengadaan adalah stok diterima, bukan uang kas dibayar.</p><p>Awal/sisa buku berasal dari ledger stok bulanan. Snapshot opname bulan sebelumnya dan akhir ditampilkan berdampingan. Snapshot tidak sama dengan hitung fisik: periksa cakupan opname di modul operasional. Selisih nilai, profil negatif, dan biaya nol tetap terlihat. Tidak ada pembentukan opname, repair, ataupun perubahan saldo dari laporan ini.</p><p>Pemakaian bahan berasal dari USAGE_OUT, termasuk input produksi component. Component yang tersisa belum seluruhnya menjadi HPP penjualan. Waste/dibuang dan spoil/rusak dilaporkan sebagai bahan terbuang; susut proses dan selisih/koreksi minus dipisahkan. Bahan yang menjadi component tidak dijumlahkan lagi sebagai biaya baru.</p><p>Analisis susut membaca ledger mutasi, bukan menambahkan kembali dokumen adjustment. Mutasi asli dan pembalik mengikuti tanggal masing-masing. Pembalik mengurangi kategori asal dan bisa membuat susut neto negatif pada bulan koreksi. Nilai berasal dari biaya snapshot, bukan harga master hari ini. Rasio bukan laba dan bukan penilaian otomatis baik/buruk.</p></details>
