<?php if($comparison && $s['available']):
$pos=$comparison;$netCash=$t['sales_in']-$t['sales_out'];$delta=$netCash-$s['totals']['value'];
$posLink=site_url('pos/reports/sales').'?'.http_build_query(['date_from'=>$f['day']?:$f['from'],'date_to'=>min($f['day']?:$f['to'],date('Y-m-d')),'status'=>'ALL','order_scope'=>'ALL','service_type'=>'ALL']);
?>
<div class="rw-grid rw-reconcile-grid">
  <article class="rw-panel"><span class="rw-eyebrow">01 / Basis nota POS</span><h2>Kenapa angka omzet berbeda?</h2><p class="rw-sub">Pembanding /pos/reports/sales, seluruh outlet dan metode bayar, pada periode yang sama.</p><div class="rw-equation">
    <div><span>Uang diterima sebelum refund<small>Pembayaran nota terpilih; bukan kas bersih</small></span><strong>Rp <?= $money($pos['received']) ?></strong></div>
    <div><span>Tagihan sebelum refund</span><strong>Rp <?= $money($pos['billing']) ?></strong></div>
    <div><span>- Refund atas nota terpilih</span><strong>Rp <?= $money($pos['refund']) ?></strong></div>
    <div class="rw-equation-total"><span>= Penjualan Bersih / laporan POS</span><strong>Rp <?= $money($pos['net']) ?></strong></div>
  </div><p class="rw-sub">Laporan POS mengelompokkan nota menurut tanggal lunas, atau tanggal konfirmasi/pesan jika belum lunas. Refund atas nota tersebut bisa terjadi di bulan lain. Ada <?= (int)$pos['unsettled'] ?> nota belum lunas dalam kelompok ini.</p><?php if($can_pos): ?><a class="rw-button" href="<?= $esc($posLink) ?>">Buka POS dengan tanggal yang sama</a><?php endif ?></article>
  <article class="rw-panel rw-insight"><span class="rw-eyebrow">02 / Basis pengakuan bulanan</span><h2>Omzet neto analisis keuangan</h2><div class="rw-equation">
    <div><span>Tagihan nota lunas periode ini</span><strong>Rp <?= $money($s['totals']['billing']) ?></strong></div>
    <div><span>- Pajak penjualan</span><strong>Rp <?= $money($s['totals']['tax']) ?></strong></div>
    <div><span>- Refund yang terjadi periode ini</span><strong>Rp <?= $money($s['totals']['refund']) ?></strong></div>
    <div class="rw-equation-total"><span>= Omzet POS neto</span><strong>Rp <?= $money($s['totals']['value']) ?></strong></div>
  </div><div class="rw-notice <?= $pos['net']===$s['totals']['value']?'info':'' ?>"><?= $pos['net']===$s['totals']['value']?'Cocok dengan Penjualan Bersih laporan POS.':'Selisih basis terhadap Penjualan Bersih POS: Rp '.$money($s['totals']['value']-$pos['net']).'.' ?></div><p class="rw-sub">Perbedaan dapat berasal dari pajak, nota belum lunas, atau refund lintas bulan. Perbedaan basis bukan alasan untuk mengubah saldo transaksi.</p><a class="rw-button" href="<?= $esc($url(['view'=>'sales','page'=>1])) ?>">Telusuri nota & refund</a></article>
</div>
<article class="rw-panel"><span class="rw-eyebrow">03 / Basis mutasi rekening</span><h2>POS masuk dan keluar bukan dua jenis omzet</h2><p class="rw-sub">Masuk adalah uang yang dicatat diterima rekening. Keluar bisa refund pelanggan atau koreksi/pembatalan pembayaran. DP dipisahkan karena belum menjadi penjualan.</p><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Sumber</th><th>Kas masuk</th><th>Kas keluar</th><th>Makna</th></tr></thead><tbody><?php foreach($r['groups'] as $group): if(!in_array($group['effect'],['sales','deposit'],true)){continue;} ?><tr><td><a href="<?= $esc($url(['view'=>'detail','category'=>$group['code'],'page'=>1])) ?>"><?= $esc($group['label']) ?></a></td><td class="rw-num"><?= $money($group['in']) ?></td><td class="rw-num"><?= $money($group['out']) ?></td><td><?= $group['effect']==='deposit'?'DP / pembalik DP, bukan omzet':($group['code']==='POS_REFUND'?'Pengembalian uang pelanggan':'Pembayaran / koreksi rekening; lihat dokumen sumber') ?></td></tr><?php endforeach ?></tbody></table></div>
  <div class="rw-balance"><div><span>Pembayaran POS masuk (tanpa DP)</span><strong><?= $money($t['sales_in']) ?></strong></div><div><span>- Refund / koreksi POS keluar</span><strong><?= $money($t['sales_out']) ?></strong></div><div><span>= Kas POS neto tercatat</span><strong><?= $money($netCash) ?></strong></div><div><span>Selisih terhadap omzet neto</span><strong><?= $money($delta) ?></strong></div></div>
  <p class="rw-sub">Kas dan omzet tidak harus sama: tanggal penerimaan, refund, pajak, kembalian, biaya platform, serta koreksi dapat berbeda. Selisih ini ditampilkan apa adanya, tidak ditutup otomatis. Klik sumber di tabel untuk menelusuri mutasi.</p>
</article>
<?php if($pos['cash_anomalies']): ?><article class="rw-panel rw-recon-findings"><h2>Nota yang perlu ditelusuri</h2><p class="rw-sub">Maksimal 100 nota lunas periode ini dengan selisih pembayaran via payment line terhadap paid_total nota. Ini indikator pemeriksaan, bukan otorisasi menghapus transaksi. DP, beda tanggal bayar, dan mutasi manual perlu diperiksa terpisah.</p><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Nota</th><th>Pembayaran nota</th><th>Mutasi pembayaran neto</th><th>Selisih</th><th>Baris mutasi</th></tr></thead><tbody><?php foreach($pos['cash_anomalies'] as $finding): ?><tr><td><?php if($can_pos): ?><a href="<?= $esc(site_url('pos/reports/sales/'.(int)$finding['order_id'])) ?>"><?= $esc($finding['order_no']) ?></a><?php else: ?><?= $esc($finding['order_no']) ?><?php endif ?></td><td class="rw-num"><?= $number($finding['paid_total']) ?></td><td class="rw-num"><?= $number($finding['cash_value']) ?></td><td class="rw-num rw-amount-out"><?= $number($finding['difference']) ?></td><td class="rw-num"><?= (int)$finding['mutations'] ?></td></tr><?php endforeach ?></tbody></table></div></article><?php endif ?>
<?php endif ?>
