<?php
$base='finance-reports/monthly-analysis';
require __DIR__.'/_setup.php';
$r=$report;
$months=$r['months']??Report_workspace::financialMonths($f);
$resetCash=['account_id'=>0,'category'=>'','direction'=>'','q'=>'','flow'=>'','currency'=>'IDR','page'=>1];
$cashFiltered=$f['account_id'] || $f['category']!=='' || $f['direction']!=='' || $f['q']!=='' || $f['flow']!=='';
$operational=in_array($f['view'],['efficiency','waste'],true);
$monthOptions=$month_options?:Report_workspace::monthOptions($f);
$this->load->view('finance/_tabs',['finance_tab_active'=>'monthly-analysis']);
?>
<section class="report-workspace rw-finance">
  <header class="rw-hero"><div><div class="rw-eyebrow">Namu / Financial intelligence</div><h1>Dari omzet, sampai setiap bahan.</h1><p>Omzet, kas, efisiensi belanja, dan bahan terbuang dalam satu ruang analisis. Angka yang dapat ditelusuri, bukan sekadar grafik.</p></div><div class="rw-actions"><?php if($can_export && !$error): ?><?php if(!$operational): ?><a class="rw-button" href="<?= $esc($url(['export'=>'matrix'])) ?>">CSV perbandingan</a><?php endif ?><a class="rw-button" href="<?= $esc($url(['export'=>'csv'])) ?>">CSV <?= $operational?($f['view']==='waste'?'bahan terbuang':'efisiensi'):($f['view']==='sales'?'omzet':'mutasi') ?></a><?php endif ?><button class="rw-button" type="button" data-report-print>Cetak</button></div></header>
  <form class="rw-filter rw-fin-filter" method="get" action="<?= $esc(site_url($base)) ?>">
    <?php foreach(['month_from'=>'Dari bulan','month_to'=>'Sampai bulan','month'=>'Bulan fokus / rincian'] as $field=>$label): ?><label><?= $label ?><select name="<?= $field ?>" required><?php foreach($monthOptions as $value=>$caption): ?><option value="<?= $esc($value) ?>"<?= $selected($f[$field],$value) ?>><?= $esc($caption) ?></option><?php endforeach ?></select></label><?php endforeach ?>
    <label>Mata uang<select name="currency"><?php $currencies=array_unique(array_merge(['IDR',$f['currency']],array_column($r['accounts']??[],'currency_code'))); foreach($currencies as $currency): ?><option<?= $selected($f['currency'],$currency) ?>><?= $esc($currency) ?></option><?php endforeach ?></select></label>
    <input type="hidden" name="view" value="<?= $esc($f['view']) ?>">
    <?php if($operational): ?>
      <label>Divisi<select name="division_id"><option value="0">Semua divisi</option><?php foreach($inventory['divisions']??[] as $division): ?><option value="<?= (int)$division['id'] ?>"<?= $selected($f['division_id'],$division['id']) ?>><?= $esc($division['name']) ?></option><?php endforeach ?></select></label>
      <label>Lokasi<select name="location"><?php foreach(['ALL'=>'Reguler + Event','REGULAR'=>'Reguler','EVENT'=>'Event'] as $value=>$caption): ?><option value="<?= $value ?>"<?= $selected($f['location'],$value) ?>><?= $caption ?></option><?php endforeach ?></select></label>
      <?php if($f['view']==='waste'): ?><label>Stok<select name="inventory_kind"><?php foreach(['ALL'=>'Bahan + Component','MATERIAL'=>'Bahan baku','COMPONENT'=>'Component'] as $value=>$caption): ?><option value="<?= $value ?>"<?= $selected($f['inventory_kind'],$value) ?>><?= $caption ?></option><?php endforeach ?></select></label><label>Jenis susut<select name="loss_kind"><?php foreach(['ALL'=>'Semua jenis','WASTE'=>'Waste / dibuang','SPOIL'=>'Spoil / rusak','PROCESS_LOSS'=>'Susut proses','VARIANCE'=>'Selisih hitung','ADJUSTMENT_MINUS'=>'Koreksi minus'] as $value=>$caption): ?><option value="<?= $value ?>"<?= $selected($f['loss_kind'],$value) ?>><?= $caption ?></option><?php endforeach ?></select></label><label class="rw-search">Bahan / lot / alasan<input name="asset_q" value="<?= $esc($f['asset_q']) ?>" maxlength="150"></label><?php endif ?>
    <?php else: ?><details class="rw-cash-filters"<?= $cashFiltered?' open':'' ?>><summary>Filter khusus arus kas<?= $cashFiltered?' / aktif':'' ?></summary><div>
      <label>Rekening<select name="account_id"><option value="0">Semua rekening</option><?php foreach($r['accounts']??[] as $a): ?><option value="<?= (int)$a['id'] ?>"<?= $selected($f['account_id'],$a['id']) ?>><?= $esc($a['account_name'].' / '.$a['currency_code'].(!$a['is_active']?' (nonaktif)':'')) ?></option><?php endforeach ?></select></label>
      <label>Kelompok arus<select name="flow"><option value="">Semua kelompok</option><?php foreach($r['flow_options']??[] as $code=>$label): ?><option value="<?= $esc($code) ?>"<?= $selected($f['flow'],$code) ?>><?= $esc($label) ?></option><?php endforeach ?></select></label>
      <label>Kategori sumber<select name="category"><option value="">Semua kategori</option><?php foreach($r['category_options']??[] as $code=>$label): ?><option value="<?= $esc($code) ?>"<?= $selected($f['category'],$code) ?>><?= $esc($label) ?></option><?php endforeach ?></select></label>
      <label>Arah<select name="direction"><option value="">Masuk + keluar</option><option value="IN"<?= $selected($f['direction'],'IN') ?>>Masuk</option><option value="OUT"<?= $selected($f['direction'],'OUT') ?>>Keluar</option></select></label>
      <label class="rw-search">Referensi / catatan<input name="q" value="<?= $esc($f['q']) ?>" maxlength="150" placeholder="Nomor PO, mutasi, keterangan..."></label>
    </div><p class="rw-sub">Filter ini hanya berlaku pada kas. Omzet nota disembunyikan saat filter kas aktif agar nota split payment tidak dihitung ganda.</p></details><?php endif ?>
    <button class="rw-button primary">Tampilkan analisis</button><a class="rw-button" href="<?= $esc(site_url($base)) ?>">Reset</a>
  </form>
  <nav class="rw-tabs rw-fin-tabs" aria-label="Tampilan analisis keuangan"><?php $tabNo=0;foreach(['overview'=>'Tren & Perbandingan','reconcile'=>'Cocokkan dengan POS','efficiency'=>'Efisiensi Belanja','waste'=>'Waste & Susut','matrix'=>'Rekap Harian','sales'=>'Rincian Omzet','detail'=>'Mutasi Kas','balances'=>'Saldo & Jurnal'] as $key=>$label): $tabChange=['view'=>$key,'page'=>1,'day'=>''];if(in_array($key,['efficiency','waste','reconcile'],true)){$tabChange=array_replace($resetCash,$tabChange);} ?><a class="<?= $f['view']===$key?'active':'' ?>" <?= $f['view']===$key?'aria-current="page"':'' ?> href="<?= $esc($url($tabChange)) ?>"><span><?= sprintf('%02d',++$tabNo) ?></span><?= $esc($label) ?></a><?php endforeach ?></nav>
  <?php if($error): ?><div class="rw-notice error" role="alert"><?= $esc($error) ?></div><?php else: $t=$r['totals'];$s=$r['sales'];$bt=$r['balances']['total']; ?>
  <div class="rw-section-head"><div><span class="rw-eyebrow">Sorotan periode</span><h2><?= $esc($f['month']) ?><?= $f['day']!==''?' / '.$esc($f['day']):'' ?></h2></div><span class="rw-period-tag"><?= $r['partial_month']?'Berjalan sampai '.date('d-m-Y'):'Bulan penuh' ?> / <?= $esc($f['currency']) ?></span></div>
  <?php if($f['day']!==''): ?><div class="rw-notice info">Kartu dan rincian hanya tanggal <?= $esc($f['day']) ?>. Grafik dan matriks tetap mencakup bulan penuh. <a href="<?= $esc($url(['day'=>'','page'=>1])) ?>">Lihat seluruh bulan</a></div><?php endif ?>
  <?php if(!$s['available'] && !$operational): ?><div class="rw-notice"><?= $esc($s['reason']) ?> <a href="<?= $esc($url($resetCash)) ?>">Reset filter kas</a></div><?php endif ?>
  <?php if($f['view']==='overview'): ?>
  <div class="rw-kpis">
    <a class="rw-kpi teal" href="<?= $esc($url(array_replace($resetCash,['view'=>'sales']))) ?>"><span>Omzet POS neto</span><strong><?= $s['available']?'Rp '.$money($s['totals']['value']):'Tidak ditampilkan' ?></strong><small>Tanpa pajak, setelah refund. Bukan kas masuk.</small><?php if($s['available'] && $r['compare_available'] && !$f['day']): ?><em><?= $esc(Report_workspace::change($s['totals']['value'],$s['compare']['value'])) ?> vs <?= $esc($f['compare']) ?></em><?php endif ?></a>
    <a class="rw-kpi" href="<?= $esc($url(['flow'=>'business','direction'=>'OUT','view'=>'detail','page'=>1])) ?>"><span>Pengeluaran usaha / kas</span><strong><?= $esc($f['currency']) ?> <?= $money($t['business_out']) ?></strong><small>Pembelian, gaji, dan biaya. Tanpa pembayaran utang, kasbon, prive, refund POS, atau transfer.</small><?php if($r['compare_available'] && !$f['day']): ?><em><?= $esc(Report_workspace::change($t['business_out'],$r['compare']['business_out'])) ?> vs <?= $esc($f['compare']) ?></em><?php endif ?></a>
    <a class="rw-kpi gold" href="<?= $esc($url(['flow'=>'debt','direction'=>'IN','view'=>'detail','page'=>1])) ?>"><span>Penerimaan utang / pinjaman</span><strong><?= $esc($f['currency']) ?> <?= $money($t['debt_in']) ?></strong><small>Uang masuk dari utang. Tidak menambah omzet.</small></a>
    <div class="rw-kpi"><span>Penerimaan nonpenjualan lain</span><strong><?= $esc($f['currency']) ?> <?= $money($t['non_sales_in']-$t['debt_in']) ?></strong><small>Di luar pembayaran POS, utang, dan transfer. Komposisinya ada di uraian arus kas.</small></div>
  </div>
  <p class="rw-sub">Pengeluaran usaha memakai tanggal kas dibayar, termasuk pembelian persediaan/aset; selisihnya terhadap omzet bukan laba bersih.<?= $r['partial_month']?' Kartu membandingkan jumlah hari berjalan yang sama; tabel antarbulan menampilkan realisasi masing-masing bulan.':'' ?></p>
  <?php if($t['unclassified'] || !$r['category_ready']): ?><div class="rw-notice">Ada <?= (int)$t['unclassified'] ?> mutasi fokus yang belum diklasifikasikan. Tetap dihitung dalam total kas, tetapi tidak ditebak sebagai omzet atau biaya usaha.</div><?php endif ?>
  <?php endif ?>
  <?php if(in_array($f['view'],['overview','matrix'],true)):
    $chartRows=$f['view']==='overview'?$r['monthly']:$r['daily'];
    foreach($chartRows as &$row){
      $target=$f['view']==='overview'?['month'=>$row['label'],'day'=>'']:['day'=>$row['label']];
      $row['links']=['omzet'=>$url(array_replace($target,['view'=>'sales','page'=>1])), 'business_out'=>$url(array_replace($target,['flow'=>'business','direction'=>'OUT','view'=>'detail','page'=>1]))];
      $row['note']=substr($row['label'],0,7)===date('Y-m')?'Realisasi sampai '.date('d-m-Y'):'';
    }unset($row);
    $series=[];if($s['available']){$series[]=['key'=>'omzet','label'=>'Omzet POS neto','color'=>'#11786d'];}$series[]=['key'=>'business_out','label'=>'Pengeluaran usaha / kas','color'=>'#8d2945'];
    $largest=null;foreach($r['matrix'] as $source){if($source['flow']==='business' && $source['direction']==='OUT' && (!$largest || $source['total']>$largest['total'])){$largest=$source;}}
  ?>
  <div class="rw-fin-trends"><article class="rw-panel"><div class="rw-section-head"><div><span class="rw-eyebrow">Dua cerita, satu pandangan</span><h2><?= $f['view']==='overview'?'Omzet vs pengeluaran usaha':'Ritme omzet & pengeluaran harian' ?></h2></div><span class="rw-period-tag"><?= $esc($f['currency']) ?></span></div><p class="rw-sub">Klik titik untuk membuka transaksi. Klik legenda untuk menampilkan / menyembunyikan garis.<?= $f['view']==='overview'?' Rentang '.$esc($f['month_from']).' sampai '.$esc($f['month_to']).'.':'' ?></p><div class="rw-chart" data-report-chart="finance-month-chart"></div></article>
    <aside class="rw-panel rw-insight"><span class="rw-eyebrow">Baca perubahan</span><h2>Biaya terbesar dalam rentang</h2><?php if($largest): ?><p><?= $esc($largest['label']) ?></p><strong><?= $esc($f['currency']) ?> <?= $money($largest['total']) ?></strong><p class="rw-sub">Akumulasi arus keluar, bukan nilai pesanan. Pembalik masuk ditampilkan terpisah.</p><?php if($f['view']==='overview'): ?><button type="button" class="rw-button" data-source-pick="<?= $esc($largest['key']) ?>">Telusuri trennya</button><?php endif ?><?php else: ?><p class="rw-sub">Belum ada pengeluaran usaha untuk filter ini.</p><?php endif ?><hr><p class="rw-sub">Utang, modal, piutang, DP, dan transfer tidak masuk ke garis omzet. Nilai nol tetap terlihat; angka negatif tidak dipotong.</p></aside></div>
  <script type="application/json" id="finance-month-chart"><?= $json(['type'=>'line','title'=>'Omzet POS neto dan pengeluaran usaha','currency'=>$f['currency'],'rows'=>$chartRows,'series'=>$series]) ?></script>
  <?php endif ?>
  <?php if($f['view']==='overview'): ?>
    <?php require __DIR__.'/_financial_comparison.php'; ?>
    <div class="rw-grid">
    <?php foreach(['in'=>'Uang masuk berasal dari mana?','out'=>'Uang keluar untuk apa?'] as $direction=>$heading): ?>
      <article class="rw-panel rw-cash-bridge"><span class="rw-eyebrow">Arus kas / fokus <?= $esc($f['month']) ?></span><h2><?= $heading ?></h2><strong class="rw-cash-total"><?= $esc($f['currency']) ?> <?= $money($t[$direction]) ?></strong><p class="rw-sub">Seluruh kas <?= $direction==='in'?'masuk':'keluar' ?> nontransfer, bukan <?= $direction==='in'?'omzet':'beban akrual' ?>.</p><ul><?php foreach($r['flows'] as $flow): if($flow['code']==='transfer' || !$flow[$direction]){continue;} ?><li><a href="<?= $esc($url(['flow'=>$flow['code'],'direction'=>strtoupper($direction),'view'=>'detail','page'=>1])) ?>"><?= $esc($flow['label']) ?></a><b><?= $money($flow[$direction]) ?></b></li><?php endforeach ?></ul><p class="rw-sub">Transfer internal <?= $direction==='in'?'masuk':'keluar' ?>: <?= $money($t['transfer_'.$direction]) ?>, terpisah dari jumlah di atas.</p></article>
    <?php endforeach ?></div>
  <?php elseif($f['view']==='matrix'): ?>
    <article class="rw-panel"><h2>Realisasi setiap hari / <?= $esc($f['month']) ?></h2><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Tanggal</th><th>Omzet neto</th><th>Pengeluaran usaha</th><th>Penerimaan utang</th><th>Kas masuk nontransfer</th><th>Kas keluar nontransfer</th><th>Transfer masuk</th><th>Transfer keluar</th></tr></thead><tbody><?php foreach($r['daily'] as $d): ?><tr><td><a href="<?= $esc($url(['day'=>$d['label'],'view'=>'detail','page'=>1])) ?>"><?= $esc($d['label']) ?></a></td><?php foreach(['omzet','business_out','debt_in','in','out','transfer_in','transfer_out'] as $key): ?><td class="rw-num"><?= $d[$key]===null?'-':$money($d[$key]) ?></td><?php endforeach ?></tr><?php endforeach ?></tbody></table></div></article>
  <?php elseif($f['view']==='sales'): ?>
    <article class="rw-panel"><h2>Rincian omzet POS neto</h2><p class="rw-sub">Tagihan nota lunas dikurangi pajak dan refund terposting. Penjualan pada tanggal lunas; refund pada tanggal refund. DP dan nota belum lunas tidak diakui sebagai omzet.</p><?php if($s['available']): ?><div class="rw-balance"><?php foreach(['billing'=>'Tagihan sebelum refund','tax'=>'- Pajak penjualan','refund'=>'- Refund periode','value'=>'= Omzet POS neto'] as $key=>$label): ?><div><span><?= $label ?></span><strong><?= $money($s['totals'][$key]) ?></strong></div><?php endforeach ?></div><div class="rw-table-wrap"><table class="rw-summary-table"><thead><tr><th>Tanggal pengakuan</th><th>Dokumen</th><th>Nota POS</th><th>Jenis</th><th>Tagihan</th><th>Pajak</th><th>Refund</th><th>Omzet neto</th></tr></thead><tbody><?php foreach($s['pager']['rows'] as $row): ?><tr><td><?= $esc($row['event_date']) ?></td><td><?= $esc($row['document_no']) ?></td><td><?php if($can_pos): ?><a href="<?= $esc(site_url('pos/reports/sales/'.(int)$row['order_id'])) ?>"><?= $esc($row['order_no']) ?></a><?php else: ?><?= $esc($row['order_no']) ?><?php endif ?></td><td><?= $row['event_type']==='SALE'?'Penjualan':'Refund' ?></td><?php foreach(['billing','tax','refund','value'] as $key): ?><td class="rw-num"><?= $number($row[$key]) ?></td><?php endforeach ?></tr><?php endforeach ?></tbody></table></div><?php $savedPager=$r['pager'];$r['pager']=$s['pager'];require __DIR__.'/_pager.php';$r['pager']=$savedPager; ?><?php if(!$s['pager']['count']): ?><p class="rw-empty">Tidak ada penjualan / refund untuk periode ini.</p><?php endif ?><?php endif ?></article>
  <?php elseif($f['view']==='reconcile'): require __DIR__.'/_financial_reconciliation.php'; ?>
  <?php elseif($operational): require __DIR__.'/_financial_inventory.php'; ?>
  <?php elseif($f['view']==='balances'): require __DIR__.'/_financial_balances.php'; ?>
  <?php else: ?>
    <article class="rw-panel"><h2>Rincian mutasi keuangan</h2><p class="rw-sub">Pada tanggal uang bergerak. Transaksi asli dan pembalik tetap ditampilkan untuk menjaga jejak saldo.</p><div class="rw-table-wrap"><table class="rw-detail-table"><thead><tr><th>Tanggal / Mutasi</th><th>Rekening</th><th>Kelompok / Sumber</th><th>Arah</th><th>Nominal</th><th>Dokumen / Referensi</th><th>Catatan & Jejak sumber</th></tr></thead><tbody><?php foreach($r['pager']['rows'] as $row): ?><tr>
      <td><small><?= $esc($row['mutation_date']) ?></small><strong><?= $esc($row['mutation_no']) ?></strong><?php if($row['reversal_of_mutation_id']): ?><small>Pembalik mutasi #<?= (int)$row['reversal_of_mutation_id'] ?></small><?php endif ?></td><td><?= $esc($row['account_name']) ?><small><?= $esc($row['currency_code']) ?></small></td><td><?= $esc($row['category_name']) ?><small><?= $esc($row['flow_name']) ?></small></td><td><span class="rw-pill <?= $row['mutation_type']==='OUT'?'out':'' ?>"><?= $row['mutation_type']==='IN'?'MASUK':'KELUAR' ?></span></td><td class="rw-num"><?= $money($row['amount_cents']) ?></td>
      <td><?php if($row['purchase_order_id'] && $can_purchase): ?><a href="<?= $esc(site_url('purchase-orders/detail/'.(int)$row['purchase_order_id'])) ?>"><?= $esc($row['po_no']) ?></a><?php else: ?><?= $esc($row['po_no']?:($row['document_no']?:'-')) ?><?php endif ?><small><?= $esc($row['ref_module']) ?></small></td><td><?= $esc($row['notes']) ?><details><summary>Jejak sumber</summary><small><?= $esc($row['ref_table']?:'Mutasi manual') ?> #<?= (int)$row['ref_id'] ?></small><small>Saldo sebelum: <?= $number($row['balance_before']) ?> / sesudah: <?= $number($row['balance_after']) ?></small></details></td>
    </tr><?php endforeach ?></tbody></table></div><?php require __DIR__.'/_pager.php'; ?><?php if(!$t['count']): ?><p class="rw-empty">Tidak ada mutasi sesuai filter.</p><?php endif ?></article>
  <?php endif ?>
  <details class="rw-guide"><summary>Panduan & dasar perhitungan</summary><p>Pilih rentang 1-12 bulan. Bulan fokus mengatur kartu, rekap harian, dan rincian; tabel perbandingan serta grafik bulanan selalu memakai seluruh rentang. Klik nominal bulan untuk melihat sumber transaksi. Grafik sumber dapat diganti melalui pilihan sumber atau tombol tren pada tiap baris.</p><p>Omzet POS neto memakai basis laporan keuangan POS: nota lunas sebelum refund dikurangi pajak dan refund terposting pada periode refund. Nota batal, draft, belum lunas, dan DP belum menjadi omzet. Pembayaran split tidak menggandakan nota. Omzet bukan penerimaan kas POS dan tidak dijumlahkan lagi ke total mutasi kas.</p><p>Pengeluaran usaha adalah arus keluar pembelian, payroll selain kasbon, serta biaya manual terklasifikasi. Utang, piutang/kasbon, modal/prive, DP, refund POS, koreksi, dan transfer dipisahkan. Retur/pembalik purchase masuk tetap terpisah dari pembelian keluar, bukan omzet. Pembelian persediaan/aset tidak otomatis menjadi beban akrual; selisih omzet dan pengeluaran kas bukan laba.</p><p>Arus kas bersumber dari fin_account_mutation_log; tidak menjumlahkan PO, SR, atau nota lagi sebagai kas. Transaksi asli dan pembalik ada di tanggal masing-masing. Bulan berjalan hanya sampai hari ini dan ditandai belum penuh. Selisih pada tabel antarbulan memakai realisasi bulan tersebut; kartu membandingkan jumlah hari yang sama untuk bulan berjalan. Angka nol berbeda dari omzet yang tidak tersedia.</p><p>CSV perbandingan mengikuti rentang dan filter kas. CSV mutasi / omzet mengikuti bulan fokus serta tanggal rincian. Hak akses ekspor dan dokumen sumber tetap diperiksa.</p></details>
  <?php endif ?>
</section>
