<?php $edit=(array)($edit_schedule??[]); $canSave=$edit?!empty($can_edit):!empty($can_create); ?>
<div class="container-xxl py-3">
  <h4 class="fw-bold mb-1"><i class="ri-send-plane-line me-1"></i>Jadwal & Delivery Telegram</h4><p class="text-muted small">Scheduler harian Asia/Jakarta; antrean memakai idempotency key dan lease.</p>
  <?php if ($flash=$this->session->flashdata('success')): ?><div class="alert alert-success"><?= html_escape($flash) ?></div><?php endif; ?><?php if ($flash=$this->session->flashdata('error')): ?><div class="alert alert-danger"><?= html_escape($flash) ?></div><?php endif; ?>
  <div class="row g-3 mb-3"><div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-header fw-semibold"><?= $edit?'Edit jadwal':'Tambah jadwal' ?></div><div class="card-body">
    <?php if ($canSave): ?><form method="post" action="<?= site_url('telegram/schedule_save') ?>"><input type="hidden" name="tg_schedule_csrf" value="<?= html_escape($schedule_csrf??'') ?>"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>">
      <div class="mb-2"><label class="form-label">Nama</label><input class="form-control" name="schedule_name" maxlength="120" required value="<?= html_escape($edit['schedule_name']??'') ?>"></div>
      <div class="mb-2"><label class="form-label">Target aktif</label><select class="form-select" name="target_id" required><option value="">Pilih</option><?php foreach ((array)$targets as $target): ?><option value="<?= (int)$target['id'] ?>" <?= (int)($edit['target_id']??0)===(int)$target['id']?'selected':'' ?>><?= html_escape($target['title']) ?></option><?php endforeach; ?></select></div>
      <div class="row g-2"><div class="col-7"><label class="form-label">Laporan</label><select class="form-select" name="report_type"><?php foreach ((array)$report_types as $value=>$label): ?><option value="<?= html_escape($value) ?>" <?= ($edit['report_type']??'')===$value?'selected':'' ?>><?= html_escape($label) ?></option><?php endforeach; ?></select></div><div class="col-5"><label class="form-label">Jam</label><input class="form-control" type="time" name="send_time" required value="<?= html_escape(substr((string)($edit['send_time']??'08:00'),0,5)) ?>"></div></div>
      <div class="form-check my-3"><input type="hidden" name="is_active" value="0"><input class="form-check-input" id="schedule-active" type="checkbox" name="is_active" value="1" <?= !isset($edit['is_active'])||!empty($edit['is_active'])?'checked':'' ?>><label class="form-check-label" for="schedule-active">Aktif</label></div><button class="btn btn-primary">Simpan jadwal</button><?php if($edit): ?><a class="btn btn-link" href="<?= site_url('telegram/delivery') ?>">Batal</a><?php endif; ?>
    </form><?php else: ?><p class="text-muted mb-0">Akses lihat saja.</p><?php endif; ?>
  </div></div></div><div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header fw-semibold">Jadwal</div><div class="table-responsive"><table class="table table-sm mb-0"><thead><tr><th>Nama</th><th>Target</th><th>Laporan</th><th>Jam</th><th>Status</th><th></th></tr></thead><tbody><?php foreach((array)$schedules as $row): ?><tr><td><?= html_escape($row['schedule_name']) ?></td><td><?= html_escape($row['target_title']) ?></td><td><?= html_escape($row['report_type']) ?></td><td><?= html_escape(substr($row['send_time'],0,5)) ?></td><td><?= !empty($row['is_active'])&& !empty($row['target_active'])?'Aktif':'Nonaktif' ?></td><td><?php if(!empty($can_edit)): ?><a class="btn btn-outline-secondary btn-sm" href="<?= site_url('telegram/delivery?edit='.(int)$row['id']) ?>">Edit</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
  <div class="card border-0 shadow-sm"><div class="card-header fw-semibold">100 antrean terbaru</div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>ID</th><th>Sumber</th><th>Target</th><th>Laporan</th><th>Status</th><th>Percobaan</th><th>Waktu</th></tr></thead><tbody><?php foreach((array)$queue_rows as $row): ?><tr><td><?= (int)$row['id'] ?></td><td><?= html_escape($row['source_type']) ?></td><td><?= html_escape($row['target_title']) ?></td><td><?= html_escape($row['report_type']??'-') ?></td><td><span class="badge <?= $row['status']==='SENT'?'bg-success':($row['status']==='UNKNOWN'?'bg-warning text-dark':'bg-secondary') ?>"><?= html_escape($row['status']) ?></span></td><td><?= (int)$row['attempt_count'] ?>/<?= (int)$row['max_attempts'] ?></td><td><?= html_escape($row['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
</div>
