CREATE TABLE IF NOT EXISTS inv_component_lot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  location_type VARCHAR(20) NOT NULL,
  division_id BIGINT UNSIGNED NULL,
  component_id BIGINT UNSIGNED NOT NULL,
  uom_id BIGINT UNSIGNED NOT NULL,
  lot_no VARCHAR(64) NOT NULL,
  receipt_date DATE NOT NULL,
  expiry_date DATE NULL,
  unit_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
  qty_in_total DECIMAL(18,4) NOT NULL DEFAULT 0,
  qty_out_total DECIMAL(18,4) NOT NULL DEFAULT 0,
  qty_balance DECIMAL(18,4) NOT NULL DEFAULT 0,
  source_module VARCHAR(50) NULL,
  source_table VARCHAR(100) NULL,
  source_id BIGINT UNSIGNED NULL,
  source_line_id BIGINT UNSIGNED NULL,
  parent_lot_id BIGINT UNSIGNED NULL,
  last_issue_at DATETIME NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_inv_component_lot_scope (location_type, division_id, component_id, uom_id, lot_no),
  KEY idx_inv_component_lot_source (source_table, source_id, source_line_id),
  KEY idx_inv_component_lot_open (location_type, division_id, component_id, uom_id, status, receipt_date),
  KEY idx_inv_component_lot_component (component_id, receipt_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inv_component_lot_issue_log (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  issue_no VARCHAR(32) NOT NULL,
  issue_date DATE NOT NULL,
  issue_datetime DATETIME NOT NULL,
  location_type VARCHAR(20) NOT NULL,
  division_id BIGINT UNSIGNED NULL,
  component_id BIGINT UNSIGNED NOT NULL,
  uom_id BIGINT UNSIGNED NOT NULL,
  issue_qty DECIMAL(18,4) NOT NULL DEFAULT 0,
  total_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  source_module VARCHAR(50) NULL,
  source_table VARCHAR(100) NULL,
  source_id BIGINT UNSIGNED NULL,
  source_line_id BIGINT UNSIGNED NULL,
  notes TEXT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'POSTED',
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_inv_component_lot_issue_no (issue_no),
  KEY idx_inv_component_lot_issue_source (source_table, source_id, source_line_id),
  KEY idx_inv_component_lot_issue_main (location_type, division_id, component_id, uom_id, issue_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS inv_component_lot_issue_line (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  issue_id BIGINT UNSIGNED NOT NULL,
  lot_id BIGINT UNSIGNED NOT NULL,
  qty_out DECIMAL(18,4) NOT NULL DEFAULT 0,
  unit_cost DECIMAL(18,6) NOT NULL DEFAULT 0,
  total_cost DECIMAL(18,2) NOT NULL DEFAULT 0,
  source_balance_before DECIMAL(18,4) NULL,
  source_balance_after DECIMAL(18,4) NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id),
  KEY idx_inv_component_lot_issue_line_issue (issue_id),
  KEY idx_inv_component_lot_issue_line_lot (lot_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;