START TRANSACTION;

ALTER TABLE wa_broadcast
  ADD COLUMN IF NOT EXISTS media_path VARCHAR(500) DEFAULT NULL AFTER custom_message,
  ADD COLUMN IF NOT EXISTS media_url VARCHAR(500) DEFAULT NULL AFTER media_path,
  ADD COLUMN IF NOT EXISTS media_mime VARCHAR(100) DEFAULT NULL AFTER media_url,
  ADD COLUMN IF NOT EXISTS media_name VARCHAR(255) DEFAULT NULL AFTER media_mime;

COMMIT;
