<?php
$canEdit = !empty($can_edit);
$generalPayload = (array)(($general['payload'] ?? []));
$stationRows = (array)($stations ?? []);
$stationReady = !empty($station_ready);
$outletRows = (array)($outlets ?? []);
?>
<style>
  .review-admin-stars{letter-spacing:.08em;color:#d98700;font-weight:800}.review-admin-comment{max-width:360px;white-space:normal;color:#6f5c54;font-size:.84rem;line-height:1.4}.review-admin-grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(320px,.95fr);gap:1rem;margin-bottom:1rem}.review-qr-card{height:100%}.review-qr-status{display:flex;align-items:center;justify-content:space-between;gap:.8rem;margin:.6rem 0 1rem;padding:.7rem .8rem;border-radius:11px;background:#fbf5f1;border:1px solid #ecdcd4;font-size:.85rem}.review-station-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(215px,1fr));gap:.75rem}.review-station{position:relative;min-height:100%;padding:.9rem;border:1px solid #e8d7ce;border-radius:14px;background:linear-gradient(145deg,#fff,#fcf5f0)}.review-station-top{display:flex;align-items:flex-start;justify-content:space-between;gap:.5rem}.review-station-title{font-size:.95rem;font-weight:800;color:#493631}.review-station-meta{margin-top:.25rem;color:#87726a;font-size:.76rem;line-height:1.35}.review-station-qr{display:grid;width:94px;height:94px;margin:.8rem auto .6rem;padding:5px;place-items:center;border:1px solid #ecd9cf;border-radius:10px;background:#fff}.review-station-qr img,.review-station-qr canvas{display:none!important}.review-station-qr [data-pos-qr-visual="true"]{display:block!important;width:100%!important;height:100%!important;image-rendering:pixelated}.review-station-actions{display:flex;justify-content:center;gap:.45rem;margin-top:.55rem}.review-empty{padding:1rem;border:1px dashed #dfc9bd;border-radius:12px;color:#806b63;font-size:.85rem;background:#fffaf7}.review-modal-backdrop{display:none;position:fixed;inset:0;z-index:1070;align-items:center;justify-content:center;padding:1rem;background:rgba(34,27,28,.48)}.review-modal-backdrop.is-open{display:flex}.review-modal{width:min(100%,560px);max-height:min(88vh,760px);overflow:auto;border-radius:20px;background:#fff;padding:1.15rem;box-shadow:0 22px 60px rgba(0,0,0,.25)}.review-modal h5{margin:0}.review-modal-close{border:0;background:transparent;font-size:1.35rem;color:#6f5d57}.review-qr-big{width:180px;height:180px;display:grid;margin:1rem auto;padding:8px;place-items:center;border:1px solid #ecd8ce;border-radius:16px;background:#fff}.review-qr-big img,.review-qr-big canvas{display:none!important}.review-qr-big [data-pos-qr-visual="true"]{display:block!important;width:100%!important;height:100%!important;image-rendering:pixelated}.review-list-source{display:block;margin-top:.2rem;color:#9a8178;font-size:.72rem;font-weight:700;text-transform:uppercase;letter-spacing:.05em}@media(max-width:991.98px){.review-admin-grid{grid-template-columns:1fr}}
</style>
<div class="container-xxl py-3 print-config-page">
  <div class="fin-page-header mb-3"><div><div class="print-config-kicker">Feedback customer</div><h4 class="fin-page-title mb-1">Ulasan Pelanggan</h4><p class="fin-page-subtitle mb-0">Kelola QR pada struk, QR yang bisa ditempel di outlet, dan ulasan yang diterima dalam satu tempat.</p></div></div>
  <?php $this->load->view('pos/_printer_config_common', ['printer_config_tab' => 'reviews']); ?>

  <div class="review-admin-grid">
    <section class="card print-config-card review-qr-card"><div class="card-body">
      <div class="d-flex align-items-start justify-content-between gap-2"><div><div class="print-config-kicker">QR pada struk</div><h5 class="mb-1">Ajak customer memberi ulasan setelah bayar</h5><p class="small text-muted mb-0">Setiap nota memperoleh QR unik. Ulasan dari QR ini tertaut langsung pada nota dan customer bila tersedia.</p></div><span id="receipt-qr-status" class="print-config-status <?= !empty($generalPayload['customer_review_qr_enabled']) ? 'active' : 'inactive' ?>"><?= !empty($generalPayload['customer_review_qr_enabled']) ? 'Aktif' : 'Nonaktif' ?></span></div>
      <div class="review-qr-status"><span>Aktifkan sumber QR di sini. Lalu, pada layout <strong>Struk Pembayaran</strong>, centang <em>QR ulasan pelanggan</em>.</span><a class="btn btn-outline-secondary btn-sm" href="<?= site_url('pos/printers/layouts') ?>">Buka layout</a></div>
      <?php if ($canEdit): ?><form id="receipt-review-settings"><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" role="switch" id="receipt-review-enabled" <?= !empty($generalPayload['customer_review_qr_enabled']) ? 'checked' : '' ?>><label class="form-check-label fw-semibold" for="receipt-review-enabled">Tampilkan QR ulasan pada struk pembayaran yang layout-nya mengizinkan</label></div><label class="form-label" for="receipt-review-message">Pesan di atas QR</label><input class="form-control" id="receipt-review-message" value="<?= html_escape((string)($generalPayload['customer_review_message'] ?? 'Bagikan ulasan Anda dengan scan QR berikut.')) ?>" maxlength="255"><div class="d-flex justify-content-end mt-3"><button class="btn btn-primary" type="submit"><?php $this->load->view('pos/_icon', ['name' => 'save', 'label' => '']); ?><span class="ms-1">Simpan QR Struk</span></button></div></form><?php else: ?><div class="print-config-note mt-3">Akses Anda hanya untuk melihat pengaturan QR struk.</div><?php endif; ?>
    </div></section>
    <section class="card print-config-card review-qr-card"><div class="card-body">
      <div class="print-config-kicker">QR untuk area pengunjung</div><h5 class="mb-1">Cetak QR untuk meja, pintu masuk, atau kasir</h5><p class="small text-muted">QR ini tidak memerlukan nota. Pengunjung mengisi ulasan dan dapat langsung dihubungkan sebagai Member Namua melalui WhatsApp.</p>
      <?php if (!$stationReady): ?><div class="review-empty">Fitur QR area belum tersedia pada database ini. Minta admin memeriksa migrasi resmi yang sesuai dengan versi aplikasi, lalu muat ulang halaman.</div><?php else: ?><div class="review-station-grid" id="review-station-grid"><?php foreach ($stationRows as $station): $stationUrl = site_url('review/station/' . rawurlencode((string)$station['station_code'])); ?><article class="review-station"><div class="review-station-top"><div><div class="review-station-title"><?= html_escape((string)$station['station_name']) ?></div><div class="review-station-meta"><?= html_escape((string)($station['outlet_name'] ?? 'Semua outlet')) ?><br><?= html_escape((string)$station['station_code']) ?></div></div><span class="print-config-status <?= !empty($station['is_active']) ? 'active' : 'inactive' ?>"><?= !empty($station['is_active']) ? 'Aktif' : 'Nonaktif' ?></span></div><div class="review-station-qr" data-review-station-qr="<?= html_escape($stationUrl) ?>" role="img" aria-label="QR <?= html_escape((string)$station['station_name']) ?>"></div><div class="review-station-actions"><button type="button" class="btn btn-outline-secondary print-config-icon-btn" data-station-preview='<?= html_escape(json_encode($station, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), true) ?>' title="Lihat QR" aria-label="Lihat QR"><?php $this->load->view('pos/_icon', ['name' => 'eye', 'label' => 'Lihat QR']); ?></button><a class="btn btn-outline-secondary print-config-icon-btn" href="<?= site_url('pos/customer-reviews/stations/print/' . (int)$station['id']) ?>" target="_blank" title="Cetak QR" aria-label="Cetak QR"><?php $this->load->view('pos/_icon', ['name' => 'print', 'label' => 'Cetak QR']); ?></a><?php if ($canEdit): ?><button type="button" class="btn btn-outline-secondary print-config-icon-btn" data-station-edit='<?= html_escape(json_encode($station, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES), true) ?>' title="Edit QR area" aria-label="Edit QR area"><?php $this->load->view('pos/_icon', ['name' => 'edit', 'label' => 'Edit QR area']); ?></button><button type="button" class="btn btn-outline-secondary print-config-icon-btn <?= !empty($station['is_active']) ? 'is-danger' : 'is-success' ?>" data-station-toggle="<?= (int)$station['id'] ?>" title="<?= !empty($station['is_active']) ? 'Nonaktifkan QR' : 'Aktifkan QR' ?>" aria-label="Ubah status QR"><?php $this->load->view('pos/_icon', ['name' => 'power', 'label' => 'Ubah status']); ?></button><?php endif; ?></div></article><?php endforeach; ?></div><?php if ($canEdit): ?><div class="d-flex justify-content-end mt-3"><button type="button" class="btn btn-outline-primary" id="add-review-station"><?php $this->load->view('pos/_icon', ['name' => 'plus', 'label' => '']); ?><span class="ms-1">Tambah QR Area</span></button></div><?php endif; ?><?php endif; ?>
    </div></section>
  </div>

  <section class="card print-config-card"><div class="card-body">
    <div class="d-flex align-items-center justify-content-between gap-2 flex-wrap mb-3"><div><div class="print-config-kicker">Masukan yang diterima</div><h5 class="mb-0">Daftar Ulasan</h5></div><span class="small text-muted">Ulasan struk dan QR area tampil bersama, dengan sumber yang jelas.</span></div>
    <div class="print-config-toolbar mb-3"><div class="form-group"><label>Cari ulasan</label><input id="review-q" class="form-control" placeholder="Nota, customer, outlet, area, atau isi ulasan"></div><div class="form-group"><label>Status</label><select id="review-status" class="form-select"><option value="ALL">Semua status</option><option value="OPEN">Belum diisi</option><option value="SUBMITTED">Sudah masuk</option><option value="HIDDEN">Disembunyikan</option></select></div><div class="form-group"><label>Dari tanggal</label><input id="review-date-from" class="form-control" type="date"></div><div class="form-group"><label>Sampai tanggal</label><input id="review-date-to" class="form-control" type="date"></div><div class="form-group" style="max-width:130px"><label>Baris</label><select id="review-limit" class="form-select"><option>10</option><option selected>25</option><option>50</option></select></div><button class="btn btn-primary print-config-action" id="review-filter"><?php $this->load->view('pos/_icon', ['name' => 'search', 'label' => '']); ?><span class="ms-1">Terapkan</span></button><button class="btn btn-outline-secondary print-config-icon-btn" id="review-clear" title="Clear filter" aria-label="Clear filter"><?php $this->load->view('pos/_icon', ['name' => 'clear', 'label' => 'Clear filter']); ?></button></div>
    <div class="print-config-table-wrap"><table class="table table-hover print-config-table"><thead><tr><th>Waktu / Sumber</th><th>Customer / Outlet</th><th>Rating</th><th>Ulasan</th><th>Status</th><th class="text-center">Aksi</th></tr></thead><tbody id="review-body"></tbody></table></div><div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mt-3" id="review-pager"></div>
  </div></section>
</div>

<div class="review-modal-backdrop" id="review-station-modal" aria-hidden="true"><section class="review-modal"><div class="d-flex justify-content-between align-items-start gap-2 mb-3"><div><div class="print-config-kicker">QR area pengunjung</div><h5 id="review-station-modal-title">Tambah QR Area</h5></div><button type="button" class="review-modal-close" data-close-review-modal aria-label="Tutup">&times;</button></div><form id="review-station-form"><input type="hidden" id="station-id" name="id"><div class="row g-3"><div class="col-md-7"><label class="form-label">Nama area</label><input class="form-control" id="station-name" name="station_name" required maxlength="150" placeholder="Contoh: Meja kasir"></div><div class="col-md-5"><label class="form-label">Kode QR</label><input class="form-control" id="station-code" name="station_code" maxlength="60" placeholder="Dibuat otomatis bila kosong"></div><div class="col-12"><label class="form-label">Outlet</label><select class="form-select" id="station-outlet" name="outlet_id"><option value="0">Semua outlet</option><?php foreach ($outletRows as $outlet): ?><option value="<?= (int)$outlet['id'] ?>"><?= html_escape((string)$outlet['outlet_name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><label class="form-label">Catatan lokasi</label><input class="form-control" id="station-notes" name="notes" maxlength="255" placeholder="Contoh: Tempel di meja kasir"></div><div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" role="switch" id="station-active" name="is_active" value="1" checked><label class="form-check-label fw-semibold" for="station-active">QR siap dipindai pengunjung</label></div></div></div><div class="d-flex justify-content-end gap-2 mt-4"><button type="button" class="btn btn-light" data-close-review-modal>Batal</button><button type="submit" class="btn btn-primary"><?php $this->load->view('pos/_icon', ['name' => 'save', 'label' => '']); ?><span class="ms-1">Simpan QR Area</span></button></div></form></section></div>
<div class="review-modal-backdrop" id="review-qr-preview-modal" aria-hidden="true"><section class="review-modal text-center"><div class="d-flex justify-content-between align-items-start gap-2"><div class="text-start"><div class="print-config-kicker">QR siap cetak</div><h5 id="review-qr-preview-title">QR Ulasan</h5></div><button type="button" class="review-modal-close" data-close-qr-modal aria-label="Tutup">&times;</button></div><div class="review-qr-big" id="review-qr-preview-image" role="img" aria-label="QR ulasan"></div><p class="small text-muted mb-2" id="review-qr-preview-meta"></p><a id="review-qr-print-link" class="btn btn-primary" target="_blank"><?php $this->load->view('pos/_icon', ['name' => 'print', 'label' => '']); ?><span class="ms-1">Buka Versi Cetak</span></a></section></div>

<script src="<?= base_url('assets/vendor/qrcodejs/qrcode.min.js') ?>"></script>
<script src="<?= base_url('assets/js/pos-local-qr.js') ?>?v=20260825g"></script>
<script>
document.addEventListener('DOMContentLoaded', function () {
  const ui = window.PrinterConfigUI; const canEdit = <?= $canEdit ? 'true' : 'false' ?>; const endpoint = '<?= site_url('pos/customer-reviews') ?>'; const body = document.getElementById('review-body'); const state = {q: '', status: 'ALL', date_from: '', date_to: '', page: 1, limit: 25};
  const reviewCsrf = <?= json_encode((string)($customer_review_csrf_token ?? ''), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
  const reviewCsrfHeader = <?= json_encode((string)($customer_review_csrf_header ?? ''), JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) ?>;
  async function postReview(path, payload) {
    if (!canEdit || !/^[a-f0-9]{64}$/.test(reviewCsrf) || reviewCsrfHeader !== 'X-Pos-Review-Csrf') {
      throw new Error('Sesi formulir ulasan tidak tersedia. Muat ulang halaman lalu coba kembali.');
    }
    const target = new URL(endpoint + path, window.location.href);
    if (target.origin !== window.location.origin) throw new Error('Alamat aplikasi tidak sesuai. Hubungi admin.');
    const response = await fetch(target.href, {
      method: 'POST', credentials: 'same-origin', mode: 'same-origin', redirect: 'error',
      headers: {'X-Requested-With': 'XMLHttpRequest', 'Content-Type': 'application/json', [reviewCsrfHeader]: reviewCsrf},
      body: JSON.stringify(payload || {})
    });
    const raw = await response.text();
    let result;
    try { result = JSON.parse(raw); } catch (error) {
      throw new Error('Jawaban server tidak dapat dibaca. Periksa sesi login lalu muat ulang halaman.');
    }
    if (!result || !response.ok || !result.ok) throw new Error((result && result.message) || 'Perubahan ulasan belum dapat disimpan.');
    return result;
  }
   function renderQr(container, url, size, label) { if (!container) return false; if (window.PosLocalQr && window.PosLocalQr.render(container, url, {size: size, label: label})) return true; container.textContent = 'QR belum dapat dimuat. Muat ulang halaman.'; return false; }
   document.querySelectorAll('[data-review-station-qr]').forEach(function (container) { renderQr(container, container.getAttribute('data-review-station-qr'), 220, container.getAttribute('aria-label') || 'QR ulasan pelanggan'); });
  function query() { return new URLSearchParams({review_q: state.q, review_status: state.status, review_date_from: state.date_from, review_date_to: state.date_to, review_page: state.page, review_limit: state.limit}).toString(); }
  function controls() { document.getElementById('review-q').value = state.q; document.getElementById('review-status').value = state.status; document.getElementById('review-date-from').value = state.date_from; document.getElementById('review-date-to').value = state.date_to; document.getElementById('review-limit').value = state.limit; }
  function badge(status) { const value = String(status || 'OPEN').toUpperCase(); const css = value === 'SUBMITTED' ? 'active' : (value === 'HIDDEN' ? 'inactive' : 'generated'); const text = value === 'SUBMITTED' ? 'Sudah masuk' : (value === 'HIDDEN' ? 'Disembunyikan' : 'Belum diisi'); return '<span class="print-config-status ' + css + '">' + text + '</span>'; }
  function stars(rating) { const n = Math.max(0, Math.min(5, Number(rating || 0))); return n ? '<span class="review-admin-stars">' + '&#9733;'.repeat(n) + '</span><span class="text-muted"> ' + n + '/5</span>' : '-'; }
  function actions(row) { if (!canEdit || String(row.review_status) === 'OPEN') return '-'; const hidden = String(row.review_status) === 'HIDDEN'; const title = hidden ? 'Tampilkan kembali ulasan' : 'Sembunyikan ulasan'; return '<button class="btn btn-outline-secondary print-config-icon-btn ' + (hidden ? 'is-success' : 'is-danger') + '" data-visibility="' + Number(row.id) + '" data-hidden="' + (hidden ? '0' : '1') + '" title="' + title + '" aria-label="' + title + '">' + ui.icon(hidden ? 'eye' : 'power', title) + '</button>'; }
  function source(row) { return String(row.review_source || 'RECEIPT') === 'STATION' ? 'QR area: ' + String(row.station_name || row.station_code || '-') : 'QR pada struk: ' + String(row.order_no_snapshot || row.order_no_live || '-'); }
  async function load() { controls(); const json = await ui.get(endpoint + '/data?' + query()); body.innerHTML = (json.rows || []).map(function (row) { const date = row.submitted_at || row.created_at || '-'; const customer = row.customer_name_snapshot || row.member_name || 'Walk in'; const comment = row.review_text ? ui.escapeHtml(row.review_text) : '<span class="muted">Belum ada isi ulasan.</span>'; return '<tr><td><strong>' + ui.escapeHtml(date) + '</strong><span class="review-list-source">' + ui.escapeHtml(source(row)) + '</span></td><td><strong>' + ui.escapeHtml(customer) + '</strong><div class="muted">' + ui.escapeHtml(row.outlet_name || '-') + '</div></td><td>' + stars(row.rating) + '</td><td><div class="review-admin-comment">' + comment + '</div></td><td>' + badge(row.review_status) + '</td><td class="text-center">' + actions(row) + '</td></tr>'; }).join('') || '<tr><td colspan="6" class="print-config-empty">Belum ada ulasan yang sesuai filter.</td></tr>'; ui.pager(document.getElementById('review-pager'), json.meta || {}, state, load); }
  document.getElementById('review-filter').addEventListener('click', function () { state.q = document.getElementById('review-q').value.trim(); state.status = document.getElementById('review-status').value; state.date_from = document.getElementById('review-date-from').value; state.date_to = document.getElementById('review-date-to').value; state.limit = Number(document.getElementById('review-limit').value); state.page = 1; load().catch(function (error) { ui.notice('error', 'Ulasan tidak dapat dimuat', error.message); }); });
  document.getElementById('review-clear').addEventListener('click', function () { state.q = ''; state.status = 'ALL'; state.date_from = ''; state.date_to = ''; state.page = 1; load().catch(function (error) { ui.notice('error', 'Ulasan tidak dapat dimuat', error.message); }); });
  body.addEventListener('click', async function (event) { const button = event.target.closest('[data-visibility]'); if (!button) return; const hidden = Number(button.dataset.hidden || 0) === 1; const action = hidden ? 'menyembunyikan' : 'menampilkan kembali'; if (!window.confirm('Yakin ingin ' + action + ' ulasan ini?')) return; try { await postReview('/visibility/' + Number(button.dataset.visibility), {hidden: hidden ? 1 : 0, reason: hidden ? 'Disembunyikan moderator melalui halaman ulasan.' : ''}); await load(); ui.notice('success', hidden ? 'Ulasan disembunyikan' : 'Ulasan ditampilkan', 'Status ulasan sudah diperbarui.'); } catch (error) { ui.notice('error', 'Status ulasan gagal diubah', error.message); } });
  const settings = document.getElementById('receipt-review-settings'); if (settings) settings.addEventListener('submit', async function (event) { event.preventDefault(); try { await postReview('/settings', {customer_review_qr_enabled: document.getElementById('receipt-review-enabled').checked ? 1 : 0, customer_review_message: document.getElementById('receipt-review-message').value.trim()}); const enabled = document.getElementById('receipt-review-enabled').checked; const badgeEl = document.getElementById('receipt-qr-status'); badgeEl.textContent = enabled ? 'Aktif' : 'Nonaktif'; badgeEl.className = 'print-config-status ' + (enabled ? 'active' : 'inactive'); ui.notice('success', 'Pengaturan QR struk disimpan', enabled ? 'QR akan muncul pada struk yang layout-nya mengizinkan.' : 'QR tidak akan muncul sampai diaktifkan kembali.'); } catch (error) { ui.notice('error', 'Pengaturan QR belum tersimpan', error.message); } });
  const stationModal = document.getElementById('review-station-modal'); const qrModal = document.getElementById('review-qr-preview-modal'); const stationForm = document.getElementById('review-station-form'); function openStation(data) { stationForm.reset(); document.getElementById('station-id').value = data.id || ''; document.getElementById('station-name').value = data.station_name || ''; document.getElementById('station-code').value = data.station_code || ''; document.getElementById('station-outlet').value = String(data.outlet_id || 0); document.getElementById('station-notes').value = data.notes || ''; document.getElementById('station-active').checked = data.is_active === undefined ? true : Number(data.is_active) === 1; document.getElementById('review-station-modal-title').textContent = data.id ? 'Edit QR Area' : 'Tambah QR Area'; stationModal.classList.add('is-open'); stationModal.setAttribute('aria-hidden', 'false'); document.getElementById('station-name').focus(); } function closeStation() { stationModal.classList.remove('is-open'); stationModal.setAttribute('aria-hidden', 'true'); } function closeQr() { qrModal.classList.remove('is-open'); qrModal.setAttribute('aria-hidden', 'true'); }
  const addStation = document.getElementById('add-review-station'); if (addStation) addStation.addEventListener('click', function () { openStation({}); }); document.querySelectorAll('[data-close-review-modal]').forEach(function (button) { button.addEventListener('click', closeStation); }); document.querySelectorAll('[data-close-qr-modal]').forEach(function (button) { button.addEventListener('click', closeQr); }); stationModal.addEventListener('click', function (event) { if (event.target === stationModal) closeStation(); }); qrModal.addEventListener('click', function (event) { if (event.target === qrModal) closeQr(); });
  document.querySelectorAll('[data-station-edit]').forEach(function (button) { button.addEventListener('click', function () { openStation(JSON.parse(button.dataset.stationEdit)); }); }); document.querySelectorAll('[data-station-preview]').forEach(function (button) { button.addEventListener('click', function () { const data = JSON.parse(button.dataset.stationPreview); const url = '<?= site_url('review/station/') ?>' + encodeURIComponent(String(data.station_code)); document.getElementById('review-qr-preview-title').textContent = String(data.station_name); document.getElementById('review-qr-preview-meta').textContent = String(data.outlet_name || 'Semua outlet') + ' - ' + String(data.station_code); renderQr(document.getElementById('review-qr-preview-image'), url, 520, 'QR ulasan ' + String(data.station_name)); document.getElementById('review-qr-print-link').href = endpoint + '/stations/print/' + Number(data.id); qrModal.classList.add('is-open'); qrModal.setAttribute('aria-hidden', 'false'); }); });
  if (stationForm) stationForm.addEventListener('submit', async function (event) { event.preventDefault(); if (!stationForm.reportValidity()) return; const submit = stationForm.querySelector('[type="submit"]'); submit.disabled = true; try { const data = ui.formObject(stationForm); data.is_active = document.getElementById('station-active').checked ? 1 : 0; await postReview('/stations/save', data); ui.notice('success', 'QR area disimpan', 'QR siap dilihat dan dicetak.'); window.setTimeout(function () { window.location.reload(); }, 350); } catch (error) { ui.notice('error', 'QR area belum tersimpan', error.message); } finally { submit.disabled = false; } });
  document.querySelectorAll('[data-station-toggle]').forEach(function (button) { button.addEventListener('click', async function () { try { await postReview('/stations/toggle/' + Number(button.dataset.stationToggle), {}); window.location.reload(); } catch (error) { ui.notice('error', 'Status QR belum diubah', error.message); } }); });
  load().catch(function (error) { body.innerHTML = '<tr><td colspan="6" class="print-config-empty">' + ui.escapeHtml(error.message) + '</td></tr>'; });
});
</script>
