<?php
$options = is_array($printer_options ?? null) ? $printer_options : [];
$events = (array)($event_types ?? []);
$documents = (array)($document_types ?? []);
$eventLabels = (array)($event_type_labels ?? []);
$documentLabels = (array)($document_type_labels ?? []);
$printModeLabels = (array)($print_mode_labels ?? ['OFF' => 'Tidak cetak', 'AUTO' => 'Cetak otomatis', 'ASK' => 'Tanya dulu']);
$canCreate = !empty($can_create);
$canEdit = !empty($can_edit);
?>
<div class="container-xxl py-3 print-config-page">
  <div class="fin-page-header mb-3"><div><h4 class="fin-page-title mb-1">Aturan Cetak</h4><p class="fin-page-subtitle mb-0">Hubungkan kejadian POS, isi dokumen, layout, dan printer tujuan dalam satu tempat.</p></div><?php if ($canCreate): ?><button class="btn btn-primary" id="new-rule"><?php $this->load->view('pos/_icon', ['name' => 'plus', 'label' => 'Tambah aturan']); ?><span class="ms-1">Tambah Aturan</span></button><?php endif; ?></div>
  <?php $this->load->view('pos/_printer_config_common', ['printer_config_tab' => 'rules']); ?>
  <div class="print-config-note mb-3"><strong>Tentukan cara cetaknya di setiap aturan.</strong> <em>Tidak cetak</em> menyimpan aturan tanpa mengirim apa pun. <em>Cetak otomatis</em> langsung mengirim saat event terjadi. <em>Tanya dulu</em> menampilkan pilihan cetak atau lewati setelah transaksi berhasil disimpan, sehingga cocok untuk struk yang tidak selalu dibutuhkan.</div>
  <div class="card print-config-card"><div class="card-body">
    <div class="d-flex gap-2 flex-wrap mb-3" id="rule-status-tabs"><button class="btn btn-sm btn-primary" data-status="ACTIVE">Berjalan</button><button class="btn btn-sm btn-outline-primary" data-status="INACTIVE">Tidak cetak</button><button class="btn btn-sm btn-outline-primary" data-status="ALL">Semua</button></div>
    <div class="print-config-toolbar mb-3"><div class="form-group"><label>Cari aturan</label><input id="rule-q" class="form-control" placeholder="Aturan, printer, atau layout"></div><div class="form-group"><label>Event POS</label><select id="rule-event-code" class="form-select"><option value="ALL">Semua event</option><?php foreach ($events as $event): ?><option value="<?= html_escape((string)$event) ?>"><?= html_escape((string)($eventLabels[$event] ?? $event)) ?></option><?php endforeach; ?></select></div><div class="form-group" style="max-width:130px"><label>Baris</label><select id="rule-limit" class="form-select"><option>10</option><option selected>25</option><option>50</option></select></div><button class="btn btn-primary print-config-action" id="rule-filter"><?php $this->load->view('pos/_icon', ['name' => 'search', 'label' => '']); ?><span class="ms-1">Terapkan</span></button><button class="btn btn-outline-secondary print-config-icon-btn" id="rule-clear" title="Clear filter" aria-label="Clear filter"><?php $this->load->view('pos/_icon', ['name' => 'clear', 'label' => 'Clear filter']); ?></button></div>
    <div class="print-config-table-wrap"><table class="table table-hover print-config-table"><thead><tr><th>Event / Aturan</th><th>Cakupan Item</th><th>Tujuan Printer</th><th>Layout</th><th>Mode Cetak</th><th>Copy</th><th class="text-center">Aksi</th></tr></thead><tbody id="rule-body"></tbody></table></div><div class="d-flex justify-content-between align-items-center gap-2 flex-wrap mt-3" id="rule-pager"></div>
  </div></div>
</div>
<div class="modal fade print-config-modal" id="rule-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-xl modal-dialog-scrollable"><div class="modal-content">
  <div class="modal-header"><div><h5 class="modal-title" id="rule-title">Tambah Aturan Cetak</h5><div class="small text-muted">Pilihan ini langsung menjadi sumber bagi engine cetak setelah disimpan.</div></div><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div>
  <div class="modal-body"><form id="rule-form" class="row g-3"><input type="hidden" name="id"><input type="hidden" name="route_code">
    <div class="col-md-6"><label class="form-label">Nama aturan</label><input class="form-control" name="route_name" required placeholder="Contoh: KOT BAR Reguler"></div><div class="col-md-3"><label class="form-label">Prioritas</label><input class="form-control" type="number" min="1" max="9999" name="priority" value="100"></div><div class="col-md-3"><label class="form-label">Copy tambahan</label><input class="form-control" type="number" min="0" max="10" name="copy_count" value="0"><div class="form-text">0 = ikut pengaturan koneksi.</div></div>
    <div class="col-md-6"><label class="form-label">Event POS</label><select class="form-select" name="event_code" required><?php foreach ($events as $event): ?><option value="<?= html_escape((string)$event) ?>"><?= html_escape((string)($eventLabels[$event] ?? $event)) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Jenis dokumen</label><select class="form-select" name="document_type" required><?php foreach ($documents as $document): ?><option value="<?= html_escape((string)$document) ?>"><?= html_escape((string)($documentLabels[$document] ?? $document)) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label">Koneksi printer tujuan</label><select class="form-select" name="connection_id" required><option value="">Pilih koneksi</option><?php foreach ((array)($options['connections'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>"><?= html_escape((string)$row['connection_name']) ?><?= !empty($row['location_label']) ? ' - ' . html_escape((string)$row['location_label']) : '' ?></option><?php endforeach; ?></select></div><div class="col-md-6"><label class="form-label">Layout dokumen</label><select class="form-select" name="layout_id" required><option value="">Pilih layout dengan jenis dokumen yang sama</option><?php foreach ((array)($options['layouts'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>" data-doc="<?= html_escape((string)$row['document_type']) ?>">[<?= html_escape((string)($documentLabels[$row['document_type']] ?? $row['document_type'])) ?>] <?= html_escape((string)$row['layout_name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-4"><label class="form-label">Outlet</label><select class="form-select" name="outlet_id"><option value="0">Semua outlet</option><?php foreach ((array)($options['outlets'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>"><?= html_escape((string)$row['outlet_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Terminal</label><select class="form-select" name="terminal_id"><option value="0">Semua terminal</option><?php foreach ((array)($options['terminals'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>"><?= html_escape((string)$row['terminal_name']) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><label class="form-label">Isi dokumen</label><select class="form-select" name="content_scope" id="rule-content-scope"><option value="ALL_ITEMS">Semua item order</option><option value="MATCHED_DIVISION">Hanya item divisi tertentu</option></select></div>
    <div class="col-md-6 division-scope"><label class="form-label">Divisi operasional</label><select class="form-select" name="operational_division_id"><option value="0">Tidak dibatasi divisi operasional</option><?php foreach ((array)($options['operational_divisions'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>"><?= html_escape((string)$row['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6 division-scope"><label class="form-label">Divisi produk</label><select class="form-select" name="product_division_id"><option value="0">Tidak dibatasi divisi produk</option><?php foreach ((array)($options['product_divisions'] ?? []) as $row): ?><option value="<?= (int)$row['id'] ?>"><?= html_escape((string)$row['name']) ?></option><?php endforeach; ?></select></div>
    <div class="col-md-6"><label class="form-label">Cara cetak</label><select class="form-select" name="print_mode"><option value="OFF">Tidak cetak</option><option value="AUTO">Cetak otomatis</option><option value="ASK">Tanya dulu</option></select><div class="form-text">Mode tanya muncul setelah transaksi tersimpan, jadi transaksi tidak tertahan bila printer bermasalah.</div></div>
    <div class="col-md-6"><label class="form-label">Catatan</label><input class="form-control" name="notes" placeholder="Contoh: KOT hanya untuk item BAR."></div>
  </form></div><div class="modal-footer"><button class="btn btn-light" data-bs-dismiss="modal">Batal</button><?php if ($canCreate || $canEdit): ?><button class="btn btn-primary" id="rule-save"><?php $this->load->view('pos/_icon', ['name' => 'save', 'label' => '']); ?><span class="ms-1">Simpan Aturan</span></button><?php endif; ?></div>
</div></div></div>
<script>
document.addEventListener('DOMContentLoaded', function () {
  const ui = window.PrinterConfigUI;
  const canEdit = <?= $canEdit ? 'true' : 'false' ?>;
  const eventLabels = <?= json_encode($eventLabels, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
  const documentLabels = <?= json_encode($documentLabels, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
  const printModeLabels = <?= json_encode($printModeLabels, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
  const state = {q: '', status: 'ACTIVE', event_code: 'ALL', page: 1, limit: 25};
  const body = document.getElementById('rule-body'); const endpoint = '<?= site_url('pos/printers/rules') ?>'; const form = document.getElementById('rule-form'); const modal = new bootstrap.Modal(document.getElementById('rule-modal')); let rows = {};
  function query() { return new URLSearchParams({rule_q: state.q, rule_status: state.status, rule_event_code: state.event_code, rule_page: state.page, rule_limit: state.limit}).toString(); }
  function modeOf(row) { const raw = String(row.print_mode || (Number(row.is_active) ? 'AUTO' : 'OFF')).toUpperCase(); return ['OFF','AUTO','ASK'].indexOf(raw) >= 0 ? raw : 'OFF'; }
  function modeBadge(row) { const mode = modeOf(row); const css = mode === 'AUTO' ? 'active' : (mode === 'ASK' ? 'generated' : 'inactive'); return '<span class="print-config-status ' + css + '">' + ui.escapeHtml(printModeLabels[mode] || mode) + '</span>'; }
  function controls() { document.getElementById('rule-q').value = state.q; document.getElementById('rule-event-code').value = state.event_code; document.getElementById('rule-limit').value = state.limit; document.querySelectorAll('#rule-status-tabs [data-status]').forEach(function (button) { button.className = 'btn btn-sm ' + (button.dataset.status === state.status ? 'btn-primary' : 'btn-outline-primary'); }); }
  function syncScope() { const show = form.elements.content_scope.value === 'MATCHED_DIVISION'; document.querySelectorAll('.division-scope').forEach(function (element) { element.classList.toggle('d-none', !show); }); }
  function syncLayouts() { const documentType = form.elements.document_type.value; const current = form.elements.layout_id.value; Array.from(form.elements.layout_id.options).forEach(function (option) { if (!option.value) return; option.hidden = option.dataset.doc !== documentType; }); if (current && form.elements.layout_id.selectedOptions[0] && form.elements.layout_id.selectedOptions[0].hidden) form.elements.layout_id.value = ''; }
  function actionButtons(row) { if (!canEdit) return '<span class="muted">Baca saja</span>'; const mode = modeOf(row); const title = mode === 'OFF' ? 'Aktifkan cetak otomatis' : 'Matikan cetak'; return '<div class="d-flex justify-content-center gap-1"><button class="btn btn-outline-primary print-config-icon-btn is-primary" data-edit="' + Number(row.id) + '" title="Edit aturan" aria-label="Edit aturan">' + ui.icon('edit', 'Edit aturan') + '</button><button class="btn btn-outline-secondary print-config-icon-btn ' + (mode === 'OFF' ? 'is-success' : 'is-danger') + '" data-toggle="' + Number(row.id) + '" title="' + title + '" aria-label="' + title + '">' + ui.icon('power', title) + '</button></div>'; }
  async function load() { controls(); const json = await ui.get(endpoint + '/data?' + query()); rows = {}; body.innerHTML = (json.rows || []).map(function (row) { rows[row.id] = row; const scope = row.content_scope === 'MATCHED_DIVISION' ? (row.operational_division_name || row.product_division_name || 'Divisi belum dipilih') : 'Semua item'; return '<tr><td><strong>' + ui.escapeHtml(row.route_name) + '</strong><div class="muted">' + ui.escapeHtml(eventLabels[row.event_code] || row.event_code) + ' / ' + ui.escapeHtml(documentLabels[row.document_type] || row.document_type) + '</div></td><td>' + ui.escapeHtml(scope) + '</td><td><strong>' + ui.escapeHtml(row.connection_name || '-') + '</strong><div class="muted">' + ui.escapeHtml(row.location_label || row.outlet_name || '-') + '</div></td><td>' + ui.escapeHtml(row.layout_name || '-') + '</td><td>' + modeBadge(row) + '</td><td>' + ui.escapeHtml(row.copy_count || row.default_copy_count || 1) + 'x</td><td class="text-center">' + actionButtons(row) + '</td></tr>'; }).join('') || '<tr><td colspan="7" class="print-config-empty">Belum ada aturan cetak.</td></tr>'; ui.pager(document.getElementById('rule-pager'), json.meta || {}, state, load); }
  function open(row) { ui.setForm(form, row || {event_code: 'ORDER_CONFIRM_KOT', document_type: 'KITCHEN_TICKET', content_scope: 'MATCHED_DIVISION', priority: 100, copy_count: 0, print_mode: 'AUTO'}); if (!form.elements.print_mode.value) form.elements.print_mode.value = modeOf(row || {}); syncScope(); syncLayouts(); document.getElementById('rule-title').textContent = row ? 'Edit Aturan Cetak' : 'Tambah Aturan Cetak'; modal.show(); }
  const newButton = document.getElementById('new-rule'); if (newButton) newButton.addEventListener('click', function () { open(null); });
  document.getElementById('rule-filter').addEventListener('click', function () { state.q = document.getElementById('rule-q').value.trim(); state.event_code = document.getElementById('rule-event-code').value; state.limit = Number(document.getElementById('rule-limit').value); state.page = 1; load().catch(function (error) { ui.notice('error', 'Aturan tidak dapat dimuat', error.message); }); });
  document.getElementById('rule-clear').addEventListener('click', function () { state.q = ''; state.status = 'ACTIVE'; state.event_code = 'ALL'; state.page = 1; load().catch(function (error) { ui.notice('error', 'Aturan tidak dapat dimuat', error.message); }); });
  document.querySelectorAll('#rule-status-tabs [data-status]').forEach(function (button) { button.addEventListener('click', function () { state.status = button.dataset.status; state.page = 1; load().catch(function (error) { ui.notice('error', 'Aturan tidak dapat dimuat', error.message); }); }); });
  form.elements.content_scope.addEventListener('change', syncScope); form.elements.document_type.addEventListener('change', syncLayouts);
  body.addEventListener('click', async function (event) { const edit = event.target.closest('[data-edit]'); const toggle = event.target.closest('[data-toggle]'); if (edit) { open(rows[edit.dataset.edit]); return; } if (!toggle) return; try { await ui.post(endpoint + '/toggle/' + Number(toggle.dataset.toggle), {}); await load(); ui.notice('success', 'Aturan diperbarui', 'Mode cetak pada aturan ini sudah berubah.'); } catch (error) { ui.notice('error', 'Aturan gagal diubah', error.message); } });
  const saveButton = document.getElementById('rule-save'); if (saveButton) saveButton.addEventListener('click', async function () { if (!form.reportValidity()) return; saveButton.disabled = true; try { await ui.post(endpoint + '/save', ui.formObject(form)); modal.hide(); await load(); ui.notice('success', 'Aturan disimpan', 'Engine cetak akan memakai pilihan terbaru pada transaksi berikutnya.'); } catch (error) { ui.notice('error', 'Aturan belum tersimpan', error.message); } finally { saveButton.disabled = false; } });
  load().catch(function (error) { body.innerHTML = '<tr><td colspan="7" class="print-config-empty">' + ui.escapeHtml(error.message) + '</td></tr>'; });
});
</script>
