-- A5.12 customer-neutral clean-install reference seed.
-- CLEAN INSTALL ONLY: never apply to an existing customer database.
-- Source allowlist: product navigation metadata and one global SUPERADMIN role.
-- Excluded: users, employees, other roles, customer permission choices, secrets,
-- transactions, balances, inventory, targets, queues, logs, and customer identity.
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
START TRANSACTION;

INSERT INTO sys_matrix_group (id, group_code, group_label, icon, color, bg_color, sort_order) VALUES
  (1, 'DASHBOARD', 'Dashboard', 'ri-dashboard-line', '#1d4ed8', '#eff6ff', 10),
  (3, 'AUTH', 'Hak Akses', 'ri-shield-keyhole-line', '#2563eb', '#eff6ff', 120),
  (5, 'SISTEM', 'Sistem & Hak Akses', 'ri-settings-3-line', '#475569', '#f1f5f9', 25),
  (7, 'SYS', 'Sistem', 'ri-settings-3-line', '#475569', '#f1f5f9', 30),
  (9, 'MASTER', 'Master Data', 'ri-database-2-line', '#475569', '#f8fafc', 100),
  (11, 'PURCHASE', 'Purchase', 'ri-shopping-cart-2-line', '#ea580c', '#fff7ed', 30),
  (13, 'INVENTORY', 'Inventory', 'ri-archive-drawer-line', '#059669', '#f0fdf4', 40),
  (15, 'PRODUKSI', 'Base / Prepare', 'ri-flask-line', '#0f766e', '#ecfeff', 51),
  (17, 'POS', 'POS & Kasir', 'ri-store-2-line', '#be185d', '#fdf2f8', 20),
  (19, 'HR', 'Karyawan & HR', 'ri-team-line', '#0284c7', '#f0f9ff', 60),
  (21, 'ATTENDANCE', 'Absensi', 'ri-calendar-check-line', '#b45309', '#fffbeb', 61),
  (23, 'PAYROLL', 'Penggajian', 'ri-money-dollar-circle-line', '#0d9488', '#f0fdfa', 90),
  (25, 'FINANCE', 'Keuangan', 'ri-bank-line', '#be123c', '#fff1f2', 80),
  (27, 'REPORT', 'Laporan', 'ri-bar-chart-2-line', '#6d28d9', '#faf5ff', 110),
  (29, 'MY_PORTAL', 'Portal Saya', 'ri-user-settings-line', '#4338ca', '#eef2ff', 200),
  (93, 'PRODUCT', 'Produk', 'ri-store-2-line', '#7c3aed', '#f5f3ff', 50),
  (95, 'LOYALTY', 'Member & Promo', 'ri-user-star-line', '#2563eb', '#eff6ff', 70),
  (97, 'MENU_BOOK', 'Menu Book', 'ri-book-open-line', '#7c2d12', '#fff7ed', 110),
  (99, 'SYSTEM', 'Sistem', 'ri-settings-3-line', '#475569', '#f1f5f9', 121),
  (103, 'ASSET', 'Aset', 'ri-archive-2-line', '#0f766e', '#ecfdf5', 86);

INSERT INTO sys_page (id, page_code, page_name, module, matrix_group, description, is_active) VALUES
  (1, 'auth.users.index', 'Daftar User', 'SISTEM', NULL, 'Lihat daftar semua akun user', 1),
  (2, 'auth.users.manage', 'Kelola User', 'SISTEM', NULL, 'Buat/edit/nonaktifkan user', 0),
  (3, 'auth.users.permissions', 'Override Izin User', 'SISTEM', NULL, 'Set override izin per user', 0),
  (4, 'auth.roles.index', 'Daftar Role', 'SISTEM', NULL, 'Lihat daftar semua role', 1),
  (5, 'auth.roles.manage', 'Kelola Role', 'SISTEM', NULL, 'Buat/edit/hapus role', 0),
  (6, 'auth.roles.matrix', 'Matrix Izin Role', 'SISTEM', NULL, 'Atur izin CRUD per halaman untuk role', 0),
  (7, 'master.uom.index', 'Master UOM', 'MASTER', NULL, 'List dan kelola satuan (UOM)', 1),
  (8, 'master.operational_division.index', 'Master Divisi Operasional', 'MASTER', NULL, 'List dan kelola divisi operasional', 1),
  (9, 'master.product_division.index', 'Master Divisi Produk', 'MASTER', NULL, 'List dan kelola divisi produk', 1),
  (10, 'master.product_classification.index', 'Master Klasifikasi Produk', 'MASTER', NULL, 'List dan kelola klasifikasi produk', 1),
  (11, 'master.product_category.index', 'Master Kategori Produk', 'MASTER', NULL, 'List dan kelola kategori produk', 1),
  (12, 'master.item_category.index', 'Master Kategori Item', 'MASTER', NULL, 'List dan kelola kategori item/material', 1),
  (13, 'master.component_category.index', 'Master Kategori Component', 'MASTER', NULL, 'List dan kelola kategori component', 1),
  (14, 'master.material.index', 'Master Bahan Baku', 'MASTER', NULL, 'List dan kelola bahan baku', 1),
  (15, 'master.item.index', 'Master Item', 'MASTER', NULL, 'List dan kelola item pembelian', 1),
  (17, 'master.product.index', 'Master Product', 'MASTER', NULL, 'List dan kelola product', 1),
  (18, 'master.vendor.index', 'Master Vendor', 'MASTER', NULL, 'List dan kelola vendor', 1),
  (19, 'master.extra.index', 'Master Extra', 'MASTER', NULL, 'List dan kelola extra', 1),
  (20, 'master.extra_group.index', 'Master Extra Group', 'MASTER', NULL, 'List dan kelola group extra', 1),
  (21, 'master.product_recipe.index', 'Relasi Recipe Product', 'MASTER', NULL, 'Kelola line recipe product', 1),
  (23, 'master.product_extra_map.index', 'Mapping Product Extra Group', 'MASTER', NULL, 'Kelola mapping product ke extra group', 1),
  (41, 'master.variable_cost_default.index', 'Pengaturan Variable Cost Default', 'MASTER', NULL, 'Kelola default variable cost product/component', 1),
  (65, 'system.sidebar.manage', 'Manajemen Sidebar', 'SYSTEM', NULL, 'Kelola struktur dan data menu sidebar', 1),
  (67, 'purchase.order.index', 'Purchase Order', 'PURCHASE', NULL, 'Halaman utama purchase order', 1),
  (68, 'purchase.catalog.index', 'Purchase Catalog Search', 'PURCHASE', NULL, 'Endpoint pencarian katalog purchase', 1),
  (70, 'purchase.stock.warehouse.index', 'Purchase Warehouse Stock Monitor', 'PURCHASE', NULL, 'Monitoring stok gudang dari receipt purchase', 1),
  (71, 'purchase.stock.division.index', 'Purchase Division Stock Monitor', 'PURCHASE', NULL, 'Monitoring stok divisi dari receipt purchase', 1),
  (78, 'purchase.receipt.index', 'Purchase Receipt', 'PURCHASE', NULL, 'Form posting receipt purchase ke gudang/divisi', 1),
  (79, 'master.purchase.posting_type', 'Master Posting Type', 'MASTER', NULL, 'CRUD master posting type purchase', 1),
  (80, 'master.purchase.purchase_type', 'Master Purchase Type', 'MASTER', NULL, 'CRUD master purchase type', 1),
  (81, 'master.purchase.catalog', 'Master Purchase Catalog', 'MASTER', NULL, 'CRUD master purchase catalog profile', 1),
  (92, 'finance.account.index', 'Master Company Account', 'FINANCE', NULL, 'Kelola rekening perusahaan', 1),
  (93, 'finance.mutation.index', 'Finance Mutation Monitor', 'FINANCE', NULL, 'Input mutasi rekening dan log', 1),
  (94, 'purchase.stock.warehouse.movement.index', 'Warehouse Stock Movement', 'PURCHASE', NULL, 'Keluar masuk stok gudang', 1),
  (95, 'purchase.stock.warehouse.daily.index', 'Warehouse Daily Rollup', 'PURCHASE', NULL, 'Daily rollup stok gudang', 1),
  (96, 'purchase.stock.division.movement.index', 'Log Bahan Baku Divisi', 'PURCHASE', NULL, 'Log keluar masuk stok bahan baku divisi dari inv_stock_movement_log', 1),
  (97, 'purchase.stock.division.daily.index', 'Division Daily Rollup', 'PURCHASE', NULL, 'Daily rollup stok divisi', 1),
  (98, 'purchase.order.log.index', 'Purchase Order Log', 'PURCHASE', NULL, 'Timeline log transaksi purchase order', 1),
  (99, 'purchase.rebuild.impact.index', 'Purchase Rebuild Impact', 'PURCHASE', NULL, 'Rebuild/resync dampak purchase secara terstruktur', 1),
  (100, 'purchase.stock.warehouse.matrix.index', 'Purchase Inventory Warehouse Daily Matrix', 'PURCHASE', NULL, 'Halaman matrix daily gudang dengan tanggal horizontal dan detail mutasi', 1),
  (101, 'purchase.stock.material.matrix.index', 'Purchase Inventory Material Daily Matrix', 'PURCHASE', NULL, 'Halaman matrix daily material per divisi dengan tanggal horizontal dan detail mutasi', 1),
  (103, 'purchase.stock.opening.warehouse.index', 'Purchase Opening Gudang', 'PURCHASE', NULL, 'Input dan monitoring opening stok gudang', 1),
  (104, 'purchase.stock.opening.division.index', 'Purchase Opening Divisi', 'PURCHASE', NULL, 'Input dan monitoring opening bahan baku divisi', 1),
  (105, 'hr.org_division.index', 'Master Divisi Organisasi', 'HR', NULL, 'CRUD org_division via master module', 1),
  (106, 'hr.org_position.index', 'Master Jabatan Organisasi', 'HR', NULL, 'CRUD org_position via master module', 1),
  (107, 'hr.org_employee.index', 'Master Pegawai', 'HR', NULL, 'CRUD org_employee via master module', 1),
  (108, 'attendance.shift.index', 'Master Shift', 'ATTENDANCE', NULL, 'CRUD att_shift via master module', 1),
  (109, 'attendance.location.index', 'Master Lokasi Absensi', 'ATTENDANCE', NULL, 'CRUD att_location via master module', 1),
  (110, 'attendance.holiday.index', 'Master Hari Libur', 'ATTENDANCE', NULL, 'CRUD att_holiday_calendar via master module', 1),
  (111, 'payroll.component.index', 'Master Komponen Gaji', 'PAYROLL', NULL, 'CRUD pay_salary_component via master module', 1),
  (112, 'payroll.profile.index', 'Master Profil Gaji', 'PAYROLL', NULL, 'CRUD pay_salary_profile via master module', 1),
  (113, 'payroll.assignment.index', 'Assignment Profil Gaji', 'PAYROLL', NULL, 'CRUD pay_salary_assignment via master module', 1),
  (114, 'attendance.settings.index', 'Pengaturan Absensi & Payroll', 'ATTENDANCE', NULL, 'Policy absensi dan payroll scope', 1),
  (115, 'attendance.daily.index', 'Rekap Absensi Harian', 'ATTENDANCE', NULL, 'Rekap harian tunggal dari att_daily', 1),
  (116, 'attendance.logs.index', 'Log Presensi', 'ATTENDANCE', NULL, 'Log checkin/checkout dari att_presence', 1),
  (117, 'attendance.schedules.index', 'Jadwal Shift Pegawai', 'ATTENDANCE', NULL, 'Monitoring jadwal shift pegawai', 1),
  (122, 'attendance.pending.index', 'Pending Request Absensi', 'ATTENDANCE', NULL, 'Monitoring pengajuan & approval absensi', 1),
  (129, 'hr.contract_template.index', 'Master Template Kontrak', 'HR', NULL, 'CRUD hr_contract_template via master module', 1),
  (130, 'hr.contract.index', 'Master Kontrak Pegawai', 'HR', NULL, 'CRUD hr_contract via master module', 1),
  (133, 'payroll.basic_salary.index', 'Standar Gaji Pokok', 'PAYROLL', NULL, 'CRUD pay_basic_salary_standard via master module', 1),
  (134, 'payroll.objective_override.index', 'Override Tunjangan Objektif', 'PAYROLL', NULL, 'CRUD pay_objective_override via master module', 1),
  (135, 'payroll.preview_thp.index', 'Preview THP', 'PAYROLL', NULL, 'Preview THP read-only dari assignment + kontrak aktif', 1),
  (136, 'attendance.anomalies.index', 'Monitoring Anomali Absensi', 'ATTENDANCE', NULL, 'Monitoring data anomali absensi harian', 1),
  (137, 'attendance.master_health.index', 'Kesehatan Data Master HR', 'ATTENDANCE', NULL, 'Audit relasi data master HR sebelum operasional payroll', 1),
  (138, 'attendance.estimate.index', 'Estimasi Gaji Absensi', 'ATTENDANCE', NULL, 'Estimasi harian/bulanan berbasis absensi sebelum payroll final', 1),
  (140, 'attendance.overtime_entry.index', 'Input Lembur Manual', 'ATTENDANCE', NULL, 'CRUD input lembur manual berbasis tanggal dan jam lembur', 1),
  (141, 'payroll.manual_adjustment.index', 'Penyesuaian Gaji Manual', 'PAYROLL', NULL, 'CRUD tambahan dan pengurangan gaji manual', 1),
  (142, 'attendance.ph.assignment.index', 'Assignment PH Pegawai', 'ATTENDANCE', NULL, 'Pengaturan pegawai yang berhak PH', 1),
  (143, 'attendance.ph.ledger.index', 'Ledger & Log PH', 'ATTENDANCE', NULL, 'Mutasi PH grant/use/expire/adjust', 1),
  (144, 'attendance.ph.recap.index', 'Rekap PH Pegawai', 'ATTENDANCE', NULL, 'Rekap saldo PH per pegawai', 1),
  (145, 'my.overtime.index', 'Lembur Saya', 'MY_PORTAL', NULL, 'Riwayat lembur pegawai', 1),
  (146, 'my.ph.index', 'PH Saya', 'MY_PORTAL', NULL, 'Saldo & histori PH pegawai', 1),
  (147, 'my.adjustment.index', 'Tambahan/Pengurangan Saya', 'MY_PORTAL', NULL, 'Riwayat tambahan/pengurangan manual pegawai', 1),
  (151, 'payroll.meal_disbursement.index', 'Pencairan Uang Makan', 'PAYROLL', NULL, 'Generate kandidat uang makan, anti duplicate, dan posting paid', 1),
  (152, 'payroll.salary_disbursement.index', 'Pencairan Gaji', 'PAYROLL', NULL, 'Finalisasi payroll period dan pencairan gaji', 1),
  (153, 'payroll.cash_advance.index', 'Kasbon Pegawai', 'PAYROLL', NULL, 'Manajemen kasbon dan cicilan pegawai', 1),
  (154, 'master.bank.index', 'Master Bank', 'MASTER', NULL, 'Daftar bank umum untuk referensi rekening perusahaan dan pegawai', 1),
  (155, 'procurement.workbench.index', 'Procurement API Access', 'PURCHASE', NULL, 'Endpoint permission base procurement', 0),
  (157, 'procurement.division.index', 'PO/SR Divisi', 'PURCHASE', NULL, 'Pengajuan kebutuhan divisi auto route ke SR/PO', 1),
  (160, 'procurement.store_request.index', 'Store Request', 'PURCHASE', NULL, 'Verifikasi SR + fulfillment + shortage ke PO', 1),
  (163, 'purchase.reclassify.profile.domain.index', 'Reclassify Profile Domain', 'PURCHASE', NULL, 'Utility pembersihan historis snapshot ITEM/MATERIAL by profile_key', 1),
  (165, 'production.component.stock.index', 'Stok Base/Prepare', 'PRODUKSI', NULL, 'Saldo live base/prepare per lokasi', 1),
  (166, 'production.component.movement.index', 'Mutasi Base/Prepare', 'PRODUKSI', NULL, 'Ledger keluar-masuk base/prepare', 1),
  (167, 'production.component.daily.index', 'Daily Matrix Base/Prepare', 'PRODUKSI', NULL, 'Matrix harian stok base/prepare', 1),
  (168, 'production.component.opening.index', 'Opening Base/Prepare', 'PRODUKSI', NULL, 'Dokumen stok awal base/prepare', 1),
  (169, 'production.component.adjustment.index', 'Adjustment Base/Prepare', 'PRODUKSI', NULL, 'Dokumen penyesuaian base/prepare', 1),
  (170, 'production.component.batch.index', 'Batch Produksi Base/Prepare', 'PRODUKSI', NULL, 'Produksi output base/prepare', 1),
  (171, 'production.component.monthly.index', 'Opname Bulanan Base/Prepare', 'PRODUKSI', NULL, 'Closing/opening bulanan base/prepare', 1),
  (172, 'production.component.category.index', 'Kategori Base/Prepare', 'PRODUKSI', NULL, 'Kategori master base/prepare', 1),
  (173, 'production.component.master.index', 'Master Base/Prepare', 'PRODUKSI', NULL, 'Master data base/prepare', 1),
  (174, 'production.component.formula.index', 'Resep/Formula Base/Prepare', 'PRODUKSI', NULL, 'Formula/resep base/prepare', 1),
  (176, 'purchase.stock.adjustment.warehouse.index', 'Purchase Adjustment Gudang', 'PURCHASE', NULL, 'Input dan monitoring penyesuaian stok gudang', 1),
  (177, 'purchase.stock.adjustment.division.index', 'Purchase Adjustment Divisi', 'PURCHASE', NULL, 'Input dan monitoring penyesuaian stok bahan baku divisi', 1),
  (182, 'master.purchase.catalog_vendor', 'Master Purchase Catalog Vendor', 'MASTER', NULL, 'CRUD relasi vendor dan harga untuk purchase catalog', 1),
  (183, 'purchase.report.index', 'Laporan Purchase', 'PURCHASE', NULL, 'Ringkasan bulanan/harian purchase dan detail per tipe per tanggal', 1),
  (184, 'pos.member.index', 'Member POS', 'POS', NULL, 'Master member untuk pencarian kasir, loyalty, voucher, dan aplikasi member', 1),
  (185, 'pos.payment_method.index', 'Payment Method POS', 'POS', NULL, 'Master metode pembayaran POS dan mapping rekening kasir', 1),
  (186, 'pos.outlet_terminal.index', 'Outlet + Terminal POS', 'POS', NULL, 'Master outlet penjualan dan terminal/perangkat kasir POS', 1),
  (187, 'master.product_bundle.index', 'Bundle Produk', 'MASTER', NULL, 'Kelola bundle produk untuk kebutuhan penjualan POS', 1),
  (190, 'pos.printer.index', 'Printer POS', 'POS', NULL, 'Master template, profile, dan device printer POS desktop', 1);

INSERT INTO sys_page (id, page_code, page_name, module, matrix_group, description, is_active) VALUES
  (191, 'pos.order.draft.index', 'Draft Order POS', 'POS', NULL, 'Workbench draft order POS dan stock commit snapshot awal', 1),
  (192, 'pos.cashier.index', 'Kasir POS', 'POS', NULL, 'Layar kasir fase 1 untuk input order, member, bundle, confirm stock commit, dan preview void/refund', 1),
  (193, 'loyalty.member.index', 'Member & Loyalitas', 'LOYALTY', NULL, 'Master member dan saldo loyalitas pelanggan', 1),
  (194, 'loyalty.point_rule.index', 'Aturan Poin', 'LOYALTY', NULL, 'Pengaturan rule point member', 1),
  (195, 'loyalty.stamp_campaign.index', 'Campaign Stamp', 'LOYALTY', NULL, 'Pengaturan campaign stamp member', 1),
  (196, 'loyalty.voucher_campaign.index', 'Campaign Voucher', 'LOYALTY', NULL, 'Pengaturan campaign voucher member', 1),
  (197, 'master.product_extra.workspace.index', 'Workspace Extra Produk', 'MASTER', NULL, 'Hub konsep extra produk, group extra, mapping produk, dan sambungannya ke POS', 1),
  (198, 'pos.stock.live.index', 'Stock Live POS', 'POS', NULL, 'Audit cache availability POS vs kalkulasi live recipe dan stok aktual', 1),
  (199, 'pos.sales_channel.index', 'Sales Channel POS', 'POS', NULL, 'Master channel penjualan POS seperti Walk In, WhatsApp, GrabFood, ShopeeFood, dan channel lain beserta relasi service type yang diizinkan.', 1),
  (201, 'pos.deposit.index', 'Deposit / DP POS', 'POS', NULL, 'Input dan audit deposit / DP POS atas nama customer/member sebelum dipakai ke pembayaran final.', 1),
  (202, 'purchase.stock.division.reconcile.index', 'Banding Stok Akhir Divisi', 'PURCHASE', NULL, 'Banding stok akhir divisi antara stok aktif, material daily, daily rollup, dan movement mentah', 1),
  (204, 'pos.report.sales.index', 'Laporan Penjualan POS', 'POS', NULL, 'Laporan ringkasan transaksi penjualan POS per order.', 1),
  (205, 'pos.report.sales.detail.index', 'Laporan Penjualan Produk POS', 'POS', NULL, 'Laporan detail penjualan POS sampai level line produk.', 1),
  (206, 'pos.report.payment.index', 'Laporan Pembayaran POS', 'POS', NULL, 'Laporan ledger pembayaran POS per dokumen pembayaran.', 1),
  (207, 'pos.report.refund.index', 'Laporan Refund POS', 'POS', NULL, 'Laporan refund POS berikut detail pembatalannya.', 1),
  (208, 'pos.report.void.index', 'Laporan Void POS', 'POS', NULL, 'Laporan void POS berikut line produk dan extra yang dibatalkan.', 1),
  (209, 'pos.order.monitor.index', 'Monitor Dapur / Bar POS', 'POS', NULL, 'Board operasional task kitchen, bar, dan checker untuk order POS aktif', 1),
  (217, 'finance.cash_vault_daily.index', 'Laporan Brankas Harian', 'FINANCE', NULL, 'Laporan saldo harian brankas/kas berdasarkan mutasi rekening perusahaan, pendapatan POS, refund, transfer, dan belanja.', 1),
  (218, 'auth.roles.users', 'Atur Pengguna per Role', 'SISTEM', NULL, 'Menentukan user mana yang masuk ke suatu role.', 0),
  (219, 'dashboard.index', 'Dashboard', 'DASHBOARD', NULL, 'Ringkasan operasional utama aplikasi.', 1),
  (220, 'my.home.index', 'Beranda Saya', 'MY_PORTAL', NULL, 'Beranda ringkasan portal pegawai.', 1),
  (221, 'my.attendance.index', 'Absensi Saya', 'MY_PORTAL', NULL, 'Riwayat dan aksi absensi pegawai.', 1),
  (222, 'my.leave.index', 'Pengajuan Izin Saya', 'MY_PORTAL', NULL, 'Pengajuan izin, sakit, dan koreksi absensi pribadi.', 1),
  (223, 'my.payroll.index', 'Payroll Saya', 'MY_PORTAL', NULL, 'Estimasi gaji dan slip gaji pribadi.', 1),
  (224, 'my.profile.index', 'Kontrak Saya', 'MY_PORTAL', NULL, 'Profil pegawai dan akses kontrak kerja pribadi.', 1),
  (225, 'my.meal.index', 'Uang Makan Saya', 'MY_PORTAL', NULL, 'Ledger uang makan pegawai.', 1),
  (226, 'my.cash_advance.index', 'Kasbon Saya', 'MY_PORTAL', NULL, 'Monitoring kasbon dan cicilan pegawai.', 1),
  (234, 'pos.report.cashier.close.index', 'Laporan Tutup Kasir POS', 'POS', NULL, 'Laporan tutup kasir POS yang membandingkan snapshot rekening shift dengan mutasi rekening POS tercatat.', 1),
  (235, 'pos.report.daily_sales.index', 'Daily Sales POS', 'POS', NULL, 'Ringkasan penjualan harian POS per tanggal, metode bayar, rekening, dan shift.', 1),
  (239, 'pos.report.payment.method.index', 'Laporan Metode Pembayaran POS', 'POS', NULL, 'Rekap penerimaan POS per metode pembayaran termasuk refund.', 1),
  (240, 'pos.report.payment.account.index', 'Laporan Rekening Pembayaran POS', 'POS', NULL, 'Rekap penerimaan POS per rekening perusahaan termasuk refund.', 1),
  (243, 'pos.self_order.index', 'Self Order POS', 'POS', NULL, 'Pengaturan self order, QR meja, dan Midtrans QRIS untuk aplikasi member', 1),
  (244, 'pos.order.paid.index', 'Pesanan Terbayar POS', 'POS', NULL, 'Workspace pesanan POS berstatus PAID: filter tanggal, detail order, refund, dan koreksi metode pembayaran.', 1),
  (245, 'purchase.material.price_history', 'Riwayat Harga Bahan Baku', 'PURCHASE', NULL, 'Grafik dan tabel riwayat harga beli & HPP per item dari data purchase receipt.', 1),
  (249, 'system.dbtools.settings', 'DB Tools Settings', 'SYSTEM', NULL, 'Pengaturan backup dan replication via UI.', 1),
  (253, 'inventory.stock.opname.division.index', 'Daily Recon Stok Divisi', 'PURCHASE', NULL, 'Halaman kroscek dan rekonsiliasi stok bahan baku harian per divisi dengan input fisik dan aksi penyesuaian.', 1),
  (257, 'product.availability', 'Ketersediaan Produk', 'PRODUCT', NULL, 'Auto-registered dari audit sidebar', 1),
  (259, 'production.component.lots', 'Lot Component', 'PRODUCTION', NULL, 'Auto-registered dari audit sidebar', 1),
  (265, 'production.component.daily.recon.index', 'Daily Recon Stok Component', 'PRODUKSI', NULL, NULL, 1),
  (267, 'inventory.stock.opname.warehouse.monthly', 'Stok Opname Bulanan Gudang', 'INVENTORY', NULL, NULL, 1),
  (269, 'inventory.stock.opname.division.monthly', 'Stok Opname Bulanan Divisi', 'INVENTORY', NULL, NULL, 1),
  (271, 'production.component.opname.monthly', 'Stok Opname Bulanan Component', 'PRODUKSI', NULL, NULL, 1),
  (279, 'finance.payable.index', 'Utang Pihak Luar', 'FINANCE', NULL, 'Kelola utang pihak luar, pelunasan, dan dampaknya ke rekening perusahaan.', 1),
  (281, 'finance.receivable.index', 'Piutang Pihak Luar', 'FINANCE', NULL, 'Kelola piutang pihak luar, penerimaan pembayaran, dan dampaknya ke rekening perusahaan.', 1),
  (283, 'finance.party.index', 'Relasi Utang Piutang', 'FINANCE', NULL, 'Master pihak luar untuk transaksi utang dan piutang, bisa ditautkan ke member.', 1),
  (285, 'finance.cash_position.index', 'Posisi Kas & Eksposur', 'FINANCE', NULL, 'Dashboard rekening untuk membaca saldo fisik, saldo riil, utang, piutang, kasbon, payroll pending, dan histori saldo tetap.', 1),
  (287, 'finance.period_close.index', 'Tutup Periode Keuangan', 'FINANCE', NULL, 'Workspace cut off bulanan dan tahunan untuk snapshot laporan keuangan.', 1),
  (289, 'finance.target.index', 'Target Keuangan', 'FINANCE', NULL, 'Workspace target harian, bulanan, tahunan, dan fondasi bonus berbasis metric keuangan.', 1),
  (291, 'payroll.bonus.index', 'Bonus Pegawai', 'PAYROLL', NULL, 'Workspace bonus pegawai: aturan bonus, penalti, penilaian 360, dan rekap bonus.', 1),
  (293, 'my.bonus.index', 'Bonus Saya', 'MY_PORTAL', NULL, 'Ringkasan bonus pribadi dan penilaian rekan kerja harian.', 1),
  (299, 'menu_book.index', 'Menu Book', 'MENU_BOOK', NULL, 'Halaman indeks buku menu digital untuk usaha food and beverage.', 1),
  (301, 'finance.financial_estimation.index', 'Estimasi Keuangan', 'FINANCE', NULL, 'Dashboard estimasi keuangan berbasis omzet, HPP live, beban berjalan, estimasi gaji, adjustment stok, dan saldo riil.', 1),
  (303, 'finance.bank_daily_recap.index', 'Rekap Rekening Harian', 'FINANCE', NULL, 'Rekap harian saldo rekening fisik, saldo riil rekening, dan saldo riil kafe untuk audit kas harian.', 1),
  (305, 'finance.daily_overview.index', 'Keuangan Harian', 'FINANCE', NULL, 'Ringkasan harian kas awal, arus masuk, arus keluar, net, kas akhir, dan detail per rekening.', 1),
  (311, 'inventory.stock.opening.division.generated', 'Stok Awal Bahan Baku', 'INVENTORY', NULL, 'Stok awal bahan baku divisi hasil generate otomatis (carry-forward closing opname bulan sebelumnya). Source: inv_division_stock_opening_snapshot WHERE source_type = AUTO_REBUILD.', 1),
  (313, 'loyalty.redeem.index', 'Redeem Poin / Voucher / Stamp', 'LOYALTY', NULL, 'Proses penukaran (redeem) poin, stamp, dan voucher milik member', 1),
  (315, 'loyalty.redeem_rule.index', 'Pengaturan Redeem', 'LOYALTY', NULL, 'Katalog reward yang bisa ditukar dengan poin atau stamp oleh member', 1),
  (319, 'landing_page.index', 'Pengaturan Landing Page', 'WEBSITE', 'WEBSITE', NULL, 1),
  (321, 'pos.daily_recon_settings.index', 'Pengaturan Gate Daily Recon POS', 'POS', NULL, 'Mengaktifkan/menonaktifkan warning cek daily recon bahan baku dan component saat buka/tutup kasir POS.', 1),
  (327, 'purchase.stock.transfer.division.index', 'Purchase Transfer Divisi', 'PURCHASE', NULL, 'Input dan monitoring mutasi bahan baku antar divisi dan lokasi', 1),
  (329, 'wa.dashboard', 'WA Dashboard', 'WA', NULL, 'Dashboard status koneksi dan statistik WhatsApp Bot', 1),
  (331, 'wa.broadcast', 'WA Broadcast', 'WA', NULL, 'Manajemen kampanye broadcast WhatsApp ke pelanggan', 1),
  (333, 'wa.template', 'WA Template', 'WA', NULL, 'Kelola template pesan WhatsApp', 1),
  (335, 'wa.group', 'WA Grup', 'WA', NULL, 'Mapping dan manajemen grup WhatsApp', 1),
  (337, 'wa.log', 'WA Log Pengiriman', 'WA', NULL, 'Riwayat log pengiriman pesan WhatsApp', 1),
  (339, 'wa.settings', 'WA Pengaturan', 'WA', NULL, 'Konfigurasi koneksi dan pengaturan WhatsApp Bot', 1),
  (353, 'production.roastery.packaging_label.index', 'Label Packaging Kopi', 'PRODUKSI', NULL, 'Desain, preview, dan cetak label packaging kopi roastery', 1),
  (361, 'pos.online_food.index', 'Online Food POS', 'POS', NULL, 'Pengaturan dan monitoring order online food dari aplikasi member', 1),
  (365, 'pos.report.sales.extra.index', 'Laporan Penjualan Extra POS', 'POS', NULL, 'Laporan detail penjualan POS untuk extra per item extra.', 1),
  (367, 'asset.item.index', 'Daftar Aset', 'ASSET', 'ASSET', 'CRUD aset fisik, foto, lokasi, dan nilai buku', 1),
  (369, 'asset.damage.index', 'Laporan Kerusakan Aset', 'ASSET', 'ASSET', 'Input aset rusak/hilang dengan alasan dan bukti foto', 1),
  (371, 'asset.recon.index', 'Rekon Aset Bulanan', 'ASSET', 'ASSET', 'Generate dan posting rekon aset akhir bulan', 1),
  (373, 'asset.transfer.index', 'Mutasi Aset', 'ASSET', 'ASSET', 'Mutasi aset antar divisi/outlet dengan approval dan posting audit trail', 1),
  (375, 'asset.label.index', 'QR Label Aset', 'ASSET', 'ASSET', 'Cetak QR label aset per unit untuk scan detail dan rekon', 1),
  (377, 'asset.maintenance.index', 'Maintenance Aset', 'ASSET', 'ASSET', 'Jadwal dan realisasi preventive/corrective maintenance aset', 1),
  (379, 'asset.handover.index', 'Serah Terima Aset', 'ASSET', 'ASSET', 'Serah terima aset antar PIC/pegawai', 1),
  (381, 'asset.disposal.index', 'Disposal Aset', 'ASSET', 'ASSET', 'Pengajuan pensiun, buang, jual, atau donasi aset', 1),
  (383, 'asset.depreciation.index', 'Jurnal Penyusutan Aset', 'ASSET', 'ASSET', 'Preview dan staging jurnal penyusutan aset bulanan', 1),
  (397, 'wa.manual', 'WA Kirim Manual', 'WA', NULL, 'Kirim pesan WhatsApp manual ke nomor atau member terdaftar', 1),
  (399, 'wa.report_schedule', 'WA Jadwal Laporan', 'WHATSAPP', 'WHATSAPP', 'Jadwal laporan otomatis dan daftar command bot WhatsApp', 1),
  (401, 'inventory.stock.deficit.index', 'Defisit Stok', 'INVENTORY', NULL, 'Daftar pemakaian yang belum tertutup lot stok dan riwayat penyelesaiannya.', 1),
  (403, 'inventory.stock.period.index', 'Tutup Periode Stok', 'INVENTORY', NULL, 'Kontrol periode stok bahan baku dan component untuk cut-off bulanan.', 1),
  (409, 'inventory.stock.health.index', 'Kesehatan Stok Aktif', 'INVENTORY', NULL, 'Antrean pemeriksaan stok bulan aktif terhadap lot dan nilai sebelum cut-off.', 1),
  (411, 'inventory.stock.value_reconciliation.index', 'Koreksi Nilai Stok', 'INVENTORY', NULL, 'Koreksi nilai stok aktif dan lot OPEN tanpa mengubah jumlah barang.', 1),
  (413, 'inventory.stock.integrity_audit.index', 'Audit Integritas Stok', 'INVENTORY', NULL, 'Pemeriksaan baca-saja jejak adjustment, batch, transfer, POS, defisit, HPP, lot, dan period lock bulan aktif.', 1),
  (415, 'pos.report.sales.audit.index', 'Audit Penjualan & HPP POS', 'POS', NULL, 'Pemeriksaan baca-saja untuk refund, penjualan bersih, HPP, margin, dan tautan koreksi HPP defisit.', 1),
  (417, 'pos.availability.queue.index', 'Ketersediaan POS', 'POS', NULL, 'Pemantauan antrean pembaruan cache ketersediaan menu POS dan panduan cron worker.', 1),
  (421, 'loyalty.voucher_usage.index', 'Laporan Pemakaian Voucher', 'LOYALTY', NULL, 'Riwayat voucher dan promo voucher yang dipakai pada transaksi POS berikut nota, customer, kasir, dan nilai potongannya.', 1),
  (425, 'pos.report.cost_control.index', 'Cost Control POS', 'POS', NULL, 'Dashboard baca-saja untuk analisis pembelian bahan, produksi, waste, HPP, margin, dan kas operasional.', 1),
  (429, 'asset.master_change.index', 'Perubahan Data Aset', 'ASSET', 'ASSET', 'Pengajuan, persetujuan, dan jejak perubahan data master aset yang sudah dikunci.', 1),
  (431, 'pos.printer.connection', 'Koneksi Printer POS', 'POS', NULL, 'Koneksi fisik printer dan agent lokal.', 1),
  (433, 'pos.printer.general', 'Tampilan Umum Cetak POS', 'POS', NULL, 'Branding dan data umum cetak per outlet.', 1),
  (435, 'pos.printer.layout', 'Layout Cetak POS', 'POS', NULL, 'Pengaturan data yang tampil atau disembunyikan pada dokumen.', 1),
  (437, 'pos.printer.rule', 'Aturan Cetak POS', 'POS', NULL, 'Aturan event, sumber order, printer tujuan, layout, dan copy.', 1),
  (439, 'pos.printer.monitor', 'Monitor Cetak POS', 'POS', NULL, 'Riwayat target cetak, hasil agent, dan kegagalan reprint.', 1),
  (441, 'pos.printer.guide', 'Panduan Printer POS', 'POS', NULL, 'Panduan operator dan teknisi printer POS.', 1),
  (443, 'pos.customer_review.index', 'Ulasan Pelanggan POS', 'POS', NULL, 'Daftar dan moderasi ulasan pelanggan yang masuk melalui QR pada struk pembayaran.', 1),
  (445, 'finance.cash_reconciliation.index', 'Rekonsiliasi Kas', 'FINANCE', 'FINANCE', 'Rekonsiliasi saldo sistem dan saldo riil rekening, dengan tindak lanjut mutasi atau transfer yang diaudit.', 1),
  (449, 'pos.reservation.index', 'Reservasi POS', 'POS', NULL, 'Input, verifikasi, DP, dan pemantauan reservasi customer sebelum menjadi order POS resmi.', 1),
  (451, 'finance.revenue_reconciliation.index', 'Rekonsiliasi Pendapatan', 'FINANCE', 'FINANCE', 'Rekonsiliasi omzet POS dengan settlement riil per metode pembayaran.', 1);

INSERT INTO sys_page (id, page_code, page_name, module, matrix_group, description, is_active) VALUES
  (459, 'attendance.meal_calendar.index', 'Kalender Uang Makan', 'ATTENDANCE', 'ATTENDANCE', 'Kalender estimasi uang makan per pegawai dan per hari.', 1);

INSERT INTO sys_menu (id, parent_id, menu_code, menu_label, icon, url, page_id, sort_order, is_active, sidebar_type) VALUES
  (1, NULL, 'dashboard', 'Dashboard', 'ri-home-smile-line', '/', 219, 1, 1, 'MAIN'),
  (2, NULL, 'grp.pos', 'POS & Kasir', 'ri-store-2-line', NULL, NULL, 4, 1, 'MAIN'),
  (3, NULL, 'grp.inventory', 'Inventory', 'ri-archive-stack-line', NULL, NULL, 8, 1, 'MAIN'),
  (4, NULL, 'grp.material', 'Bahan Baku', 'ri-flask-line', NULL, NULL, 18, 0, 'MAIN'),
  (5, NULL, 'grp.production', 'Produksi Base/Prepare', 'ri-tools-line', NULL, NULL, 19, 0, 'MAIN'),
  (6, NULL, 'grp.purchase', 'PO & SR', 'ri-shopping-bag-3-line', '#', NULL, 7, 1, 'MAIN'),
  (7, NULL, 'grp.hr', 'Karyawan & HR', 'ri-group-line', NULL, NULL, 10, 1, 'MAIN'),
  (8, NULL, 'grp.payroll', 'Penggajian', 'ri-money-dollar-circle-line', NULL, NULL, 13, 1, 'MAIN'),
  (9, NULL, 'grp.finance', 'Keuangan', 'ri-wallet-3-line', '#', NULL, 12, 1, 'MAIN'),
  (10, NULL, 'grp.reports', 'Laporan', 'ri-bar-chart-2-line', NULL, NULL, 20, 0, 'MAIN'),
  (11, NULL, 'grp.master', 'Master Data', 'ri-database-2-line', NULL, NULL, 15, 1, 'MAIN'),
  (12, NULL, 'grp.system', 'Sistem', 'ri-settings-3-line', NULL, NULL, 18, 1, 'MAIN'),
  (13, 12, 'sys.users', 'Manajemen User', 'ri-user-settings-line', '/users', 1, 1, 1, 'MAIN'),
  (14, 12, 'sys.roles', 'Manajemen Role', 'ri-shield-keyhole-line', '/roles', 4, 2, 1, 'MAIN'),
  (16, NULL, 'my.home', 'Beranda Saya', 'ri-home-3-line', '/my', 220, 1, 1, 'MY'),
  (17, NULL, 'my.attendance', 'Absensi Saya', 'ri-time-line', '/my/attendance', 221, 2, 1, 'MY'),
  (18, NULL, 'my.leave', 'Pengajuan Izin', 'ri-hotel-bed-line', '/my/leave-requests', 222, 3, 1, 'MY'),
  (19, NULL, 'my.payroll', 'Slip Gaji', 'ri-file-list-3-line', '/my/payroll', 223, 4, 1, 'MY'),
  (20, NULL, 'my.meal', 'Uang Makan', 'ri-restaurant-line', '/my/meal-ledger', 225, 5, 1, 'MY'),
  (21, NULL, 'my.cash_advance', 'Kasbon Saya', 'ri-hand-coin-line', '/my/cash-advance', 226, 10, 1, 'MY'),
  (22, NULL, 'my.profile', 'Kontrak Saya', 'ri-user-3-line', '/my/profile', 224, 11, 1, 'MY'),
  (43, 274, 'master.uom', 'Master UOM', 'ri-ruler-2-line', '/master/uom', 7, 3, 1, 'MAIN'),
  (44, 11, 'master.category', 'Divisi', 'ri-flow-chart', '/master/operational-division', 8, 4, 1, 'MAIN'),
  (45, 274, 'master.item', 'Master Item', 'ri-box-3-line', '/master/item', 15, 4, 1, 'MAIN'),
  (46, 274, 'master.material', 'Bahan Baku', 'ri-flask-line', '/master/material', 14, 5, 1, 'MAIN'),
  (48, 250, 'master.product', 'Product', 'ri-restaurant-line', '/master/product', 17, 4, 1, 'MAIN'),
  (49, 274, 'master.vendor', 'Master Vendor', 'ri-truck-line', '/master/vendor', 18, 6, 1, 'MAIN'),
  (50, 250, 'master.extra', 'Master Extra', 'ri-add-circle-line', '/master/extra', 19, 9, 1, 'MAIN'),
  (51, 250, 'master.extra.group', 'Group Extra', 'ri-menu-add-line', '/master/extra-group', 20, 10, 1, 'MAIN'),
  (61, 250, 'master.product.recipe', 'Resep Produk', 'ri-book-open-line', '/master/relation/product-recipe', 21, 6, 1, 'MAIN'),
  (63, 276, 'master.variable.cost.default', 'Variable Cost Default', 'ri-percent-line', '/master/variable-cost-default', 41, 1, 1, 'MAIN'),
  (67, 250, 'master.product.division', 'Divisi Produk', 'ri-git-merge-line', '/master/product-division', 9, 1, 1, 'MAIN'),
  (68, 250, 'master.product.classification', 'Klasifikasi Produk', 'ri-git-branch-line', '/master/product-classification', 10, 2, 1, 'MAIN'),
  (69, 250, 'master.product.category', 'Kategori Produk', 'ri-node-tree', '/master/product-category', 11, 3, 1, 'MAIN'),
  (70, 274, 'master.item.category', 'Kategori Item/Bahan Baku', 'ri-price-tag-3-line', '/master/item-category', 12, 1, 1, 'MAIN'),
  (71, 274, 'master.component.category', 'Kategori Component', 'ri-price-tag-2-line', '/master/component-category', 13, 2, 1, 'MAIN'),
  (72, 250, 'master.product.extra.map', 'Mapping Extra Produk', 'ri-links-line', '/master/relation/product-extra', 23, 11, 1, 'MAIN'),
  (111, 12, 'sys.sidebar.manage', 'Manajemen Sidebar', 'ri-node-tree', '/sidebar/manage', 65, 3, 1, 'MAIN'),
  (113, 6, 'purchase.order', 'Purchase Order', 'ri-shopping-cart-line', '/purchase', 67, 1, 1, 'MAIN'),
  (115, 221, 'purchase.stock.warehouse', 'Posisi Stok Gudang', 'ri-building-2-line', '/inventory/stock/warehouse', 70, 2, 1, 'MAIN'),
  (116, 222, 'purchase.stock.division', 'Stok Bahan Baku Live', 'ri-store-2-line', '/inventory/stock/division', 71, 3, 1, 'MAIN'),
  (125, 6, 'purchase.receipt', 'Receipt Purchase', 'ri-inbox-archive-line', '/purchase/receipt', 78, 7, 1, 'MAIN'),
  (126, 11, 'master.purchase.posting_type', 'Master Posting Type', 'ri-file-list-3-line', '/master/posting-type', 79, 5, 1, 'MAIN'),
  (127, 11, 'master.purchase.purchase_type', 'Master Purchase Type', 'ri-shopping-bag-2-line', '/master/purchase-type', 80, 6, 1, 'MAIN'),
  (128, 11, 'master.purchase.catalog', 'Master Purchase Catalog', 'ri-book-shelf-line', '/master/purchase-catalog', 81, 8, 1, 'MAIN'),
  (140, 9, 'finance.company_account', 'Kas Perusahaan', 'ri-bank-line', '/finance/accounts', 92, 1, 1, 'MAIN'),
  (141, 9, 'finance.mutation', 'Mutasi Keuangan', 'ri-exchange-funds-line', '/finance/mutations', 93, 2, 1, 'MAIN'),
  (142, 221, 'purchase.stock.warehouse.movement', 'Keluar Masuk Gudang', 'ri-arrow-left-right-line', '/inventory/stock/warehouse/movement', 94, 6, 1, 'MAIN'),
  (143, 221, 'purchase.stock.warehouse.daily', 'Stok Bulanan / Daily Gudang', 'ri-calendar-check-line', '/inventory/stock/warehouse/daily', 95, 4, 1, 'MAIN'),
  (144, 222, 'purchase.stock.division.movement', 'Log Bahan Baku', 'ri-shuffle-line', '/inventory/stock/division/movement', 96, 8, 1, 'MAIN'),
  (145, 222, 'purchase.stock.division.daily', 'Stok Bahan Baku Bulanan', 'ri-calendar-2-line', '/inventory/stock/division/daily', 97, 4, 1, 'MAIN'),
  (146, 6, 'purchase.order.log', 'Log Purchase', 'ri-file-list-3-line', '/purchase-orders/logs', 98, 4, 1, 'MAIN'),
  (147, 6, 'purchase.rebuild.impact', 'Rebuild Impact', 'ri-refresh-line', '/purchase/rebuild-impact', 99, 6, 1, 'MAIN'),
  (148, 221, 'purchase.stock.warehouse.matrix', 'Daily Gudang Matrix', 'ri-bar-chart-horizontal-line', '/inventory-warehouse-daily', 100, 1, 1, 'MAIN'),
  (149, 222, 'purchase.stock.material.matrix', 'Daily Material Matrix', 'ri-line-chart-line', '/inventory-material-daily', 101, 2, 1, 'MAIN'),
  (151, 221, 'purchase.stock.opening.warehouse', 'Opening Gudang', 'ri-archive-drawer-line', '/inventory/stock/opening/warehouse', 103, 3, 1, 'MAIN'),
  (152, 222, 'purchase.stock.opening.division', 'Opening Manual Bahan Baku', 'ri-archive-drawer-line', '/inventory/stock/opening/division', 104, 9, 1, 'MAIN'),
  (153, 185, 'hr.org-division', 'Divisi Organisasi', 'ri-git-branch-line', '/master/org-division', 105, 1, 1, 'MAIN'),
  (154, 185, 'hr.org-position', 'Jabatan Organisasi', 'ri-user-star-line', '/master/org-position', 106, 2, 1, 'MAIN'),
  (155, 186, 'hr.org-employee', 'Data Pegawai', 'ri-team-line', '/master/org-employee', 107, 1, 1, 'MAIN'),
  (156, 187, 'hr.att-shift', 'Master Shift', 'ri-time-line', '/master/att-shift', 108, 2, 1, 'MAIN'),
  (157, 187, 'hr.att-location', 'Lokasi Absensi', 'ri-map-pin-line', '/master/att-location', 109, 4, 1, 'MAIN'),
  (158, 187, 'hr.att-holiday', 'Hari Libur', 'ri-calendar-event-line', '/master/att-holiday', 110, 6, 1, 'MAIN'),
  (159, 8, 'pay.component', 'Komponen Gaji', 'ri-wallet-3-line', '/master/pay-component', 111, 4, 1, 'MAIN'),
  (160, 8, 'pay.profile', 'Profil Gaji', 'ri-file-settings-line', '/master/pay-profile', 112, 5, 1, 'MAIN'),
  (161, 8, 'pay.assignment', 'Assignment Profil', 'ri-links-line', '/master/pay-assignment', 113, 6, 1, 'MAIN'),
  (168, 187, 'hr.att-settings', 'Pengaturan Absensi', 'ri-settings-3-line', '/attendance/settings', 114, 1, 1, 'MAIN'),
  (169, 188, 'hr.att-daily', 'Rekap Absensi', 'ri-calendar-check-line', '/attendance/daily', 115, 2, 1, 'MAIN'),
  (170, 188, 'hr.att-logs', 'Log Presensi', 'ri-fingerprint-line', '/attendance/logs', 116, 3, 1, 'MAIN'),
  (171, 187, 'hr.att-schedules', 'Jadwal Shift', 'ri-time-line', '/attendance/schedules', 117, 3, 1, 'MAIN'),
  (175, 8, 'hr.att-pending', 'Pengajuan Absensi', 'ri-file-edit-line', '/attendance/pending-requests', 122, 1, 1, 'MAIN'),
  (179, 186, 'hr.contract-template', 'Template Kontrak', 'ri-file-text-line', '/master/hr-contract-template', 129, 4, 1, 'MAIN'),
  (180, 186, 'hr.contract', 'Kontrak Pegawai', 'ri-article-line', '/hr/contracts', 130, 3, 1, 'MAIN'),
  (183, 186, 'hr.contract-master', 'Kontrak Pegawai (Master)', 'ri-database-2-line', '/master/hr-contract', 130, 2, 1, 'MAIN'),
  (185, 7, 'org.menu', 'Organisasi', 'ri-organization-chart', NULL, NULL, 1, 1, 'MAIN'),
  (186, 7, 'org.emp', 'Karyawan', 'ri-team-line', NULL, NULL, 2, 1, 'MAIN'),
  (187, 7, 'attend.menu', 'Master Attendance', 'ri-calendar-check-line', NULL, NULL, 3, 1, 'MAIN'),
  (188, 7, 'attend.report', 'Laporan Absen', 'ri-checkbox-circle-line', NULL, NULL, 4, 1, 'MAIN'),
  (189, 8, 'pay.basic-salary', 'Standar Gaji Pokok', 'ri-money-dollar-box-line', '/master/pay-basic-salary', 133, 7, 1, 'MAIN'),
  (190, 8, 'pay.objective-override', 'Override Tunjangan', 'ri-wallet-line', '/master/pay-objective-override', 134, 8, 1, 'MAIN'),
  (191, 8, 'pay.preview-thp', 'Preview THP', 'ri-line-chart-line', '/payroll/preview-thp', 135, 9, 1, 'MAIN'),
  (192, 188, 'hr.att-anomalies', 'Anomali Absensi', 'ri-alert-line', '/attendance/anomalies', 136, 4, 1, 'MAIN'),
  (193, 188, 'hr.att-master-health', 'Kesehatan Data HR', 'ri-heart-pulse-line', '/attendance/master-health', 137, 5, 1, 'MAIN'),
  (195, 188, 'hr.att-estimate', 'Estimasi Gaji', 'ri-calculator-line', '/attendance/estimate', 138, 1, 1, 'MAIN'),
  (197, 187, 'hr.att-schedules-v2', 'Jadwal Shift V2', 'ri-calendar-schedule-line', '/attendance/schedules-v2', 117, 5, 1, 'MAIN'),
  (198, 8, 'hr.att-overtime', 'Input Lembur', 'ri-time-line', '/attendance/overtime-entries', 140, 2, 1, 'MAIN'),
  (199, 8, 'pay.manual-adjustment', 'Adj. Gaji Manual', 'ri-scales-3-line', '/payroll/manual-adjustments', 141, 3, 1, 'MAIN'),
  (201, 7, 'hr.att-ph-assignment', 'Assignment PH', 'ri-user-star-line', '/attendance/ph-assignments', 142, 5, 1, 'MAIN'),
  (202, 7, 'hr.att-ph-ledger', 'Ledger PH', 'ri-file-list-2-line', '/attendance/ph-ledger', 143, 6, 1, 'MAIN'),
  (203, 7, 'hr.att-ph-recap', 'Rekap PH', 'ri-bar-chart-box-line', '/attendance/ph-recap', 144, 7, 1, 'MAIN'),
  (204, NULL, 'my.overtime', 'Lembur Saya', 'ri-time-line', '/my/overtime', 145, 6, 1, 'MY'),
  (205, NULL, 'my.ph', 'PH Saya', 'ri-calendar-check-line', '/my/ph-ledger', 146, 7, 1, 'MY'),
  (206, NULL, 'my.adjustment', 'Tambahan/Pengurangan', 'ri-scales-3-line', '/my/manual-adjustments', 147, 9, 1, 'MY'),
  (208, 8, 'pay.meal-disbursement', 'Pencairan Uang Makan', 'ri-restaurant-2-line', '/payroll/meal-disbursements', 151, 10, 1, 'MAIN'),
  (209, 8, 'pay.salary-disbursement', 'Pencairan Gaji', 'ri-bank-card-line', '/payroll/payroll-periods', 152, 11, 1, 'MAIN'),
  (210, 8, 'pay.cash-advance', 'Kasbon Pegawai', 'ri-hand-coin-line', '/payroll/cash-advances', 153, 12, 1, 'MAIN'),
  (211, 11, 'master.bank', 'Master Bank', 'ri-bank-line', '/master/bank', 154, 3, 1, 'MAIN'),
  (212, 188, 'hr.att-meal-calendar', 'Estimasi Uang Makan', 'ri-restaurant-2-line', '/attendance/meal-calendar', 459, 6, 1, 'MAIN'),
  (213, 6, 'procurement.workbench', 'Procurement Workbench', 'ri-git-merge-line', '/procurement/workbench', 155, 10, 0, 'MAIN'),
  (215, 6, 'procurement.division', 'PO / SR Divisi', 'ri-inbox-line', '/procurement/division-po-sr', 157, 3, 1, 'MAIN');

INSERT INTO sys_menu (id, parent_id, menu_code, menu_label, icon, url, page_id, sort_order, is_active, sidebar_type) VALUES
  (218, 6, 'procurement.store-request', 'Store Request', 'ri-inbox-archive-line', '/store-requests', 160, 2, 1, 'MAIN'),
  (219, 6, 'purchase.reclassify-profile-domain', 'Reclassify Profile', 'ri-shuffle-line', '/purchase/reclassify-profile-domain', 163, 8, 1, 'MAIN'),
  (221, 3, 'inventory.stock.group.warehouse', 'Stok Gudang', 'ri-building-2-line', NULL, NULL, 1, 1, 'MAIN'),
  (222, 3, 'inventory.stock.group.division', 'Stok Divisi', 'ri-store-2-line', NULL, NULL, 2, 1, 'MAIN'),
  (223, 254, 'production.component.stock', 'Stok Base/Prepare', 'ri-scales-3-line', '/production/component-stock', 165, 9, 1, 'MAIN'),
  (224, 254, 'production.component.movement', 'Mutasi Base/Prepare', 'ri-exchange-funds-line', '/production/component-movements', 166, 8, 1, 'MAIN'),
  (225, 254, 'production.component.daily', 'Daily Base/Prepare', 'ri-calendar-check-line', '/production/component-daily', 167, 3, 1, 'MAIN'),
  (226, 254, 'production.component.batch', 'Batch Produksi', 'ri-flask-line', '/production/component-batches', 170, 1, 1, 'MAIN'),
  (227, 254, 'production.component.opening', 'Opening Base/Prepare', 'ri-inbox-archive-line', '/production/component-openings', 168, 4, 1, 'MAIN'),
  (228, 254, 'production.component.adjustment', 'Adjustment Base/Prepare', 'ri-equalizer-3-line', '/production/component-adjustments', 169, 5, 1, 'MAIN'),
  (229, 254, 'production.component.monthly', 'Opname Bulanan Base/Prepare', 'ri-file-chart-line', '/production/component-monthly', 171, 7, 1, 'MAIN'),
  (230, 253, 'production.component.category', 'Kategori Base/Prepare', 'ri-price-tag-2-line', '/production/component-categories', 172, 1, 1, 'MAIN'),
  (231, 253, 'production.component.master', 'Master Base/Prepare', 'ri-tools-line', '/production/component-masters', 173, 2, 1, 'MAIN'),
  (232, 253, 'production.component.formula', 'Resep/Formula Base/Prepare', 'ri-function-line', '/production/component-formulas', 174, 3, 1, 'MAIN'),
  (240, 221, 'purchase.stock.warehouse.lot', 'Lot Gudang', 'ri-stack-line', '/inventory/stock/warehouse/lot', 70, 8, 1, 'MAIN'),
  (241, 222, 'purchase.stock.division.lot', 'Lot Bahan Baku', 'ri-stack-line', '/inventory/stock/division/lot', 71, 11, 1, 'MAIN'),
  (242, 221, 'purchase.stock.adjustment.warehouse', 'Adjustment Gudang', 'ri-scales-3-line', '/inventory/stock/adjustment/warehouse', 176, 5, 1, 'MAIN'),
  (243, 222, 'purchase.stock.adjustment.division', 'Adjustment Bahan Baku', 'ri-scales-3-line', '/inventory/stock/adjustment/division', 177, 7, 1, 'MAIN'),
  (248, 11, 'master.purchase.catalog_vendor', 'Master Purchase Catalog Vendor', 'ri-links-line', '/master/purchase-catalog-vendor', 182, 9, 1, 'MAIN'),
  (249, NULL, 'produk', 'Produk', 'ri-store-2-line', NULL, NULL, 9, 1, 'MAIN'),
  (250, 249, 'produk.master', 'Master Produk', 'ri-folders-line', NULL, NULL, 1, 1, 'MAIN'),
  (251, 250, 'produk.master.data', 'Data Produk', 'ri-restaurant-line', NULL, NULL, 5, 1, 'MAIN'),
  (252, NULL, 'produk.master.extra', 'Extra Produk', 'ri-add-circle-line', NULL, NULL, 22, 0, 'MAIN'),
  (253, 249, 'production.component.group.master', 'Master Base/Prepare', 'ri-book-shelf-line', NULL, NULL, 2, 1, 'MAIN'),
  (254, 3, 'production.component.group.transaction', 'Stok Base/Prepare', 'ri-exchange-funds-line', NULL, NULL, 3, 1, 'MAIN'),
  (255, 5, 'production.component.group.monitoring', 'Monitoring Stok', 'ri-line-chart-line', NULL, NULL, 1, 0, 'MAIN'),
  (256, 254, 'production.component.lot', 'Lot Component', 'ri-stack-line', '/production/component-lots', 259, 12, 1, 'MAIN'),
  (257, 6, 'purchase.report', 'Laporan Purchase', 'ri-file-chart-line', '/purchase-orders/report', 183, 5, 1, 'MAIN'),
  (259, 2, 'pos.payment-method', 'Payment Method POS', 'ri-bank-card-line', '/pos/payment-methods', 185, 9, 1, 'MAIN'),
  (260, 2, 'pos.outlet-terminal', 'Outlet + Terminal POS', 'ri-store-3-line', '/pos/outlets-terminals', 186, 6, 1, 'MAIN'),
  (261, 250, 'master.product.bundle', 'Bundle Produk', 'ri-gift-2-line', '/master/relation/product-bundle', 187, 7, 1, 'MAIN'),
  (264, 2, 'pos.printer', 'Printer POS', 'ri-printer-line', '/pos/printers', 190, 12, 1, 'MAIN'),
  (265, 2, 'pos.order.draft', 'Draft Order POS', 'ri-shopping-bag-3-line', '/pos/orders/draft', 191, 13, 1, 'MAIN'),
  (266, NULL, 'pos.cashier', 'Kasir POS', 'ri-shopping-bag-3-line', '/pos/cashier', 192, 2, 1, 'MAIN'),
  (267, NULL, 'grp.loyalty', 'Member & Promo', 'ri-user-star-line', NULL, NULL, 11, 1, 'MAIN'),
  (268, 267, 'loyalty.member', 'Member', 'ri-user-heart-line', '/loyalty/members', 193, 1, 1, 'MAIN'),
  (269, 267, 'loyalty.point_rule', 'Poin', 'ri-coin-line', '/loyalty/point-rules', 194, 2, 1, 'MAIN'),
  (270, 267, 'loyalty.stamp_campaign', 'Stamp', 'ri-coupon-3-line', '/loyalty/stamp-campaigns', 195, 3, 1, 'MAIN'),
  (271, 267, 'loyalty.voucher_campaign', 'Voucher', 'ri-ticket-2-line', '/loyalty/voucher-campaigns', 196, 4, 1, 'MAIN'),
  (272, 250, 'master.product.extra.workspace', 'Workspace Extra Produk', 'ri-magic-line', '/master/relation/product-extra-workspace', 197, 8, 1, 'MAIN'),
  (273, 11, 'master.group.product', 'Produk & Extra', 'ri-store-2-line', NULL, NULL, 7, 1, 'MAIN'),
  (274, 11, 'master.group.inventory', 'Item & Bahan', 'ri-flask-line', NULL, NULL, 1, 1, 'MAIN'),
  (275, 11, 'master.group.relation', 'Relasi & Formula', 'ri-links-line', NULL, NULL, 10, 1, 'MAIN'),
  (276, 11, 'master.group.config', 'Konfigurasi', 'ri-settings-3-line', NULL, NULL, 2, 1, 'MAIN'),
  (280, 250, 'product.monitoring.stock', 'Monitoring Stok', 'ri-line-chart-line', NULL, NULL, 12, 1, 'MAIN'),
  (281, 280, 'product.monitoring.availability', 'Ketersediaan Produk', 'ri-bar-chart-grouped-line', '/product/availability', 257, 1, 1, 'MAIN'),
  (285, 2, 'pos.stock.live', 'Stock Live POS', 'ri-pulse-line', '/pos/stock-live', 198, 2, 1, 'MAIN'),
  (286, 2, 'pos.sales-channel', 'Sales Channel POS', 'ri-share-forward-line', '/pos/sales-channels', 199, 11, 1, 'MAIN'),
  (288, 2, 'pos.deposit', 'Deposit / DP POS', 'ri-wallet-3-line', '/pos/deposits', 201, 5, 1, 'MAIN'),
  (289, 222, 'purchase.stock.division.reconcile', 'Audit Bahan Baku', 'ri-scales-3-line', '/inventory/stock/division/reconcile', 202, 12, 1, 'MAIN'),
  (291, 254, 'production.component.reconcile', 'Reconcile Base/Prepare', 'ri-scales-3-line', '/production/component-reconcile', 167, 11, 1, 'MAIN'),
  (292, NULL, 'pos.report.group', 'Laporan POS', 'ri-bar-chart-box-line', NULL, NULL, 6, 1, 'MAIN'),
  (293, 292, 'pos.report.sales', 'Laporan Penjualan POS', 'ri-receipt-line', '/pos/reports/sales', 204, 2, 1, 'MAIN'),
  (294, 292, 'pos.report.sales.detail', 'Laporan Penjualan Produk', 'ri-file-list-3-line', '/pos/reports/sales-detail', 205, 4, 1, 'MAIN'),
  (295, 292, 'pos.report.payment', 'Laporan Pembayaran POS', 'ri-bank-card-line', '/pos/reports/payments', 206, 6, 1, 'MAIN'),
  (296, 292, 'pos.report.refund', 'Laporan Refund POS', 'ri-arrow-go-back-line', '/pos/reports/refunds', 207, 10, 1, 'MAIN'),
  (297, 292, 'pos.report.void', 'Laporan Void POS', 'ri-close-circle-line', '/pos/reports/voids', 208, 11, 1, 'MAIN'),
  (300, 2, 'pos.order.monitor', 'Monitor Dapur / Bar', 'ri-restaurant-2-line', '/pos/order-monitor', 209, 3, 1, 'MAIN'),
  (308, 9, 'finance.cash_vault_daily', 'Laporan Brankas Harian', 'ri-safe-2-line', '/finance-reports/cash-vault-daily', 217, 4, 1, 'MAIN'),
  (310, 292, 'pos.report.cashier.close', 'Laporan Tutup Kasir POS', 'ri-safe-2-line', '/pos/reports/cashier-close', 234, 9, 1, 'MAIN'),
  (313, 292, 'pos.report.daily_sales', 'Daily Sales POS', 'ri-calendar-check-line', '/pos/reports/daily-sales', 235, 1, 1, 'MAIN'),
  (318, 292, 'pos.report.payment.method', 'Laporan Metode Pembayaran POS', 'ri-bank-card-2-line', '/pos/reports/payment-methods', 239, 7, 1, 'MAIN'),
  (319, 292, 'pos.report.payment.account', 'Laporan Rekening Pembayaran POS', 'ri-wallet-3-line', '/pos/reports/payment-accounts', 240, 8, 1, 'MAIN'),
  (322, NULL, 'pos.self_order', 'Self Order', 'ri-qr-code-line', '/pos/self-order', 243, 3, 1, 'MAIN'),
  (323, 2, 'pos.stock.commit.audit', 'Audit Commit Stok', 'ri-scales-3-line', '/pos/stock-commit-audit', 198, 4, 1, 'MAIN'),
  (325, 2, 'pos.order.paid.index', 'Pesanan Terbayar', 'ri-wallet-3-line', '/pos/orders/paid', 244, 1, 1, 'MAIN'),
  (326, 6, 'purchase.material.price_history', 'Riwayat Harga Item', 'ri-line-chart-line', '/purchase/item-price-history', 245, 9, 1, 'MAIN'),
  (330, 12, 'system.dbtools.settings', 'Perlindungan Database', 'ri-shield-check-line', '/dbtools', 249, 4, 1, 'MAIN'),
  (333, 222, 'purchase.stock.opname.division', 'Daily Recon', 'ri-check-double-line', '/inventory/stock/daily-recon/division', 253, 1, 1, 'MAIN'),
  (335, 254, 'production.component.daily.recon', 'Daily Recon Component', 'ri-check-double-line', '/production/component-daily-recon', 265, 2, 1, 'MAIN'),
  (337, 221, 'inventory.stock.opname.warehouse.monthly', 'Opname Gudang', 'ri-file-list-3-line', '/inventory/stock/opname/warehouse/monthly', 267, 7, 1, 'MAIN'),
  (339, 222, 'inventory.stock.opname.division.monthly', 'Opname Bahan Baku', 'ri-file-list-3-line', '/inventory/stock/opname/division/monthly', 269, 10, 1, 'MAIN'),
  (341, 254, 'production.component.opname.monthly', 'Opname Component', 'ri-file-list-3-line', '/production/component-opname', 271, 10, 1, 'MAIN'),
  (349, 9, 'finance.payable', 'Utang', 'ri-hand-coin-line', '/finance/utang', 279, 12, 1, 'MAIN'),
  (351, 9, 'finance.receivable', 'Piutang', 'ri-wallet-2-line', '/finance/piutang', 281, 13, 1, 'MAIN'),
  (353, 9, 'finance.party', 'Pihak Luar', 'ri-team-line', '/finance/relasi', 283, 14, 1, 'MAIN'),
  (355, 9, 'finance.cash_position', 'Posisi Kas & Eksposur', 'ri-funds-box-line', '/finance-reports/cash-position', 285, 3, 1, 'MAIN'),
  (357, 9, 'finance.period_close', 'Tutup Periode', 'ri-calendar-check-line', '/finance-reports/period-close', 287, 10, 1, 'MAIN'),
  (359, 9, 'finance.target', 'Target Keuangan', 'ri-focus-3-line', '/finance-reports/targets', 289, 11, 1, 'MAIN'),
  (361, 8, 'pay.bonus', 'Bonus Pegawai', 'ri-gift-line', '/payroll/bonus', 291, 13, 1, 'MAIN'),
  (363, NULL, 'my.bonus', 'Bonus Saya', 'ri-medal-line', '/my/bonus', 293, 8, 1, 'MY'),
  (365, 254, 'production.component.opening.monthly', 'Opening Bulanan', 'ri-archive-line', '/production/component-opening-monthly', 271, 6, 1, 'MAIN'),
  (371, NULL, 'grp.menu_book', 'Menu Book', 'ri-book-open-line', NULL, NULL, 16, 1, 'MAIN'),
  (373, 371, 'menu_book.index', 'Menu Book', 'ri-restaurant-line', '/menu_book', 299, 1, 1, 'MAIN'),
  (375, 9, 'finance.financial_estimation', 'Estimasi Keuangan', 'ri-line-chart-line', '/finance-reports/financial-estimation', 301, 8, 1, 'MAIN'),
  (377, 9, 'finance.bank_daily_recap', 'Rekap Rekening Harian', 'ri-bank-card-line', '/finance-reports/rekap-rekening-harian', 303, 9, 1, 'MAIN'),
  (379, 9, 'finance.daily_overview', 'Keuangan Harian', 'ri-funds-line', '/finance-reports/daily-overview', 305, 6, 1, 'MAIN'),
  (385, 222, 'inventory.stock.opening.division.generated', 'Stok Awal Bahan Baku', 'ri-archive-drawer-line', '/inventory/stock/stok-awal/division', 311, 6, 1, 'MAIN'),
  (387, 267, 'loyalty.redeem', 'Redeem', 'ri-gift-2-line', '/loyalty/redeem', 313, 5, 1, 'MAIN'),
  (389, 267, 'loyalty.redeem_rule', 'Pengaturan Redeem', 'ri-settings-3-line', '/loyalty/redeem-rules', 315, 7, 1, 'MAIN'),
  (393, 12, 'website.landing_page', 'Pengaturan Landing Page', 'ri-layout-masonry-line', 'landing-page', 319, 5, 1, 'MAIN'),
  (395, 2, 'pos.daily_recon_settings', 'Gate Daily Recon', 'ri-shield-check-line', '/pos/daily-recon-settings', 321, 14, 1, 'MAIN'),
  (401, 222, 'purchase.stock.transfer.division', 'Mutasi Bahan Baku', 'ri-share-forward-2-line', '/inventory/stock/transfer/division', 327, 5, 1, 'MAIN'),
  (403, NULL, 'grp.wa', 'WhatsApp', 'ri-whatsapp-line', '#', NULL, 17, 1, 'MAIN'),
  (405, 403, 'wa.dashboard', 'Dashboard', 'ri-dashboard-line', 'wa/dashboard', 329, 1, 1, 'MAIN'),
  (407, 403, 'wa.broadcast', 'Broadcast', 'ri-broadcast-line', 'wa/broadcast', 331, 2, 1, 'MAIN'),
  (409, 403, 'wa.template', 'Template Pesan', 'ri-file-text-line', 'wa/template', 333, 3, 1, 'MAIN'),
  (411, 403, 'wa.group', 'Grup WA', 'ri-group-2-line', 'wa/group', 335, 5, 1, 'MAIN'),
  (413, 403, 'wa.log', 'Log Pengiriman', 'ri-history-line', 'wa/log', 337, 7, 1, 'MAIN'),
  (415, 403, 'wa.settings', 'Pengaturan', 'ri-settings-3-line', 'wa/settings', 339, 8, 1, 'MAIN');

INSERT INTO sys_menu (id, parent_id, menu_code, menu_label, icon, url, page_id, sort_order, is_active, sidebar_type) VALUES
  (431, 249, 'production.roastery.group', 'Roastery', 'ri-cup-line', NULL, NULL, 3, 1, 'MAIN'),
  (433, 431, 'production.roastery.packaging_label', 'Label Packaging Kopi', 'ri-price-tag-3-line', '/roastery/packaging-labels', 353, 1, 1, 'MAIN'),
  (447, 2, 'pos.online_food', 'Online Food', 'ri-takeaway-line', NULL, NULL, 7, 1, 'MAIN'),
  (449, 447, 'pos.online_food.settings', 'Settings Online Food', 'ri-settings-3-line', '/pos/online-food/settings', 361, 2, 1, 'MAIN'),
  (455, 447, 'pos.online_food.orders', 'Orderan Online Food', 'ri-file-list-3-line', '/pos/online-food/orders', 361, 1, 1, 'MAIN'),
  (457, 292, 'pos.report.sales.extra', 'Laporan Penjualan Extra', 'ri-add-box-line', '/pos/reports/sales-extra', 365, 5, 1, 'MAIN'),
  (459, NULL, 'grp.asset', 'Aset', 'ri-archive-2-line', '#', NULL, 14, 1, 'MAIN'),
  (461, 459, 'asset.item', 'Daftar Aset', 'ri-list-check-3', '/asset-management', 367, 1, 1, 'MAIN'),
  (463, 459, 'asset.damage', 'Lapor Rusak', 'ri-camera-lens-line', '/asset-management/damage', 369, 2, 1, 'MAIN'),
  (465, 459, 'asset.recon', 'Rekon Bulanan', 'ri-calendar-check-line', '/asset-management/recon', 371, 3, 1, 'MAIN'),
  (467, 459, 'asset.transfer', 'Mutasi Aset', 'ri-arrow-left-right-line', '/asset-management/transfer', 373, 5, 1, 'MAIN'),
  (469, 459, 'asset.label', 'QR Label', 'ri-fingerprint-line', '/asset-management/labels', 375, 6, 1, 'MAIN'),
  (471, 459, 'asset.maintenance', 'Maintenance', 'ri-tools-line', '/asset-management/maintenance', 377, 7, 1, 'MAIN'),
  (473, 459, 'asset.handover', 'Serah Terima', 'ri-user-follow-line', '/asset-management/handover', 379, 8, 1, 'MAIN'),
  (475, 459, 'asset.disposal', 'Disposal', 'ri-delete-bin-line', '/asset-management/disposal', 381, 9, 1, 'MAIN'),
  (477, 459, 'asset.depreciation', 'Penyusutan', 'ri-line-chart-line', '/asset-management/depreciation', 383, 10, 1, 'MAIN'),
  (491, 403, 'wa.manual', 'Kirim Manual', 'ri-send-plane-line', 'wa/manual', 397, 6, 1, 'MAIN'),
  (493, 403, 'wa.report_schedule', 'Jadwal Laporan', 'ri-calendar-schedule-line', 'wa/template/schedules', 399, 4, 1, 'MAIN'),
  (495, 3, 'inventory.stock.group.control', 'Kontrol Stok', 'ri-shield-check-line', NULL, NULL, 4, 1, 'MAIN'),
  (497, 495, 'inventory.stock.deficit', 'Defisit Stok', 'ri-error-warning-line', '/inventory/stock/deficits', 401, 1, 1, 'MAIN'),
  (499, 495, 'inventory.stock.period', 'Tutup Periode Stok', 'ri-calendar-check-line', '/inventory/stock/periods', 403, 2, 1, 'MAIN'),
  (507, 495, 'inventory.stock.health', 'Kesehatan Stok Aktif', 'ri-heart-pulse-line', '/inventory/stock/health', 409, 3, 1, 'MAIN'),
  (509, 495, 'inventory.stock.value_reconciliation', 'Koreksi Nilai Stok', 'ri-money-dollar-circle-line', '/inventory/stock/value-reconciliation', 411, 4, 1, 'MAIN'),
  (511, 495, 'inventory.stock.integrity_audit', 'Audit Integritas Stok', 'ri-shield-check-line', '/inventory/stock/integrity-audit', 413, 5, 1, 'MAIN'),
  (513, 9, 'finance.sales_margin.pos', 'Penjualan & Margin POS', 'ri-line-chart-line', '/pos/reports/sales', 204, 13, 0, 'MAIN'),
  (515, 292, 'pos.report.sales.audit', 'Audit Penjualan & HPP', 'ri-shield-search-line', '/pos/reports/sales-audit', 415, 12, 1, 'MAIN'),
  (517, 2, 'pos.availability.queue', 'Ketersediaan POS', 'ri-refresh-line', '/pos/availability-queue', 417, 8, 1, 'MAIN'),
  (521, 267, 'loyalty.voucher_usage', 'Pemakaian Voucher', 'ri-coupon-2-line', '/loyalty/voucher-usages', 421, 6, 1, 'MAIN'),
  (525, 292, 'pos.report.cost_control', 'Cost Control POS', 'ri-funds-box-line', '/pos/reports/cost-control', 425, 3, 1, 'MAIN'),
  (529, 459, 'asset.master_change', 'Perubahan Data', 'ri-file-edit-line', '/asset-management/changes', 429, 4, 1, 'MAIN'),
  (531, 2, 'pos.customer_review', 'Ulasan Pelanggan', 'ri-star-smile-line', '/pos/customer-reviews', 443, 10, 1, 'MAIN'),
  (535, 9, 'finance.cash_reconciliation', 'Rekonsiliasi Kas', 'ri-scales-3-line', '/finance-reports/cash-reconciliation', 445, 5, 1, 'MAIN'),
  (539, NULL, 'pos.reservation', 'Reservasi', 'ri-calendar-check-line', '/pos/reservations', 449, 5, 1, 'MAIN'),
  (541, 9, 'finance.revenue_reconciliation', 'Rekonsiliasi Pendapatan', 'ri-hand-coin-line', '/finance-reports/revenue-reconciliation', 451, 7, 1, 'MAIN'),
  (559, 221, 'inventory.stock.opening.warehouse.generated', 'Stok Awal Gudang', 'ri-archive-drawer-line', '/inventory/stock/stok-awal/warehouse', 70, 9, 1, 'MAIN');

INSERT INTO sys_page_alias (id, alias_code, page_id, description, is_active) VALUES
  (1, 'attendance.schedules.v2.index', 117, 'Alias jadwal attendance v2', 1),
  (2, 'my.schedule.index', 221, 'Alias jadwal portal pegawai', 1),
  (3, 'pos.stock.commit.audit.index', 198, 'Alias audit commit stok POS', 1),
  (4, 'product.monitoring.availability.index', 257, 'Alias monitoring ketersediaan produk', 1),
  (5, 'production.component.lot.index', 259, 'Alias lot komponen produksi', 1),
  (6, 'production.component.reconcile.index', 167, 'Alias rekonsiliasi komponen produksi', 1),
  (7, 'purchase.account.index', 92, 'Alias akun pembelian', 1),
  (8, 'purchase.stock.division.lot.index', 71, 'Alias lot stok divisi', 1),
  (9, 'purchase.stock.opening.index', 103, 'Alias stok awal gudang', 1),
  (10, 'purchase.stock.warehouse.lot.index', 70, 'Alias lot stok gudang', 1);

INSERT INTO auth_role (role_code, role_name, description, division_scope_id, is_active) VALUES
  ('SUPERADMIN', 'Super Admin', 'Bypass semua izin, akses penuh', NULL, 1);

INSERT INTO auth_role_permission
  (role_id, page_id, can_view, can_create, can_edit, can_delete, can_export, created_at)
SELECT role.id, page.id, 1, 1, 1, 1, 1, CURRENT_TIMESTAMP
FROM auth_role role CROSS JOIN sys_page page
WHERE role.role_code = 'SUPERADMIN' AND role.is_active = 1;

COMMIT;
SET FOREIGN_KEY_CHECKS=1;
